### ISSUE TITLE
Not able to use LiveActivityEvent class in the depenedcy

### ISSUE THREAD

**Issue by vincedprime** [relayrides/pushy#1054]
I am using 0.15.5-SNAPSHOT.
Not sure why I'm not able to get LiveActivityEvent enum. Can use other utility class
<img width="575" alt="image" src="https://github.com/jchambers/pushy/assets/62996220/91c42c7e-ad2b-4d03-aaa9-a0e18cf42c2e">
<img width="300" alt="image" src="https://github.com/jchambers/pushy/assets/62996220/dc4e6e4e-65fb-4660-9ead-e680546f0125">

**Comment by vincedprime** [comment]
It's working with 0.15.2. But only the UPDATE and END activity are present
<img width="298" alt="image" src="https://github.com/jchambers/pushy/assets/62996220/720fe8b3-46ca-469d-b937-1849b9ca9c90">
@jchambers any thing I'm doing wrong?

**Comment by jchambers** [comment]
This appears to be a request for general support; let's move this to a discussion rather than an issue.
