### ISSUE TITLE
Optimize APNs payload construction

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#11]
To make sure an APNs payload fits within a certain size, we repeatedly regenerate the payload JSON object with different message body lengths. Our current approach could be improved in two important ways:

1. Just regenerate the message body string instead of the entire payload
2. Use a binary search instead of a linear walk to seek to the right message body length (maybe?)

**Comment by lpandzic** [comment]
I've been looking through changelogs while updating our dependency and seen this:

> Jackson (or other libraries) that work by serializing POJOs deprive us of the expressive flexibility we need to reach all of those cases (i.e. there isn't a good way to differentiate between "present and null" and "not present").

Jackson is not limited to pojo processing mode: there are other modes, such as [Tree Model](http://wiki.fasterxml.com/JacksonTreeModel). Take a look at the 'Constructing Tree Model instances from Scratch' section.

**Comment by jchambers** [comment]
FWIW, we switched to Gson a while ago.

**Comment by lpandzic** [comment]
Yeah, sorry, totally didn't see the date of that comment.
