### ISSUE TITLE
MISSING_TOKEN exception while using pushManager.shutdown command

### ISSUE THREAD

**Issue by EnesKorukcu** [relayrides/pushy#141]
I'm trying to send a push with valid token. But i'm getting MISSING_TOKEN exception. 
If i delete pushManager.shutdown line, push successfully arrives. 
If i dont delete pushManager.shutdown line, i'm getting missing token exception. 

Documentation says the opposite: 
"By the time you shut down the PushManager (as long as you don't give the shutdown process a timeout), the notification is guaranteed to have either been accepted or rejected by the APNs gateway."

**Comment by jchambers** [comment]
I updated the README in 31b3c8f. Please let us know if you think additional clarification is needed. Cheers!
