### ISSUE TITLE
Direct memory exhausted after sending many notifications

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#142]
Most of the details so far have been posted to [a mailing list thread](https://groups.google.com/d/msg/pushy-apns/W3b24t1PkHY/QnU_QpqnYF0J), but to recap:

1. When sending notifications, we'll sometimes run out of direct memory when attempting to write a notification to a channel in `ApnsConnection`. We thought this was fixed when Netty 4.0.24 came out (see #138), but the issue still seems to persist.
2. Just sending zillions of notifications to a mock server results in stable memory usage, though the problem crops up in real-world usage. We suspect the problem is centered around connection closure/rejected notifications.
3. We don't run out of direct memory until many (millions, we think) of notifications have been sent under real-world conditions.
4. The problem appears to be that *something* in a Netty event loop is (a) persisting longer than it should ~~and (b) holding a reference to an `ApnsConnection`, which is causing a leak~~ (that last part doesn't make sense, since that *shouldn't* be taking up any direct memory).

**Comment by jchambers** [comment]
Of interest: http://blog.csdn.net/jiangguilong2000/article/details/42297873

**Comment by jchambers** [comment]
Oh, hey, @ylgrgyq, that's your blog post, isn't it? ;)

**Comment by sunng87** [comment]
We confirm upgrading Netty 4.0.25 doesn't help. Also I'm afraid the direct memory leak only happens to secure connection. We have another application running on Netty and suffering the leak.

Still haven't got anything valuable for debugging.

**Comment by ylgrgyq** [comment]
> Oh, hey, @ylgrgyq, that's your blog post, isn't it? ;)

haha, sorry, that's not me. That's a poor Chinese programmer who confront with the same problem as me. 
I wonder how do you find that blog and how do you know I'm a Chinese? Please don't tell me you conclude that from my poor English. ;)

**Comment by ylgrgyq** [comment]
> We confirm upgrading Netty 4.0.25 doesn't help

I saw this issue was reopened. https://github.com/netty/netty/issues/3166

**Comment by jchambers** [comment]
> I wonder how do you find that blog and how do you know I'm a Chinese?

Found it by searching (via Google) for other people having the same problem. I thought it was you because it's exactly the same problem/data you reported, but I guess not!

**Comment by ylgrgyq** [comment]
Hi, it's me again.
As you mentioned here https://github.com/relayrides/pushy/issues/139, netty has a high/low water mark for their write buffers, and once the high water mark is hit, channel becomes unwritable. But I found that this unwritable mark is not mandatory, you still can write msg to the channel which marked as "unwritable".  Please check this mark in ChannelOutboundBuffer.

So I think maybe whenever pushy want to write some bytes to a channel, pushy should check the writability of this channel by calling isWritable function in io.netty.channel.AbstractChannel. If it's false, pushy should block by itself for some time until the isWritable returns true.

**Comment by jchambers** [comment]
We have [writability change listeners](https://github.com/relayrides/pushy/blob/master/src/main/java/com/relayrides/pushy/apns/PushManager.java#L745) that remove channels from the active pool when they become unwritable. Do you think that's insufficient?

**Comment by ylgrgyq** [comment]
Ah, yes, I think this is OK. Sorry, I miss this listener before.  :stuck_out_tongue_winking_eye:

**Comment by jchambers** [comment]
No worries at all! The thought is very much appreciated, and I just wanted to make sure we hadn't made a mistake in the implementation (which is entirely possible!). Thanks for looking into it!

**Comment by jchambers** [comment]
We just released Pushy 0.5, which has support for Apple's new HTTP/2-based protocol. I'm hoping that, by virtue of basically rewriting everything from scratch (whew) this issue will go away. Let's keep an eye on it and—I hope!—close this issue with confidence soon.

**Comment by jchambers** [comment]
@ylgrgyq @sunng87: have either of you had a chance to try out Pushy v0.5? Does this issue still seem to persist after the update?

Thanks kindly!

**Comment by ylgrgyq** [comment]
Very sorry for not seeing your comment for so long time.
We are working on upgrading Pushy to version 0.5. We'll come back as soon as possible after battle tested it. Thanks a lot for your reminder.

**Comment by jchambers** [comment]
No worries at all! Thanks for looking into it!

**Comment by jchambers** [comment]
We've gone several months without new reports of this issue; I'm going to close this for now. Please post a comment if you see even the slightest hint of direct memory exhaustion going forward. Thanks!
