### ISSUE TITLE
Extended payloads only supported under iOS 8 and newer

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#151]
Apple has, at last, updated [their docs](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW9) to cover the expanded payloads announced at WWDC 2014. However, the docs describe a situation a little more nuanced than I think we're currently reflecting in our own docs and API design:

> In iOS 8 and later, the maximum size allowed for a notification payload is 2 kilobytes; Apple Push Notification service refuses any notification that exceeds this limit. (Prior to iOS 8 and in OS X, the maximum payload size is 256 bytes.)

We should certainly update our own docs and probably update the payload construction tools, too.

**Comment by flozano** [comment]
This is a mess :(

**Comment by jchambers** [comment]
> How do you plan to tackle this?

My initial thought is something like:

```java
ApnsPayloadBuilder#buildWithDefaultMaximumPayloadLength(final IOSVersion version);
```

…then have an enum with keys like `IOS_7_AND_OLDER` and `IOS_8_AND_NEWER`. I'm very, very open to feedback here.

**Comment by flozano** [comment]
I think a setting at the payload builder level is the right way, so nothing to suggest over that. I am wondering how to undo the "mess" (I'm sending >256byte messages to iOS 7 and 6 devices).

**Comment by jchambers** [comment]
> I am wondering how to undo the "mess" (I'm sending >256byte messages to iOS 7 and 6 devices).

Yeah—that's ugly. You definitely need to be recording iOS versions along with tokens, which is a bit of a surprise.

Sorry to lead folks into this situation; we decided to add support for expanded payloads even though they weren't documented (although they had been announced and deployed for several months), and clearly that's had some ill effects.

**Comment by jchambers** [comment]
I've opened #174 to address this issue. Since it involves a breaking API change, I think it makes sense to hold off until v0.5 before releasing this, but I'm open to other opinions. Any thoughts (especially you, @flozano)?

Thanks!

**Comment by flozano** [comment]
looks OK to me.

The real mess is on "our" side (storing versions together with tokens), and there's not much pushy can do about it.

**Comment by jchambers** [comment]
The new HTTP/2-based APNs protocol claims that we can now do 4kB payloads to all devices and all OS versions. Closing this unless we learn otherwise.
