### ISSUE TITLE
pushy v0.4.2 doesn't handle INVALID_TOKEN properly

### ISSUE THREAD

**Issue by heqingwei** [relayrides/pushy#155]
In pushy v0.4.2, the if condition verification was newly added to handle the sequence 0 problem. However, this would prevent the notifications after  the notification identified as RejectedNotificationReason.INVALID_TOKEN under the same connection from being added to retry queue in push manager.

```java
if (rejectedNotification.getSequenceNumber() != 0 && RejectedNotificationReason.MISSING_TOKEN.equals(rejectedNotification.getReason())) {

	final Collection<T> unprocessedNotifications =
			this.apnsConnection.sentNotificationBuffer.getAllNotificationsAfterSequenceNumber(
					rejectedNotification.getSequenceNumber());

	if (!unprocessedNotifications.isEmpty()) {
		if (this.apnsConnection.listener != null) {
			this.apnsConnection.listener.handleUnprocessedNotifications(this.apnsConnection, unprocessedNotifications);
		}
	}
}
```

My understanding is that it should not be 

```java
if (rejectedNotification.getSequenceNumber() != 0 && RejectedNotificationReason.MISSING_TOKEN.equals(rejectedNotification.getReason()))
```

but :

```java
if (rejectedNotification.getSequenceNumber() != 0 && !RejectedNotificationReason.MISSING_TOKEN.equals(rejectedNotification.getReason()))
```

Please note that the "!" added by me before "RejectedNotificationReason.MISSING_TOKEN.equals(rejectedNotification.getReason()".

**Comment by jchambers** [comment]
Oops—yes, that does look like a mistake to me, but I'm not sure why the tests would be passing. Will investigate.

**Comment by jchambers** [comment]
> I'm not sure why the tests would be passing…

Ah—because all of the tests use a missing token for their rejected notification.

**Comment by jchambers** [comment]
I removed the problematic check in 59c4a01. I'll put out a new release shortly to address the immediate issue, but will leave this issue open until we've added proper tests.

**Comment by heqingwei** [comment]
Thanks for quick response:-)   I will use the new v0.4.3 instead.

**Comment by jchambers** [comment]
As promised, added a regression test in 80423c9.
