### ISSUE TITLE
Cannot get Notification-ID  to trace success/fail notifcation

### ISSUE THREAD

**Issue by ahmetkarakaya** [relayrides/pushy#160]
I have created two  SimpleApnsPushNotification instances with same token, and payload and put them all into PushManagerQueue.

```java
SimpleApnsPushNotification notification1= new SimpleApnsPushNotification(token, payload, DeliveryPriority.IMMEDIATE);
SimpleApnsPushNotification notification2= new SimpleApnsPushNotification(token, payload, DeliveryPriority.IMMEDIATE);
```

Since sequenceid is created internally and   wrapper in SendableApnsPushNotification, How can differentiate two notifications with the following rejection handling mechanism?

```
   pushManager.registerRejectedNotificationListener(new RejectedNotificationListener<ApnsPushNotification>(){
            @Override
            public void handleRejectedNotification(PushManager pushManager, ApnsPushNotification notification, RejectedNotificationReason rejectionReason) {
               LOGGER.error("Notification cannot be send : "+rejectionReason.getErrorCode());
            }
            
         });
```

**Comment by jchambers** [comment]
Please see https://github.com/relayrides/pushy/wiki/Frequently-asked-questions#can-i-attach-a-unique-id-to-a-push-notification. You can subclass `SimpleApnsPushNotification` and add an ID field or create your own `ApnsPushNotification` implementation that does the same.
