### ISSUE TITLE
Tomcat never starts with pushy 0.4.3

### ISSUE THREAD

**Issue by christophefondacci** [relayrides/pushy#163]
I am upgrading from 0.4 to 0.4.3 using Apache Tomcat Version 8.0.15
When starting with 0.4 => No problem but after a while, some push notification are never received, without any error logged (TRACE level)

So I gave a try to 0.4.3 as you seem to say that there has been improvements regarding threadlocal cleanup and overall support of using pushy in a web container.

When starting with 0.4.3 my server keeps waiting after the line "PushManager;Connection succeeded: ApnsConnection...",  and eventually shuts down. If I don't change anything but the lib version back to 0.4, everything works fine.

	INFO ;2015-04-10 01:51:44,809;localhost-startStop-1;BasicTilesContainer;Initializing Tiles2 container. . .
	DEBUG;2015-04-10 01:51:45,419;nioEventLoopGroup-2-1;ApnsConnection$2$1;PelmelPush-connection-0 successfully completed TLS handshake.
	TRACE;2015-04-10 01:51:45,420;nioEventLoopGroup-2-1;PushManager;Connection succeeded: ApnsConnection [name=PelmelPush-connection-0]
	INFO ;2015-04-10 01:53:52,198;localhost-startStop-1;TilesAccess;Removing TilesContext for context: org.apache.catalina.core.ApplicationContextFacade
	INFO ;2015-04-10 01:53:52,199;localhost-startStop-1;AbstractApplicationContext;Closing Root WebApplicationContext: startup date [Fri Apr 10 01:51:29 UTC 2015]; root of context hierarchy
	INFO ;2015-04-10 01:53:52,202;localhost-startStop-1;DefaultSingletonBeanRegistry;Destroying singletons in org.springframework.beans (...)
	INFO ;2015-04-10 01:53:52,211;localhost-startStop-1;PushManager;PelmelPush shutting down.
	DEBUG;2015-04-10 01:53:52,214;nioEventLoopGroup-2-1;ApnsConnection$4;PelmelPush-connection-0 sending known-bad notification to shut down.
	TRACE;2015-04-10 01:53:52,220;nioEventLoopGroup-2-1;ApnsConnection$4$1;PelmelPush-connection-0 successfully wrote known-bad notification 1
	DEBUG;2015-04-10 01:53:52,264;nioEventLoopGroup-2-1;ApnsConnection$ApnsConnectionHandler;APNs gateway rejected notification with sequence number 1 from PelmelPush-connection-0 (MISSING_TOKEN).
	TRACE;2015-04-10 01:53:52,267;nioEventLoopGroup-2-1;PushManager;Connection closed: ApnsConnection [name=PelmelPush-connection-0]
	

The strange thing is that with 0.4, I do not have the line "APNs gateway rejected notification with ... (MISSING_TOKEN)". But I do have some shutdown problem as tomcat never stopped and I was forced to kill it. I guess that error is "normal" as it says it was sending a "known-bad" notification, even though I did never receive the response in 0.4.

Now with 0.4.3 it does not start and I am in TRACE level and cannot really see any log about what is going wrong.

Is there anything that should be changed regarding configuration / setup when migrating from 0.4 to 0.4.3?

**Comment by jchambers** [comment]
We think we may be seeing similar behavior, but not reproducibly. What happens if you downgrade to Netty 4.0.24?

**Comment by jchambers** [comment]
Actually, we're thinking the problem may have actually crept in in Netty 4.0.26 at this point. Would be curious to hear if you have any luck downgrading to 4.0.25, too.

**Comment by christophefondacci** [comment]
Sorry, I actually removed pushy completely from my project as version 0.4 in a Tomcat environment was not sending all push notifications and was not logging any error while with version 0.4.3 I cannot start Tomcat at all.
I no longer have any webapp set up to make the test.

**Comment by jchambers** [comment]
Okay. In the absence of a reproducible test case, I think we have no choice but to close this until somebody else reports the same issue. Thanks for getting back to us!
