### ISSUE TITLE
ApnsPayloadBuilder generates simple alert text instead of alert dictionary

### ISSUE THREAD

**Issue by tscharlii** [relayrides/pushy#168]
The following codesnippet:

```java
final String payload = new ApnsPayloadBuilder()
        .setAlertBody("BODY")
        .setAlertTitle("TITLE")
        .buildWithDefaultMaximumLength();
```

results in this payload:

```json
{
  "aps": {
    "alert": "BODY"
  }
}
```

My expectation would be:

```json
{
  "aps": {
    "alert": {
      "body": "BODY",
      "title": "TITLE"
    }
  }
}
```

So, if I add any property (other than alert body) to the builder, and that property belongs into the alert dictionary, then the dictionary should actually be generated.

Possible fix: ApnsPayloadBuilder#shouldRepresentAlertAsString should additionally consider these properties:
alertTitle, localizedAlertKey and localizedAlertTitleKey

Best regards
Christian Charles

**Comment by sunng87** [comment]
This issue is also reported from our customers. I have created a patch for this: #170

**Comment by jchambers** [comment]
Thanks, @tscharlii, for the report, and thanks @sunng87 for the quick fix!
