### ISSUE TITLE
Request expired tokens

### ISSUE THREAD

**Issue by lpandzic** [relayrides/pushy#172]
It is not clear from the documentation and example in the README.md whether users should call this method periodically or just once after wiring?

**Comment by jchambers** [comment]
I'm not quite sure what you mean by "wiring." Could you please clarify?

The README says:

> Apple requires push notification providers to poll for expired tokens on a daily basis.

And [the `FeedbackServiceConnection` docs](http://relayrides.github.io/pushy/apidocs/0.4/com/relayrides/pushy/apns/FeedbackServiceConnection.html) directly quote [the relevant parts of the APNs guide from Apple](http://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW3).

Could you please be more specific about what you think is unclear, or which information you'd like to see added?

**Comment by lpandzic** [comment]
I meant after construction of PushManager instance. Sorry, I've misread the README.md, you are correct.

**Comment by jchambers** [comment]
No worries! Thanks for taking a second look.
