### ISSUE TITLE
CancellationException when calling the feedback service

### ISSUE THREAD

**Issue by cyChop** [relayrides/pushy#181]
Hi,

I have a problem when calling the feedback service. 

To sum up, the shutdown seems to be performed to quickly, cancelling some future tasks before they were performed. I did not fully understand the whole mechanism so here are some information that I hope can be useful.

### Reproducing

I don't think I made anything special to make this happen. A sample of calling of the PushManager is available below.

### Environment and versions

Pushy version: v0.4.3

This has been happening on my development machine (Windows 7, Eclipse environment) and on our test server (Unix).

### Logs

```
 INFO --- [           main] PushManager              : MyPushManager starting.
DEBUG --- [           main] ApnsConnection           : MyPushManager-connection-0 beginning connection process.
DEBUG --- [           main] ApnsConnection           : MyPushManager-connection-1 beginning connection process.
 INFO --- [           main] PushManager              : MyPushManager shutting down.
DEBUG --- [ntLoopGroup-4-1] ApnsConnection           : MyPushManager-connection-0 connected; waiting for TLS handshake.
DEBUG --- [ntLoopGroup-4-2] ApnsConnection           : MyPushManager-connection-1 connected; waiting for TLS handshake.
DEBUG --- [ntLoopGroup-4-1] FeedbackServiceConnection: MyPushManager-feedbackConnection-0 connected; waiting for TLS handshake.
DEBUG --- [ntLoopGroup-4-1] FeedbackServiceConnection: MyPushManager-feedbackConnection-0 failed to complete TLS handshake with APNs feedback service.
```

And then a `java.util.concurrence.CancellationException` appears in the log without any more information.

### My call to the `PushManager`

```java
try {
    pushManager = ... 
    pushManager.registerFailedConnectionListener(myFailedConnectionListener);
    pushManager.start();

    pushManager.registerExpiredTokenListener(collecter);
    pushManager.requestExpiredTokens();

} catch (Exception e) {
    throw new RuntimeException(e);
} finally {
    if (pushManager != null) {
        try {
            pushManager.shutdown();
        } catch (InterruptedException e) {
        }
    }
}
```

### Clues and ugly workaround

While debugging to understand the cause, I found that having a breakpoint at the beginning of `FeedbackServiceConnection.shutdownImmediately()` solved the problem. So I tried adding a sleep and this works:

```java
	/**
	 * Closes this feedback connection as soon as possible. Calling this method when the feedback connection is not
	 * connected has no effect.
	 */
	public synchronized void shutdownImmediately() {
		try {
			Thread.sleep(1000L);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		if (this.connectFuture != null) {
			synchronized (this.channelRegistrationMonitor) {
				if (this.connectFuture.channel().isRegistered()) {
					this.connectFuture.channel().eventLoop().execute(this.getImmediateShutdownRunnable());
				} else {
					this.closeOnRegistration = true;
				}
			}
		}
	}
```

This is however undescribably ugly.

**Comment by eager** [comment]
@cyChop does [this FAQ](https://github.com/relayrides/pushy/wiki/Frequently-asked-questions#i-started-a-push-manager-added-a-notification-to-the-queue-and-shut-down-the-push-manager-my-push-notification-never-got-sent-why-not) describe your scenario?

**Comment by cyChop** [comment]
Hi @eager.

I am not sure this matches my case, since I am not pushing in this case, only fetching the feedback information.

I may be doing something wrong, but based on my understanding of the documentation, I do not see what I missed.

**Comment by jchambers** [comment]
It's the same idea, I think: you're shutting down your push manager before we have time to finish talking to the feedback service. I don't think this is a bug, though I also don't think it's desirable behavior. That said, I see two ways forward here:

1. We can modify the `PushManager`'s `shutdown` method to wait for feedback connections to close. I don't really want to do do this for a variety of reasons, not the least of which is that the feedback service is getting removed when APNs moves from their wacky proprietary protocol to HTTP/2 "this summer" (see #184).
2. You can register listeners and wait for either (a) a list of expired tokens or (b) a failed connection to the feedback service. Either will tell you that the "poll for expired tokens" operation has finished and it's safe to shut down the push manager.

Hope that helps!

**Comment by cyChop** [comment]
@jchambers I suppose you are speaking of the `ExpiredTokenListener` and the `FailedConnectionListener`. It seems unnatural to me that such listeners should be the ones to perform the shutdown, but I can work with it. I will make the change ASAP (which is not right now).

If this is the way to go, maybe it could be highlighted on [pushy's homepage](http://relayrides.github.io/pushy/)?

Thank you for your advice.

**Comment by jchambers** [comment]
> It seems unnatural to me that such listeners should be the ones to perform the shutdown…

It is, indeed, a bit weird. Our "expected" use case for Pushy is that people will create a long-lived `PushManager` and queries for expired tokens will rarely happen around shutdown time, and starting a push manager for the sole purpose of gathering expired tokens isn't really a case we had considered (or really believe to be common, even now).

You are right that we could add to the docs, but I think that might raise more questions than it answers; I think I'm still going to take the lazy road and just wait for the feedback service to go away entirely.

**Comment by cyChop** [comment]
OK, your position is perfectly fine and based on a specific use case. But if I may, I do not find this use case obvious when having a look at the documentation, only after some use.

Maybe you could highlight it a bit so that future users could determine if Pushy is a fit for their need or if they should look at an alternative which would be more adapted.

(For example, our current use case is to generate and push notifications in a batch. The `PushManager`s (several applications) are created, notifications pushed and the managers are shut down. The same way, the manager is started, we get the feedback and it is shut down. We hope to move later to a continuous-flow solution, but in the meanwhile, we do not match your target use case.)
