### ISSUE TITLE
Frantic connection attempts upon some connection failure scenarios

### ISSUE THREAD

**Issue by jocelynlepage** [relayrides/pushy#185]
Hi,

The reconnection logic potentially create frantic connection attempts if there's a connection attempt that fails immediately. We do believe that some throttling should be applied in those circumstances, to avoid what looks like "uncontrolled" behavior.

Scenarios under which I was able to reproduce this problem:
- Specification of an invalid APNS gateway host/port (e.g. an address/port on which nothing is listening)
- By constructing a PushManager with an SSLContext that doesn't "trust" the APNS gateway

The "culprit" seems to be com.relayrides.pushy.apns.PushManager.handleConnectionFailure(ApnsConnection<T>, Throwable) and com.relayrides.pushy.apns.PushManager.handleConnectionFailure(FeedbackServiceConnection, Throwable), where it tries to reconnect right away. 

We do suggest that there's a configurable minimum delay between reconnection attempts (perhaps following a exponential backoff delay strategy as found in many network protocols) such as if the connection setup failed very quickly there's some time before a reconnection attempt is made, but if the failure took some time to be detected (such as connect timeout reached), then this time is deduced from the configured delay. 

Note that most of the times, we do observe that network connection setup failure can take ~1 second before Netty reports the error, thus experimenting reconnection attempts at a saner pace.

(note that we are testing this by having mocked the APNS gateway - basically the same thing you guys did in com.relayrides.pushy.apns.MockApnsServer test code).

**Comment by jchambers** [comment]
This should be covered by #169. There's an intermittently-failing test that I haven't been able to focus on quite yet, but as soon as that's resolved, I think we can ship a fix here. I absolutely agree that this is a real issue, but I'm going to close it as a duplicate since I think we've got it covered elsewhere.

Thanks for the thoughtful report!

**Comment by jocelynlepage** [comment]
Thanks - after a quick glimpse on the referenced branch, it seems that the ApnsConnectionGroup.reconnectDelay would take care of the aforementioned problem.

BR,
