### ISSUE TITLE
Fixed-position footer on project homepage overlaps sidebar on short windows

### ISSUE THREAD

**Issue by eager** [relayrides/pushy#186]
<img width="730" alt="napkin 2 07-09-15 7 26 47 pm" src="https://cloud.githubusercontent.com/assets/4656/8611079/710a6fa6-2670-11e5-9c56-5760cf518b2a.png">

**Comment by jchambers** [comment]
Fixed in 62279b1a6ed904c1dec6946f25a783f9c708afd3. Whew.
