### ISSUE TITLE
PushManager.isShutDown() is not thread-safe

### ISSUE THREAD

**Issue by jmason** [relayrides/pushy#189]
hey folks --

PushManager.isShutDown() ( https://github.com/relayrides/pushy/blob/master/src/main/java/com/relayrides/pushy/apns/PushManager.java#L318-L327 ) has a thread-safety issue -- this.shutDownStarted is a boolean member of the PushManager object and is accessed without any lock.  There's therefore a risk that a caller in a different thread from the one calling shutdown() will see an incorrect value.

It should be easy enough to make shutDownStarted and shutDownFinished volatile, to avoid this risk.

I think similar thread-safety issues arise with dispatchThread (which is accessed by the public isStarted() API which is in turn called by requestExpiredTokens()), and dispatchThreadShouldContinue (which may be accessed by the dispatch thread while shutdown() is in progress).

**Comment by jchambers** [comment]
Yikes; totally missed this one when it opened. Sorry, @jmason!

Yep; that all sounds sensible to me. Man am I looking forward to HTTP/2 support so we don't have to do all this stuff.

**Comment by jmason** [comment]
great! lemme know if you want me to fire in a quick pull request.

**Comment by jchambers** [comment]
This should be a non-issue now that we've moved to the HTTP/2-based APNs protocol (see #213). Closing for now; please leave a comment if this resurfaces later!
