### ISSUE TITLE
One thread to send notification

### ISSUE THREAD

**Issue by cungchoi** [relayrides/pushy#192]
Hi,
First, thanks so much about this lib, it's so amazing.

When I use, I see that just 1 thread was created in start function (createDispatchThread()) and take message from queue (connection.sendNotification(queue.take());).
When we send a large of devices, any problem happen with just 1 thread? Please share any ideas for this. Thanks so much!

**Comment by jchambers** [comment]
There's a single thread that takes notifications from the queue and hands them off to an arbitrary number of worker threads. To make use of multiple worker threads, have your `PushManager` open [multiple concurrent connections](http://relayrides.github.io/pushy/apidocs/0.4/com/relayrides/pushy/apns/PushManagerConfiguration.html#setConcurrentConnectionCount(int)) to the APNs gateway, and make sure you pass an `EventLoopGroup` configured to use multiple threads to your `PushManager` at construction time.

Hope that helps!

**Comment by cungchoi** [comment]
Thanks, I got your idea.
