### ISSUE TITLE
Throttle reconnect tries on connection failure?

### ISSUE THREAD

**Issue by skerkewitz** [relayrides/pushy#193]
Hi,

we had a some trouble on our production system a few days ago. The problem did last for about 3 minutes - but created 50k log lines that a connection could not be created (a single log line in our FailedConnectionListener#handleFailedConnection() implementation) .

Is there a easy way to throttle down the connection retries?

As far as I can see I have only the option to specify if I want retries or not. I would like to say pushy to wait 10sec after a connection failure before the next try.

Thanks in advance,
Stefan

**Comment by jchambers** [comment]
Yes—exponential back-off is included in #169. I regret that we haven't shipped it yet, but I'm still hoping to do so soon.

**Comment by skerkewitz** [comment]
Alright, thanks for the quick feedback.

**Comment by jchambers** [comment]
Cheers!

**Comment by skerkewitz** [comment]
Any news on 0.5? We created 10GB logs in 40min because a host was unreachable... :-/

**Comment by jchambers** [comment]
Our attention right now is on getting HTTP/2 support in place, but that should also resolve this issue incidentally. Probably the best thing to do to help is to take a look at #213 and let us know if you have any feedback.

I'm hoping that we'll be able to ship HTTP/2 support early next week.

**Comment by skerkewitz** [comment]
I had a feeling you would say something like that. :-)

I didn't knew Apple's HTTP/2 service is already up and running. Just noticed it after I wrote my comment. I'm looking forward to give the HTTP/2 implementation a shot as soon as it is ready.

Again, thanks for the quick reply.
