### ISSUE TITLE
Add support to determine/enforce delivery priority based on actual payload

### ISSUE THREAD

**Issue by tscharlii** [relayrides/pushy#199]
> "It is an error to use this priority (Author's Remark: IMMEDIATE) for a push that contains only the content-available key."
 
see https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html

At the moment the delivery priority is set manually or defaults to IMMEDIATE (see SimpleApnsPushNotification constructors). This may conflict with the actual payload.

I'd like to see some support to determine, whether the delivery priority CONSERVE_POWER is required or IMMEDIATE is allowed.

Maybe ApnsPayloadBuilder can track this and provide a method getDeliveryPriorityRestriction returning an enum DeliveryPriorityRestriction (either CONSERVE_POWER_REQUIRED or IMMEDIATE_ALLOWED)

Or maybe you can shed some light on the implications of the above requirement.
It is not completely clear to me, what the mentioned apple documentation means exactly. Some examples:

A silent push, must use CONSERVE_POWER
```{
  "aps": {
    "content-available": 1
  }
}```

A standard push + content-available to show a message and trigger  application:didReceiveRemoteNotification:fetchCompletionHandler in the app (does this make sense at all?): Both priorites allowed
```{
  "aps": {
    "alert": "Some message",
    "content-available": 1
  }
}```

What about this? Seems to be a silent push (no alert, no badge, no sound), yet content-available is not the only key in aps. Which priorities are allowed here?
```{
  "aps": {
    "category": "SomeCategory",
    "content-available": 1
  }
}```

And finally: Silent Push along with custom properties: must use CONSERVE_POWER
```{
  "aps": {
    "content-available": 1
  },
  "someCustomProperty": "someCustomPropertyValue"
}```

Please comment, if my assumptions are wrong.

Best regards
Christian Charles

**Comment by jchambers** [comment]
> maybe you can shed some light on the implications of the above requirement.

I ran some experiments, and having a content/priority mismatch doesn't seem to cause any protocol-level problems. One consequence of making a change like this would be that we'd have to parse every single message we wanted to send, and I'm worried about the performance implications there. Given that we don't check payloads for other content-level errors, that there's no protocol-level implication for getting this wrong, and the potential performance hit, I'm inclined to leave this kind of checking to users.

Sound good?

**Comment by jchambers** [comment]
Closing for now. @tscharlii please leave a comment if you'd like us to reconsider.
