### ISSUE TITLE
How to check client had received notification from server

### ISSUE THREAD

**Issue by docaohuynh** [relayrides/pushy#210]
Dear all!

How I check when Iphone is connected internet and received notification. And when server push notification but Iphone have not internet

Best regards
Docaohuynh

**Comment by jchambers** [comment]
Sadly, this is not a use case supported by APNs as a protocol. There's nothing Pushy can do to get at this kind of information.

**Comment by docaohuynh** [comment]
Thanks @jchambers  for your reply.
