### ISSUE TITLE
pushy 0.4.3  may send a message twice

### ISSUE THREAD

**Issue by aluenkinglee** [relayrides/pushy#214]
We are using pushy 0.4.3.

We met a strange problem : send ONE message to the pushManager but one app receive TWO SAME message.

1. If Notification A has a invalid token, Notification B is normal  after Notification A. Notification A of cause will be rejected by INVALID TOKEN. Is it possible  that the INVALID TOKEN  causes repeat message sending?

2. If so,  how to locate this problem caused by INVALID TOKEN?

thanks !

**Comment by jchambers** [comment]
@aluenkinglee I'm not sure; I don't think we've heard of this one before. I hate to put all the burden on you, but can you see if you can come up with a minimal test case (i.e. a small app that actually sends Notification A and Notification B as described above)?

Thanks!

**Comment by jchambers** [comment]
We've just merged HTTP/2 support into `master` (see #213). I strongly suspect the move to HTTP/2 will resolve this problem. I'm going to close this for now; please comment here if you see this happen again after updating Pushy.
