### ISSUE TITLE
can not find pushy 0.5 on maven

### ISSUE THREAD

**Issue by dxp558** [relayrides/pushy#221]
I can not find pushy 0.5 on maven. 
repository url :
http://repo2.maven.org/maven2/com/relayrides/pushy/0.5/
I found this directory is empty.
url:http://search.maven.org/ the same too.

**Comment by dqsdhr** [comment]
I can not find either.

**Comment by efendizadeh** [comment]
+1

**Comment by jchambers** [comment]
I'll look into it. It appears to be released from the wacky admin panel thing, but I agree that it's not showing up in search.

**Comment by jchambers** [comment]
I've requested support on this issue at https://issues.sonatype.org/browse/MVNCENTRAL-942.

**Comment by jchambers** [comment]
Sounds like this was an upstream issue, and Pushy 0.5 should be visible in Maven Central within the hour.

**Comment by jchambers** [comment]
That took longer than expected, but Pushy 0.5 is now visible in Maven Central.

**Comment by tckb** [comment]
still have issue with 0.5 version. 

Got the following error. 
```
[WARNING] The POM for com.relayrides:pushy:jar:0.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by jchambers** [comment]
@tckb Works fine for me. Could you enable debug logging and post any additional details here?

**Comment by tckb** [comment]
@jchambers  it works now. there was an issue with earlier version. I purged and  reran. it worked! 
But now there is another issue.:

On my local machine running (OSX/64 bit) it ran flawlessly. But, it failed to run on the server running Ubuntu. This is the root cause exception:
```
ALPN unsupported. Is your classpatch configured correctly?
```
NB: Yes, I'm using the correct platform dependent version ('linux-x86_64')


I am using the Netty tcnative vesion as suggested in the system-requirements. 




Any thoughts?

**Comment by jchambers** [comment]
> `ALPN unsupported. Is your classpatch configured correctly?`

I'm happy to help with this, but the [mailing list](https://groups.google.com/d/forum/pushy-apns) might be a better venue (I'm concerned that other people who run into the same thing might not notice the discussion happening here in a closed ticket about Maven Central).

Still, to take a first shot: are you certain that you're running an appropriate version of OpenSSL on your server? ALPN wasn't introduced into OpenSSL [until 1.0.2](https://www.openssl.org/news/openssl-1.0.2-notes.html). You can run `openssl version` to see what's running on your server.

If that doesn't work out, please do post to the mailing list!

**Comment by tckb** [comment]
@jchambers  fair point. 

thanks for pointing to the list. I'll open a new topic there and I'll copy the same.
```
ALPN wasn't introduced into OpenSSL until 1.0.2.
```
thats good point. Let me check.
