### ISSUE TITLE
Keep receiving error with ALPN

### ISSUE THREAD

**Issue by papped** [relayrides/pushy#229]
I'm trying to run pushy with alpn-boot. However, every time I try to run my code, I get the error:

`Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider: org.eclipse.jetty.alpn.ALPN$Provider`

I've added the following to the pom.xml file:

```
<profiles>
<profile>
            <id>alpn-8latest</id>
            <activation>
                <jdk>[1.8,)</jdk>
            </activation>
            <properties>
                <jetty.alpn.version>8.1.6.v20151105</jetty.alpn.version>
            </properties>
        </profile>
</profiles>
...
<build>
       <plugins>
                <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>get-alpn-boot</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>get</goal>
                        </goals>
                        <configuration>
                            <groupId>org.mortbay.jetty.alpn</groupId>
                            <artifactId>alpn-boot</artifactId>
                            <version>${jetty.alpn.version}</version>
                        </configuration>
                    </execution>
                </executions>
      </plugin>
   </plugins>
</build>
...
<dependencies>
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http</artifactId>
            <version>4.1.0.CR1</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.5</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.osgi</groupId>
            <artifactId>jetty-osgi-alpn</artifactId>
            <version>9.3.7.v20160115</version>
        </dependency>
</dependencies>

...
<properties>
<java.version>1.8</java.version>
        <jetty.alpn.path>${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${jetty.alpn.version}/alpn-boot-${jetty.alpn.version}.jar</jetty.alpn.path>
        <argLine.bootcp>-Xbootclasspath/p:${jetty.alpn.path}</argLine.bootcp>
</properties>
```

What could be going wrong here? Is there anything else I need to add?

Many thanks.

**Comment by jchambers** [comment]
It looks like you need to add `alpn-api` to your classpath. I would have thought that would Just Happen™ if `alpn-boot` is on your classpath, though. Would you mind trying to add it as an explicit `runtime` dependency? If that resolves the issue, we may need to update Pushy's pom.xml.

Thanks!

**Comment by papped** [comment]
Adding at as a runtime dependency gets rid off that error, but now it comes back with the error:

`java.lang.RuntimeException: ALPN unsupported. Is your classpatch configured correctly? See http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting`

I'm guessing this is to do with the OpenJDK version I'm using? I'm deploying my application on to Pivotal Web Services, and it seems to download Open Jdk JRE 1.8.0_71. This build isn't listed on the alpn website.. (closest is _72). How would that work?

**Comment by papped** [comment]
Running locally I get a `javax.net.ssl.SSLException: java.io.FileNotFoundException: XXX (No such file or directory)` on the line `apnsClient = new ApnsClient<>(file, "password");`. The file is definitely there and has been correctly created as a `File`.

**Comment by jchambers** [comment]
Okay. It's sounding like this is more of a configuration issue than a bug. It sounds like there are two issues:

1. `alpn-boot` is not actually on your boot classpath. I think the `alpn-api` thing was bit of a red herring; it was missing because `alpn-boot`, which provides `alpn-api`, was also missing.
2. There's some separate issue with finding your p12 file, but that seems completely unrelated to me.

Also, to answer your question:

> Also do you have a working pom.xml file for a project that uses pushy that I could take a look at to see if everything I'm doing is correct?

Pushy's own pom.xml is used to run unit tests that (unsurprisingly) actually use Pushy. I'd say that's a good starting point.

I'd be happy to help you out further, but since this is more of a request for support than a bug report or feature request, would you mind moving this conversation to the [mailing list](https://groups.google.com/forum/#!forum/pushy-apns)? I'll close this issue in the meantime.

Thanks!
