### ISSUE TITLE
Update to Netty 4.1.0.CR1

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#231]
Netty 4.1.0.CR1 came out last week; we should update to pick up the latest bug fixes (of which there are many). Looks like there are some breaking API changes to contend with, but nothing catastrophic.

**Comment by jchambers** [comment]
I started in on this in (see https://github.com/relayrides/pushy/tree/netty_4_1_cr1), but I think we're blocked by https://github.com/netty/netty/issues/4802.

**Comment by flozano** [comment]
https://github.com/netty/netty/releases doesn't show it yet, but .CR2 is already available...

**Comment by jchambers** [comment]
@flozano Yes! That's actually what we used in 4408224. Thanks!

**Comment by flozano** [comment]
uh, sorry :dancers: you were faster hehe
