### ISSUE TITLE
Can someone detailly explain the process to install alpn windows server?

### ISSUE THREAD

**Issue by PeterL1n** [relayrides/pushy#234]
I tried netty-alpn, but did not find out how to add it to boot path.

And for the openssl solution. I am on a windows pc, how do I install openssl on windows?

**Comment by jchambers** [comment]
Hi there! This is more of a request for general support than it is a feature request or bug report. Would you mind moving the conversation to the [mailing list](https://groups.google.com/d/forum/pushy-apns) instead of an issue on github? I'll close this issue in the meantime.

Thanks!
