### ISSUE TITLE
constructor ApnsClient(InputStream p12Content, @Nullable String password)

### ISSUE THREAD

**Issue by stIncMale** [relayrides/pushy#238]
It would be nice to have a constructor ApnsClient(InputStream p12Content, @Nullable String p12Password) in addition to ApnsClient(File p12File, String password) (which already exists) when cert is stored not in the local file system (e.g. in a database). Because currently I see no API (http://relayrides.github.io/pushy/apidocs/0.5/index.html) which allows to quickly use any of existing ApnsClient constructors when we have only p12 bytes.

**Comment by jchambers** [comment]
Oops. Looks like I forgot to update the docs. It turns out that this is a duplicate of #235, and we actually shipped it yesterday as part of Pushy 0.5.2. The docs have now been updated.

Cheers!
