### ISSUE TITLE
Consider switching to statically linked tcnative + boringssl

### ISSUE THREAD

**Issue by louiscryan** [relayrides/pushy#240]
FYI
Netty-tcnative has now released an artifact that statically links in BoringSSL. This removes the need to have folks update openssl on their boxes which can be a considerable pain.

There are also plans to release an uber-jar so you don'y have to use os classification at build time
https://github.com/netty/netty-tcnative/pull/113
Should be done soon

Should make this a lot easier
http://relayrides.github.io/pushy/#system-requirements

**Comment by jchambers** [comment]
> There are also plans to release an uber-jar so you don't have to use os classification at build time

Yeah—that sounds great. I'll keep an eye on netty/netty-tcnative#113 and act as soon as that settles out.

**Comment by jchambers** [comment]
@louiscryan Forgive the lazy question, but do you know if netty-tcnative works on non-linux flavors of unix? If it works everywhere within reason (and if the uber-jar thing goes through), I'm wondering if we should drop all of the `alpn-boot` stuff entirely and always rely on statically-linked BoringSSL.

**Comment by jchambers** [comment]
netty/netty-tcnative#113 has been merged. I guess we just need to wait for the next release now, huh?

**Comment by louiscryan** [comment]
Which non-linux flavors of unix do you care about besides osx? 

More can be added but I think folks would be asked to contribute functional builds for those that can be done without requiring the netty team to own a fleet of boxes. i.e cross-compiles or some free virtualization solution

**Comment by jchambers** [comment]
> Which non-linux flavors of unix do you care about besides osx?

I don't think we're concerned about anything specific; just wanted to make sure I understood the system requirements for netty-tcnative so I could document it clearly in our own README. I'm keeping an eye on https://github.com/netty/netty-tcnative/issues/112 for that now, though, and I'll hope that gets resolved for the next release.

**Comment by jchambers** [comment]
Netty 4.1 CR4 is out, so I expect to have this done shortly.

**Comment by jchambers** [comment]
…and now netty-tcnative fork 15 is out, too! Game on.

**Comment by jchambers** [comment]
I'm afraid I've hit a bump in the road here. See https://github.com/netty/netty/issues/5052 for discussion.

**Comment by jchambers** [comment]
Huh—so evidently, the uber-jar won't be out until fork 16. I think I'm going to pull this out of the 0.6 milestone, since this will baaaaasically be a documentation update later.

**Comment by twiedow** [comment]
Do you have any information when a working uber-jar will be out? I need a simple setup for my project where I deploy on Windows and Mac OS X. Since I don't want to have platform dependent setups I would go with a version 0.4.x. Or do you have a suggestion?

**Comment by jchambers** [comment]
I emphasize that `netty-tcnative` is its own project, and I'm not a contributor there. That said, the best information I have is https://github.com/netty/netty-tcnative/issues/133, which suggests "soon."

You can still do a mostly-platform-agnostic statically-linked SSL provider without an uber-jar, though. See http://netty.io/wiki/forked-tomcat-native.html#how-to-download-netty-tcnative-boringssl-static for instructions. You'll just need to add `os-maven-plugin` to figure out which platform-specific jar to grab.

**Comment by jchambers** [comment]
Added a recommendation to use a statically-linked version of `netty-tcnative` in aacdf77. Will add further updates whenever fork16 (the uber-jar version) comes out.

Also added profiles to use statically-linked `netty-tcnative` in tests in 8dc0e5e as part of #232.
