### ISSUE TITLE
support for gateway

### ISSUE THREAD

**Issue by attasiva** [relayrides/pushy#241]
in our environment, we have to connect to APNS only through a proxy. currently we are using stunnel for that.. but with HTTP2, i am not sure if this works.
i am getting 'version mismatch' error when tried with your MockApnsServer.. this could be because of ALPN?

is there a way in which I can send APNS requests in non-secure format till my proxy and in a secure way from proxy to APNS.

should I switch to some other proxy like haproxy?

**Comment by jchambers** [comment]
I'm sorry—I'm not sure if I understand the situation here. Which version of Pushy are you using? Will the changes from #215 do what you need?

**Comment by jchambers** [comment]
…alternatively, can you please post the full stack trace associated with the "version mismatch?"

> is there a way in which I can send APNS requests in non-secure format till my proxy and in a secure way from proxy to APNS.

Not within reason, no.

**Comment by jchambers** [comment]
I'm going to close this due to lack of information. @attasiva please feel free to leave a comment if you think this is still an issue and can provide more information.
