### ISSUE TITLE
Considered WriteTimeoutHandler?

### ISSUE THREAD

**Issue by flozano** [relayrides/pushy#244]
Context:
As of few days ago, we're seeing, **in our legacy netty-based apns client** (*not pushy*), some strange legacy (tcp/ssl based) APNS behaviour in which the netty write's Futures are never completed, either failed or succeeded (netty 4.0.33).

We have no idea of the source of this behaviour, but we're thinking on mitigating it by adding WriteTimeoutHandler [1] to the pipeline, so that any write that doesn't "succeed" in a few seconds is considered failed and the connection gets closed (and therefore the writable futures completed with an error).

**now**, we're *finally* fully migrating away from our own client to pushy http2 implementation (TG), and we're thinking if it would be good to have this same WriteTimeoutHandler [1] in the http2 request pipeline. 

Thoughts? 

[1] http://netty.io/4.1/api/io/netty/handler/timeout/WriteTimeoutHandler.html

**Comment by jchambers** [comment]
Seems like a very good idea to me, and really kind of an oversight that it's not already there. One thing isn't immediately (I emphasize "immediately"—I've spent maybe 30 seconds looking) clear to me from the docs, though: is there a way to correlate a write timeout with the specific operation that failed?

**Comment by flozano** [comment]
From what I've seen, it creates a timeout task for each write, and cancels it if still not finished after timeout... but the end result is closing the connection, so in theory I don't think it's possible to correlate, as - if I understood it correctly - all futures waiting to write on that connection will immediately fail...

**Comment by jchambers** [comment]
Done in a6af16d. Thanks for the suggestion!

**Comment by flozano** [comment]
Thanks for taking care of it!
