### ISSUE TITLE
Netty shutdown and memory leak issue

### ISSUE THREAD

**Issue by dorheini** [relayrides/pushy#245]
Hi.
I've started checking pushy 0.5 which uses the new APNs API (HTTP/2).
One of my main concerns is the netty shutdown and memory leak mentioned in #73 as i'm using a servlet container (tomcat 7).
Is this issue solved? is there a workaround for this issue?
 
i just saw that in commit `845272b`, 'Limitation and known issues' section which included the above issue was removed from README.md.
Thanks in advance,

Edit:
I embedded pushy v0.5.2 in a simple web application which runs on tomcat and when shutting down tomcat i get in the log:

```
SEVERE: The web application [/PushyDemo] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@78d183e5]) and a value of type [io.netty.util.internal.InternalThreadLocalMap] (value [io.netty.util.internal.InternalThreadLocalMap@32a6d5b]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

**Comment by jchambers** [comment]
It's still an issue. It looks like I just got a little aggressive in removing the old warnings from the README.

**Comment by jchambers** [comment]
@dorheini Restores the warning in the README in 208e8b4.

**Comment by exedmg** [comment]
Hi @jchambers Do this issue also affect spring-boot application (using embedded server)?  If I may ask, do you know any fully working example of using pushy using spring-boot and also using netty's Future listener? Thanks

**Comment by jchambers** [comment]
> Do this issue also affect spring-boot application (using embedded server)?

Probably, but I don't know anything about Spring Boot.

> do you know any fully working example of using pushy using spring-boot and also using netty's Future listener?

For general support questions, please post to [the mailing list](https://groups.google.com/d/forum/pushy-apns).
