### ISSUE TITLE
Thread Pool for Async calls

### ISSUE THREAD

**Issue by shahbour** [relayrides/pushy#260]
Hello 

I am wondering if their is any configuration for limit how many simultaneous request we can do or we should handle this at our code .

the idea is if we are sending lot of notification , are they going to be queued or break the system

Thanks

**Comment by shahbour** [comment]
Per document i think this can be specified using  EventLoopGroup , i will give it a try

**Comment by jchambers** [comment]
I think this question is more at home on the mailing list. Since you've already [mirrored this thread](https://groups.google.com/d/msg/pushy-apns/yDA7RQP2NmU/uoQir1mnBwAJ) there (thanks!), I'm going to close this issue and continue the discussion on the mailing list.
