### ISSUE TITLE
interrupted persistent connection

### ISSUE THREAD

**Issue by pedobry** [relayrides/pushy#264]
I use pushy 0.6 which establish persistent connection. However, my firewall drops idle TCP connection after 40 minutes and unfortunately the bad way (no RST, just silent drop). When I try to send notification to that connection, I get "Connection time out" exception, but only after 15 minutes (that's default Linux OS timeout to retransmit the packet). And that's not very convenient.

I'l change Linux settings /proc/sys/net/ipv4/tcp_retries2 and /proc/sys/net/ipv4/tcp_retries1 to some smaller values, but it would be really helpful if pushy can enable ChannelOption SO_KEEPALIVE on the socket.

**Comment by jchambers** [comment]
I think we have this covered in #266.
