### ISSUE TITLE
About support period of version 0.4.3

### ISSUE THREAD

**Issue by VincentWyin** [relayrides/pushy#273]
I am currently using version 0.4.3, it's works pretty well so far. Thanks for your hard work and sharing.

But now the latest version is 0.6.1, the API changes too. Should I update pushy from 0.4.3 to 0.6.1? Or can I still use the version 0.4.3 until further notice? Thanks.

**Comment by jchambers** [comment]
I strongly recommend updating to the latest version. Support issues aside, it's using the vastly-improved, HTTP/2-based APNs protocol; that means connections are much more stable, and we actually know what happens to your push notifications after we send them.

We're not planning on supporting the 0.4 series, which is probably another good reason to upgrade. That said, short of an upstream change, there shouldn't be anything that would cause the 0.4 series to spontaneously stop working.
