### ISSUE TITLE
Netty submodules for 0.4.3

### ISSUE THREAD

**Issue by nickj21** [relayrides/pushy#274]
I am not quite ready to bite the bullet in the large API change to 0.5+, however the All-in-one Netty dependency of 0.4.3 is causing classpath woes. Any idea of the complexity of getting a version of 0.4.3 to use Netty submodules instead of the All-in-one?

**Comment by jchambers** [comment]
To clarify, are you asking for advice, or are you asking for a new release of the 0.4 series? ;)

The latter is, I'm afraid, off the table. We recognize that the API change and increased system requirements are a barrier for some users, but are generally not planning on any updates to the 0.4 series.

As for the former: shouldn't be bad. I think you'd just need… `-codec` and `-transport`? You should only need to make a couple changes to the dependencies in the POM, and shouldn't need to make any code changes.

Does that help?

While we're on the topic, please let me strongly encourage you to bite the bullet and upgrade! Using the HTTP/2-based APNs protocol is sooooooo much better than the Express Train to Wackytown that was the "binary" protocol. Connections are more stable, there aren't mystery voodoo memory exhaustion issues, and we actually know what happened to your push notifications after you sent them. It's totally worth it.

Also, good to hear from you again!

**Comment by nickj21** [comment]
Thanks Jon, the dependency switch was as easy as you thought it would be. Work is being started for the new API and definitely excited for the improvements!

**Comment by jchambers** [comment]
:metal:
