### ISSUE TITLE
NPE with null password

### ISSUE THREAD

**Issue by stromnet** [relayrides/pushy#280]
```
java.lang.NullPointerException
	at com.relayrides.pushy.apns.P12Util.getPrivateKeyEntryFromP12InputStream(P12Util.java:23)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:340)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:331)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:234)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:209)
```

https://github.com/relayrides/pushy/blob/master/src/main/java/com/relayrides/pushy/apns/P12Util.java#L23 expects a password, but line 18 checks for null.

**Comment by jchambers** [comment]
Before I go too crazy trying to untangle this, are you confident that you have a P12 file that actually has a `null` password? I can produce a P12 file that has a *blank* password, but not a *null* password (i.e. the password is `""`, not `null`). If you do have a null-password P12 file, how did you produce it?

**Comment by stromnet** [comment]
I'm afraid the P12 file I have doesn't work at all, not sure why yet... With empty string I get 
```
javax.net.ssl.SSLException: java.io.IOException: Integrity check failed: java.lang.SecurityException: Failed PKCS12 integrity checking
...
Caused by: java.lang.SecurityException: Failed PKCS12 integrity checking
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2054)
```

Keytool output:
```
$ keytool -list -keystore xxx.p12 -storetype PKCS12 -v              
Enter keystore password:  

*****************  WARNING WARNING WARNING  *****************
* The integrity of the information stored in your keystore  *
* has NOT been verified!  In order to verify its integrity, *
* you must provide your keystore password.                  *
*****************  WARNING WARNING WARNING  *****************
Keystore type: PKCS12
Keystore provider: SunJSSE

Your keystore contains 1 entry

Alias name: xxx apn sandbox
Creation date: Apr 26, 2016
Entry type: PrivateKeyEntry

*******************************************
*******************************************
```

Not sure the p12 file is propery, so I'm not blaming this on pushy.. :)

However, what *can* be fixed is this:
The code on line 12 actually seems to expect that password *can* be null, where as line 23 expects it to be non-null, that made it a bit confusion as to what is actually expected. The docs in ApnsClient doesn't indicate if password must be non-null.

**Comment by jchambers** [comment]
> `Enter keystore password:`

Interesting. Sounds like this may be a case of "blank, but non-null password."

> The docs in ApnsClient doesn't indicate if password must be non-null.

Right; that definitely needs some help. My growing suspicion is that it may be possible *in theory* to have a null-password P12 file, but *in practice*, there are no tools that actually produce such a thing. Does anybody out there know otherwise?

**Comment by stromnet** [comment]
To clarify, at keytools "Enter keystore password:" prompt I just press enter.

**Comment by jchambers** [comment]
> at keytools "Enter keystore password:" prompt I just press enter.

Yep—that was my understanding.

**Comment by stromnet** [comment]
Here's openssl's output of the same file:
```
$ openssl pkcs12 -info -in xxx.p12 -nodes
Enter Import Password: [pressing enter]
MAC Iteration 1
MAC verified OK
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
Bag Attributes
    friendlyName: PMA APN Sandbox
    localKeyID: XX XX XX XX XX XX XX XX XX ... XX 
Key Attributes: <No Attributes>
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
```

**Comment by stromnet** [comment]
I tried importing the one I got into Keychain, then re-exporting it with a password. Now I got by those issues, but instead failed on 
```
java.lang.NullPointerException: invalid null input

    at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:524)
    at sun.security.pkcs12.PKCS12KeyStore.engineGetEntry(PKCS12KeyStore.java:1287)
    at java.security.KeyStore.getEntry(KeyStore.java:1521)
```
There is something funky with this p12 regardless, will re-export it. 

For the record, this works fine:
```
$ openssl genrsa -out testkey.key 2048
$ openssl req -nodes -sha256 -new -key testkey.key -out testkey.csr
$ openssl x509 -req -days 365 -in testkey.csr -signkey testkey.key -out testkey.crt
...
$ cat testkey.crt > testkey.crtkey
$ cat testkey.key >> testkey.crtkey
$ openssl pkcs12 -export -nodes -in testkey.crtkey -out testkey.p12 -name "self-signed test"
Enter Export Password: [enter]
Verifying - Enter Export Password: [enter]
```

The above loads fine with "" i.e. empty string.
The keytool output shows:
```
$ keytool -list -keystore testkey.p12 -storetype PKCS12 -v                                                
Enter keystore password:  

*****************  WARNING WARNING WARNING  *****************
* The integrity of the information stored in your keystore  *
* has NOT been verified!  In order to verify its integrity, *
* you must provide your keystore password.                  *
*****************  WARNING WARNING WARNING  *****************

Keystore type: PKCS12
Keystore provider: SunJSSE

Your keystore contains 1 entry

Alias name: self-signed test
Creation date: Apr 26, 2016
Entry type: PrivateKeyEntry


*******************************************
*******************************************
```
i.e. identical to the keytool output for the broken cert.
The `openssl pkcs12 -info` output however shows more:

```
$ openssl pkcs12 -info -in testkey.p12 -nodes
Enter Import Password:
MAC Iteration 2048
MAC verified OK
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Certificate bag
Bag Attributes
    localKeyID: F6 23 8F EA FC C9 04 F4 F8 94 D7 FF A7 9B 6F E9 F7 9E 34 27 
    friendlyName: self-signed test
subject=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
issuer=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
Bag Attributes
    localKeyID: F6 23 8F EA FC C9 04 F4 F8 94 D7 FF A7 9B 6F E9 F7 9E 34 27 
    friendlyName: self-signed test
Key Attributes: <No Attributes>
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
$ 
```

So, it seems that the KeyStore fails if it only finds a key, but no cert... or something :)


I've asked the customer to re-generate it with respect to the caveats notes (https://github.com/relayrides/pushy/wiki/Certificates), let's hope that works better.

**Comment by stromnet** [comment]
Got a new cert, exported according to the guidelines linked above. Now it works fine!
Lots of noise for a user misstake, but at least someone else may benefit from the google hits.. :)

I'll leave the issue open though, due to the ambiguity in P12Util, and leave it to you to decide wether it's worth fixing it or not.
Thanks for prompt response anyway!

**Comment by jchambers** [comment]
So I'm going to put my money on "can't actually create a P12 with a `null` password." I updated the docs, tests, and internal checks to reflect that gamble in 56f7ccb.

**Comment by jchambers** [comment]
…and thanks, of course, for the report!
