### ISSUE TITLE
Keep alive 

### ISSUE THREAD

**Issue by shahbour** [relayrides/pushy#286]
Hello

I am using the library and it is working good except that due to testing phase we don't have lot of pushes some times for more than 6 hours , when this happen always the first push after this we got error 
```
2016-05-03 12:51:24.390  WARN 7084 --- [ntLoopGroup-3-1] c.r.pushy.apns.ApnsClientHandler         : APNs client pipeline caught an exception.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_51]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_51]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_51]
```

Then it reconnect and work , is their any way to check if the connection is up before submitting any message or if their is some thing to keep the connection alive on low pushes requests

**Comment by jchambers** [comment]
We introduced automatic sending of `PING` frames in v0.6.1. Which version of Pushy are you using? How long does it take for connections to close? Do connections close spontaneously, or is it always in response to attempting to send a notification?

**Comment by shahbour** [comment]
I was on version 0.6.0 and just updated to 0.7.1 couple of hours ago , i will keep an eye on it . Based on my monitoring i was getting connection reset only as a response to my attempt to send push .

**Comment by jchambers** [comment]
Okay. I expect the automated pings should resolve this issue; going to close this for now. Please let us know if the issue persists and I'll reopen if necessary.

Thanks!
