### ISSUE TITLE
Support for Http 1

### ISSUE THREAD

**Issue by manusdiaz** [relayrides/pushy#290]
Even though I'm pretty sure about the answer, because I checked the code, I would to know if it's possible to have support for http1 (and feedbackService, etc.) with pushy. Why? Http2 protocol is not currently supported by many proxys. The CISCO proxy implanted in my company doesn't support that protocol and update it it's not scheduled.

**Comment by jchambers** [comment]
It sounds like there might be some confusion about the APNs protocol here. The current version of the APNs protocol is based on HTTP/2, and HTTP/2 *only*. There's no "fallback" mode that uses HTTP/1. The version(s) of the protocol that preceded the current HTTP/2 version all used a proprietary "binary streaming" protocol, and not any flavor of HTTP.

So, in short, there is no HTTP/1 to go "back" to.

As for proxies, would one of Pushy's pre-existing [proxy schemes](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/proxy/package-summary.html) work?

**Comment by manusdiaz** [comment]
Mmm as far as I know and I checked one year ago, the preceded apple's api runs over ssl http 1, independenlty of the data format included in tcp packets. But really, the important thing is that a lot of proxies don't support HTTP/2. CISCO has told us not to suppor that protocol, at least, in the next 6 months :(. Anyway, I'm going to test other proxy schemes to give you feedback.

keep in contact. Thank you!

**Comment by jchambers** [comment]
Well, for reference, the old versions of the protocol are still documented in appendices in the APNs Developer Guide:

- [Appendix A: Binary Provider API](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW5)
- [Appendix B: Legacy Notification Format](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/LegacyFormat.html#//apple_ref/doc/uid/TP40008194-CH105-SW1)

In any case, it sounds like the immediate questions are answered:

- Unfortunately, we will not be providing support for anything other than the latest version of the APNs protocol (or API or whatever it is now).
- You may be able to work around your proxy issues using one of Pushy's (Netty's) built-in proxy handlers.

With that said, I'm going to go ahead and close this issue. Please leave a comment here if you think there's more to address.

Cheers!
