### ISSUE TITLE
Random SSL timeouts when using .p12 cert exported on Mac

### ISSUE THREAD

**Issue by cen1** [relayrides/pushy#293]
I randomly get SSL timeout errors when initiating the pushy client:

> maj 12, 2016 12:15:50 PM io.netty.handler.ssl.ApplicationProtocolNegotiationHandler handshakeFailure
> WARNING: [id: 0x9d8a793f, L:/192.168.29.164:52926 - R:api.development.push.apple.com/17.110.227.100:443] TLS handshake failed:
> javax.net.ssl.SSLException: handshake timed out

By randomly I mean that 80% of the time error occurs, 20% of the time everything works as expected. I have a .p12 file protected with password. File was exported from Mac OS keystore.
I converted .p12 cert to .pem and tried an SSL test to apple:
`openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert APNSandbox.pem -debug -showcerts`
and it works.
Then I converted .pem back to .p12 with openssl: `openssl pkcs12 -export -in APNSandbox.pem -out APNSandboxGOOD.p12 -passout pass:12345678`
and now pushy suddenly works. I am not yet 100% sure if it works reliably or I am just getting lucky at the moment so I will update this issue if I get a failure again but so far it seems that this solved the problem.
I was tipped off by this SO question: 
http://stackoverflow.com/questions/24101643/apple-apns-and-entrust-secure-ca-root-certificate

Any idea what the hell is going on here? Is Java/pushy having problems reading .p12 files exported on Mac OS or maybe it takes more time than openssl one for whatever reason, result in SSL timeout? A difference in .p12 export is causing a problem apparently.

**Comment by fjordansilva** [comment]
I have this problem too.

**Comment by cen1** [comment]
Apparently the certificate conversion is not the solution. I am getting SSL timeouts again after an hour.

**Comment by jchambers** [comment]
@cen1 Did this ever work as expected? Did this just start happening spontaneously after a period of generally seeming to be okay?

To tip my hand, I strongly suspect something upstream. If you had a bogus certificate, I'd expect the handshake to fail quickly. There was a mystery voodoo [server issue](https://forums.developer.apple.com/thread/44677) a few weeks ago, and I wonder if this might be related.

I see you're trying this against the sandbox environment, which I believe only has one server. I'm curious if this happens when you try against production. I'm also curious if it happens when you try connecting to different servers in the same environment; you'd need to connect by IP, and you can get the list of IPs using `dig`:

```
stratus:~ jon$ dig api.push.apple.com

; <<>> DiG 9.8.3-P1 <<>> api.push.apple.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63708
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.push.apple.com.		IN	A

;; ANSWER SECTION:
api.push.apple.com.	300	IN	CNAME	api.push-apple.com.akadns.net.
api.push-apple.com.akadns.net. 600 IN	A	17.172.234.16
api.push-apple.com.akadns.net. 600 IN	A	17.172.234.18
api.push-apple.com.akadns.net. 600 IN	A	17.172.234.15
api.push-apple.com.akadns.net. 600 IN	A	17.172.234.17
api.push-apple.com.akadns.net. 600 IN	A	17.172.233.39
api.push-apple.com.akadns.net. 600 IN	A	17.172.234.19
api.push-apple.com.akadns.net. 600 IN	A	17.172.234.22
api.push-apple.com.akadns.net. 600 IN	A	17.172.234.20
```

**Comment by cen1** [comment]
No, it never worked ok. It just randomly works or it doesn't but I have been implementing and testing with pushy just recently (past week). Unfortunately I can't test against production at the moment because we do not have a production certificate yet. The IPs you provided are production IPs right?

Anyway, I can also confirm that the old system (pre HTTP2) works normally (tested with a few different apn libs).

I checked the Apple development forums and there are quite a few topics in recent weeks describing the same simptoms so it does indeed seem like it's an upstream problem. What a disaster. :/

**Comment by cen1** [comment]
It seems this is exactly my simptoms: https://forums.developer.apple.com/thread/46194 
I will try to add a hosts file entry to resolve development server to the working IP and see if that solves the problem for now. Closing the issue since it's pretty obvious that it's not a problem in pushy.

**Comment by jchambers** [comment]
Bummer. Thanks for doing the research!

I'd encourage you to chime in on the forums and [file a bug report](https://bugreport.apple.com/) with Apple; that seemed to be effective in resolving similar outages in the past.
