### ISSUE TITLE
The HTTP/2 request are lacking the :authoriy header

### ISSUE THREAD

**Issue by pizzqc** [relayrides/pushy#296]
Initial issue was raised [under Jetty initially](https://github.com/eclipse/jetty.project/issues/578) to support HTTP/2 request without ':authority' header but seems that it may be better to fix this in Pushy in order to be more compliant to the spec.

**Reference**: [RFC 7540](http://tools.ietf.org/html/rfc7540) states that [clients SHOULD send](http://tools.ietf.org/html/rfc7540#section-8.1.2.3) the ':authority' field.

Thanks a lot of your support and update to APNS v2 -- greatly appreciated ;)

/Antoine

**Comment by jchambers** [comment]
To be clear, is the lack of `:authority` headers causing functional problems anywhere?

**Comment by jchambers** [comment]
> To be clear, is the lack of :authority headers causing functional problems anywhere?

I should have read https://github.com/eclipse/jetty.project/issues/578 more closely. It is causing problems if you're trying to build a mock server, but it sounds like there are no problems when talking to "real" APNs servers.

I agree that we should send the `:authority` header if possible, but the priority will definitely be maintaining compatibility with Apple's servers over adhering to the HTTP/2 spec.

**Comment by pizzqc** [comment]
I understand and there isn't any issue with APNS per say.  I handed up implementing a mock using netty in the end ;)

Thanks

**Comment by jchambers** [comment]
The real APNs servers don't seem to mind one way or the other, so it looks like there's no harm in adding the `:authority` header. Done in 05d8c27.
