### ISSUE TITLE
netty-tcnative-boringssl-static boringSSL 1.1.33.Fork16 is out.

### ISSUE THREAD

**Issue by hrqiang** [relayrides/pushy#298]
Please include this uber-jar to easy  setup. 
Tried netty-tcnative-boringssl-static-1.1.33.Fork16-SNAPSHOT-linux-x86_64.jar, it works perfectly.

**Comment by yaogdu** [comment]
how can i get this jar?

**Comment by yaogdu** [comment]
still error as below:
`No appropriate protocol (protocol is disabled or cipher suites are inappropriate)`

**Comment by jchambers** [comment]
@hrqiang We updated the README in b9e907c.

@yaogdu Please see the README. For general support questions, please try [the mailing list](https://groups.google.com/d/forum/pushy-apns), which has a wider audience and is generally more appropriate for getting help with issues that are neither bugs nor feature requests.
