### ISSUE TITLE
There is no way to pass netty "Http2Settings"

### ISSUE THREAD

**Issue by xuwei-k** [relayrides/pushy#301]
There is [`ApnsClientHandler#build(final Http2ConnectionDecoder decoder, final Http2ConnectionEncoder encoder, final Http2Settings initialSettings)`](https://github.com/relayrides/pushy/blob/pushy-0.7.2/src/main/java/com/relayrides/pushy/apns/ApnsClientHandler.java#L129) method.

but
- `ApnsClientHandler` class is not public.
- `ApnsClient` does not accept custom `ApnsClientHandler` https://github.com/relayrides/pushy/blob/pushy-0.7.2/src/main/java/com/relayrides/pushy/apns/ApnsClient.java#L455-L460

How can I use custom `ApnsClientHandler` and [Http2Settings](https://github.com/netty/netty/blob/netty-4.1.0.CR7/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Settings.java) ?

thanks.

**Comment by jchambers** [comment]
You're right; there's no public way to do that right now. Can you tell us a little more about your use case, though? Why do you want to use your own handler and settings?

**Comment by jchambers** [comment]
Closing for now, since the current design is pretty deliberate (we're hiding a lot of behind-the-scenes stuff to keep things simple for users). @xuwei-k, please leave a comment here if you can provide additional information and we'll be happy to reopen and revisit the issue. Thanks!
