### ISSUE TITLE
0.7.2 performance

### ISSUE THREAD

**Issue by sorheart** [relayrides/pushy#302]
Hi there.
I'm using pushy 0.7.2 now. It works pretty good, my iphone got the notification.
But when I try to test the performance, the result is not so ideal.
I can only send about 200 notifications in one second.

Maybe it is because of my testing method.I'm sending 10k messages to one single iphone.
So is this about the test method or something else?

I find it really difficult to test the performance of APNS, can someone give any advice?

**Comment by jchambers** [comment]
Hi! This sounds like more of a request for general support than it sounds like a bug report or feature request. We'd be happy to help, but it's probably better to move this conversation to [the mailing list](https://groups.google.com/d/forum/pushy-apns) for a few reasons:

1. The mailing list has a wider audience of people who might be able to contribute to an answer.
2. The wider audience on the mailing list could also benefit from a more public conversation; this sounds like the kind of thing that would be of general interest to the Pushy community.
3. We can't reasonably resolve this issue by committing code.

Sound good? In the meantime, I'll close this issue and look forward to seeing you on the mailing list.

Cheers!
