### ISSUE TITLE
Pushy Proxy Support requires external DNS lookup

### ISSUE THREAD

**Issue by wodecker** [relayrides/pushy#309]
Hello, 

we want to switch to Pushy library to be able to use the new APNS Provider API. Until now, we have been using JavaPNS library to send APNS push messages.
As our server is on an internal network, we need the proxy support that became available in Pushy 0.6. (We also talk to GCM for Android Pushes, and all  external communication goes through our proxy.)

I managed to have Pushy (current version 0.7.2) run successfully on my local development environment, but when running on the internal server, I was getting a ClientNotConnectedException.
(This was after I have resolved all issues with SSL and ALPN.)

I then had a network colleague look at the protocol layer on the host when initiating the SSL Connection over the proxy.
Surprisingly, the Library first tried to resolve the name **api.push.apple.com** which failed on the internal server, as this server cannot resolve external host names.

This seems to be the root cause of the _ClientNotConnectedException_, because when we configured a valid IP in the local /etc/hosts file on the internal Linux Server, the Pushy call succeeded.

Our network colleagues also confirmed that the name resolution should be done by the proxy and not by the internal server.

To hardcode the IP Address of that Apple APNS host in the local hosts file is definitely no option for a stable environment, as we don't know if all apple hosts will keep their IP Adresses forever...

Also, all other communication to external systems over proxy worked so far, so that I think that this is a problem specific to the pushy library or the referenced/included libraries.

Can anybody help or advise how to solve that issue?

Thanks and kind regards,

Wolfgang

**Comment by jchambers** [comment]
> we don't know if all apple hosts will keep their IP Adresses forever…

They certainly will not. Production IPs change frequently.

Overall, it sounds like this might be related to [an issue raised on the mailing list](https://groups.google.com/d/msg/pushy-apns/iYtB7TSi9lU/FKbVE1wdAQAJ). Does that sound right to you?

**Comment by jchambers** [comment]
Also, reading around a bit, could you get away with a [JVM-level proxy](http://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html) instead of specifying a `ProxyHandlerFactory`?

**Comment by wodecker** [comment]
Yes, the issue in the mailing list reported by Stephen Wong has probably the same root cause.

There, they have a restricted Proxy where Domain Names have to be configured explicitely.
In our case, the Server running Pushy is restricted of external DNS lookup.

The common problem is, that the Pushy mechanism (Pushy or Netty, I didn't have a closer look so far) does a DNS lookup upfront and sends the IP Address to the Proxy instead of sending the Host name to the proxy and let the Proxy resolve the Name.

**Comment by wodecker** [comment]
Concerning the use of JVM-level proxy:
For other external communications we have set the Properties **https.proxyHost** and **https.proxyPort** as JVM Parameters.
With these settings the external calls automatically use the configured Proxy. There was no need to code something in our part.
But as far as I can remember, this was not working with Pushy, so we did wait for the explicit Proxy Support.

**Comment by jchambers** [comment]
Understood. Thanks for the clarification; we'll look into it.

**Comment by jchambers** [comment]
Ah—I think @Nowheresly solved this for us [a long time ago](https://github.com/relayrides/pushy/pull/161/files#diff-04c6e90faac2675aa89e2176d2eec7d8R218) and we just didn't notice.

@wodecker if I push some experimental code to a branch, would you be comfortable giving it a try in your proxied environment to see if it resolves the issue?

**Comment by wodecker** [comment]
Thanks, looks very promising!
We have an automated build and deployment system for that proxied environment. It is fully based on Maven, so easiest way is to have the fix available in Maven Central in order to test it.
So I'll probably wait until 0.7.3 is released.
