### ISSUE TITLE
Publicize MockApnsServer

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#313]
Pushy uses a [mock server](https://github.com/relayrides/pushy/blob/pushy-0.7.3/pushy/src/test/java/com/relayrides/pushy/apns/MockApnsServer.java) for testing purposes. If there's demand, we could polish and publicize it (i.e. move it from `src/test` to `src/main`) for Pushy users who want to use it in integration tests or benchmarks.

What do you all think? Helpful feature or needless noise?

**Comment by jmason** [comment]
Absolutely -- scale-testing APNS is pretty tricky without it.

**Comment by jchambers** [comment]
My main concern was actually around introducing Bouncy Castle as a mainline dependency, since the mock server uses it to extract topics from client certificates. Now that auth tokens are on the horizon (see #314), though, we can probably just skip over topic checking entirely. It'll be a gap, for sure, but probably one we can live with.

**Comment by jchambers** [comment]
Done! #315 is merged.
