### ISSUE TITLE
 Unable to load the library: netty-tcnative-osx-x86_64.

### ISSUE THREAD

**Issue by Areii** [relayrides/pushy#325]
pushy `0.7.3` `idea` `gradle`

```
> java.lang.UnsatisfiedLinkError: no netty-tcnative-osx-x86_64 in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
> 	at java.lang.System.loadLibrary(System.java:1122)
> 	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:189)
> 	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:161)
> 	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:238)
> 	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:65)
> 	at com.relayrides.pushy.apns.ApnsClient.getBaseSslContextBuilder(ApnsClient.java:400)
> 	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:392)
> 	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:388)
> 	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:365)
> 	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:266)
> 	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:239)
```

**Comment by Areii** [comment]
fixed
add  compile group: 'io.netty', name: 'netty-tcnative-boringssl-static', version: '1.1.33.Fork17'

**Comment by viswanathankasi** [comment]
This does not work for me as i always get the error

**Comment by wangruochan** [comment]
same issue here。
**pushy 0.11.3 osx idea  maven，jdk8**

`07:30:30.603 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - netty_tcnative_osx_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /var/folders/zk/tmh02xfn5kv6dbck_2_c1_jr0000gn/T
java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:215)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:82)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:419)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:89)
	at com.turo.pushy.apns.SslUtil.getSslProvider(SslUtil.java:49)
	at com.turo.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:490)
	at ApnsTest.sayHello(ApnsTest.java:29)`

**Comment by jchambers** [comment]
So two things here:

1. Netty/netty-tcnative will try a number of strategies to load the appropriate native library. It may generate some debugging noise in the process, which is harmless. Unless this is blocking notifications from going out, I wouldn't worry about it.
2. As of Pushy v0.13.0, netty-tcnative isn't required at all for Java 8 and newer. You can just exclude it as a dependency if you'd like. After #603 goes in, netty-tcnative won't be included as a dependency unless it's unavoidable.

**Comment by kim-jin** [comment]
you could use tomcat and jdk 7 instead tomcat and  jdk 8 fix this , i fix it from this
