### ISSUE TITLE
Add support for apns-id header

### ISSUE THREAD

**Issue by bennesher** [relayrides/pushy#329]
Please add support for the `apns-id` header in the `PushNotificationResponse` interface, and preferably also in the `ApnsPushNotification` interface (for client-set ids).

**Comment by jchambers** [comment]
Can you elaborate on the use case here? I totally get why you'd want to attach a unique identifier to a push notification, but what we've encouraged in the past is to just make your own implementation of `ApnsPushNotification` (or subclass of `SimpleApnsPushNotification`) that has all of the bonus metadata you need, then create an `ApnsClient<FancyPushNotification>`.

Is there a reason you actually need to send that ID to/from the APNs server?

**Comment by bennesher** [comment]
The theoretical use-case for having client-set ids is for setups that include their own tracking of messages, and generate the ids before sending.  

The use-case for being able to read the Apple-assigned message ids is for logging once the message is sent, in case we need to trouble-shoot a message delivery problem.

The second use-case is the main focus of my interest in this feature; including support for the former was merely out of a desire for completeness of the client, given that Apple supports that.

I concluded that this would need to be implemented in the library (rather than using a subclass), because the handling of headers is buried within the ApnsClientHandler.

If I have the time, I may implement this myself & submit a pull request.

**Comment by jchambers** [comment]
> I concluded that [getting the Apple-assigned `apns-id`] would need to be implemented in the library (rather than using a subclass), because the handling of headers is buried within the ApnsClientHandler.

That's correct.

> If I have the time, I may implement this myself & submit a pull request.

That's definitely appreciated, but I have to warn you there's a good chance we'd decline the pull request. It's very, very possible that I'm missing something important, but it's not clear to be how the `apns-id` would help with troubleshooting. Can you explain that process a bit more?

Thanks!

**Comment by gntcom** [comment]
i need to get response of notification asynchronously. how can i track my messages without apns-id ?

**Comment by jchambers** [comment]
> how can i track my messages without apns-id ?

Again, there are several mechanisms for tracking notifications. If you want to attach IDs to notifications without using the `apns-id` header, you can create your own `ApnsPushNotification` implementation that has all the metadata you want.

Note also that the [`ApnsClient#sendNotification`](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/ApnsClient.html#sendNotification-T-) returns a `Future` that yields a [`PushNotificationResponse`](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/PushNotificationResponse.html). The `PushNotificationResponse` will give you the original notification if you want to maintain your own list of notifications.

If you're using anonymous inner classes (or lambdas) as listeners, then you can even do something like this:

```java
final ApnsPushNotification myNotification = ...;

client.sendNotification(myNotification).addListener(... {
    public void operationComplete(final Future<PushNotificationResponse<ApnsPushNotification>> future) throws Exception {
        doWhatNeedsToBeDoneWith(myNotification);
    }
});
```

**Comment by jchambers** [comment]
And @bennesher let me be clear that I don't mean to be difficult about this whole thing; when I say I don't know how to use server-generated `apns-id` values to debug delivery issues, I mean exactly that. I don't mean to say that I don't think it can be done, just that I'm not familiar with the approach you have in mind.

Cheers!

**Comment by 123avi** [comment]
@bennesher there is pull request for that

**Comment by jchambers** [comment]
> there is pull request for that

Well, not quite. #347 introduces support for `apns-collapse-id`, but not `apns-id`. The former provides callers with meaningful control over the presentation and behavior of notifications on the destination device, while the latter does not.

I'm going to close this issue for now, but please let me emphasize that I'm still totally open to arguments that we should add support for the `apns-id` header. @bennesher just leave a comment here if you feel so inclined and we'll revisit the issue.

**Comment by shawnchain** [comment]
My point of view: Without the apns-id, I have to update the push message status(like, mark as dropped for rejection response)right there in the callback code. That's true if apple guarantee that server response is "instant". But if we regard the apple server as a "asyn" one that may delay the process for a long period like SMS system, a pre defined apns-id is necessary to track and update the message later sometime.  Currently I have the "UUID" field defined in my own PUSH_MESSAGE database table, but left unused because of the lacking support of pushy API.  

So here I vote for support "APNS-ID".

**Comment by jchambers** [comment]
> That's true if apple guarantee that server response is "instant". But if we regard the apple server as a "asyn" one that may delay the process for a long period like SMS system…

While neither extreme is completely true, the former is more true than the latter. Bear in mind that all we learn from the APNs server is whether or not the *server* accepted the notification, and not whether the *destination device* actually received the notification.

In our practical experience, response time from the APNs server is dominated by network latency, which makes it effectively indistinguishable from an "instant" response.
