### ISSUE TITLE
something about netty and tomcat and APR

### ISSUE THREAD

**Issue by Areii** [relayrides/pushy#331]
i use` pushy 0.7.3 `and` netty-tcnative-boringssl-static 1.1.33.Fork17` and `spring boot(tomcat embed)` .it's working well.
and then ,i package my server to a war and deploy on tomcat 8.0.35 ( linux centos6.5 ,openssl 1.0.2h).
it throws some exceptions like:
 `java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider`

i think that it because tomcat8 which on linux doesn't use netty-tcnative-boringssl-static(apr in it) and it(tomcat) use linux own APR.and tomcat 8 doesn't support http2.0 until tomcat9.

Is my opinion right？

**Comment by jchambers** [comment]
This is, unfortunately, a [known issue with `netty-tcnative`](https://github.com/netty/netty-tcnative/issues/136). I'll try to advertise it more prominently on our side shortly.

**Comment by jchambers** [comment]
I updated the docs in dc3e957; while I'm still hoping the upstream issue will be fixed soon, I think this is all we can really do in the meantime.

Thanks again!
