### ISSUE TITLE
[0.7.3] setFlushThresholds(0, 0) make sending notification delayed

### ISSUE THREAD

**Issue by dittos** [relayrides/pushy#332]
Test code:

```java
public class PushyTest {
    public static void main(String[] args) throws Exception {
        ApnsClient<SimpleApnsPushNotification> apnsClient;
        apnsClient = new ApnsClient<>(...);
        apnsClient.setFlushThresholds(0, 0);

        apnsClient.connect(ApnsClient.DEVELOPMENT_APNS_HOST).await();
        System.out.println("connected");

        // Wait event loop to start polling
        Thread.sleep(1000);

        SimpleApnsPushNotification notification = new SimpleApnsPushNotification(...);
        System.out.println("send begin");
        apnsClient.sendNotification(notification).await();
        System.out.println("send complete");
        apnsClient.disconnect().await();
    }
}
```

It takes very long time between `send begin` and `send complete`. If changed to `setFlushThresholds(1, 1)`, it is sent immediately.

Stack dump right after `send begin` shows NioEventLoop blocked at `select()` call.

**Comment by ewmkkpe** [comment]
I think this is same issue with https://github.com/relayrides/pushy/pull/326

**Comment by jchambers** [comment]
Can how clarify how long a "very long time" is?

**Comment by dittos** [comment]
I meant ~1 minute.

**Comment by jchambers** [comment]
Yep—that sounds problematic ;)

I'm curious why you're having this issue here, but we don't see the same thing in [`ApnsClientTest#testSendNotificationWithImmediateFlush()`](https://github.com/relayrides/pushy/blob/v0.7.3/pushy/src/test/java/com/relayrides/pushy/apns/ApnsClientTest.java#L451). Will investigate, though as @ewmkkpe points out, the flush thresholds will be going away shortly (see #326).

**Comment by jchambers** [comment]
I can (sometimes) reproduce this by adding a `waitForInitialSettings` call to `testSendNotificationWithImmediateFlush`. Will continue to investigate.

**Comment by jchambers** [comment]
After some thought, I've decided to roll back fancy flushing entirely. This should no longer be an issue now that #350 is merged. We'll look forward to upstream support for this feature in the near future.
