### ISSUE TITLE
Any method to push multi notifications ? Or any example to handle multi result properly .

### ISSUE THREAD

**Issue by LilyBlooper** [relayrides/pushy#339]
I have to say , Pushy maybe is the best java apns library right now . 
I hava tried notnoop and other libraries ,those libs cant handle notification list with invalid tokens within .
And the invalid tokens will influence the later right tokens in the queue . So I have to change.
Pushy is quite good . Each token get proper result .
However , the performance is not so good . Please tell me is there any way to push multiple notifications 
quicker ?

**Comment by jchambers** [comment]
> However , the performance is not so good

Can you please be more specific? What kind of performance are you seeing? What do you expect? Does it appear that you're using more CPU time than seems reasonable? Could you be affected by #332?

> Please tell me is there any way to push multiple notifications quicker ?

You should be able to just use a `for` loop, honestly. There's no protocol-level support for batched operations, to be clear, so other libraries that offer "batch" sending are just using a `for` loop internally.

One point of advice: if you're trying to send a bunch of notifications, make sure you're not (a) making blocking calls in listeners or (b) waiting for each future to finish before sending the next notification. Does that help?

**Comment by LilyBlooper** [comment]
Thanks . Really helps.
Sadly now I'm using the plan (b) , I will change my code and try again .
