### ISSUE TITLE
Incoherent timeout type

### ISSUE THREAD

**Issue by JensRantil** [relayrides/pushy#341]
**Background:** `ApnsClient#setConnectionTimeout` takes an `int` while `ApnsClient#setWriteTimeout` takes a `long`.

**Issue:** They both take a timeout, but different types.

**Proposal:** Make them have same input type. Specifically I propose `long` as that seem to be Java best practise (and `TimeUnit#convert` returns it etc.).

**Additional:**

 * Since `int` is a `subset` of `long`, changing this shouldn't have any implications on backwards compatibility.

**Comment by JensRantil** [comment]
Also `ApnsClient#setGracfulShutdownTimeout` takes `long`.

**Comment by jchambers** [comment]
Good news! This is resolved in #310, which is scheduled for inclusion in our next release.
