### ISSUE TITLE
Question: Why does `ApnsClient` have to be generic?

### ISSUE THREAD

**Issue by JensRantil** [relayrides/pushy#342]
Maybe I'm misunderstanding `ApnsClient`. I've only coded in it for maybe 30 minutes, so I might be wrong!

Above said, I noticed that it uses generics and introduces `T extends ApnsPushNotification`. From the perspective of polymorphism this means that an instance of the class can't be used with different implementations of `ApnsPushNotification`. Is this really a deliberate decision? Proposal here is to make the individual methods generic, not the whole class in itself. That is, replacing with

    public Future<PushNotificationResponse<T>> sendNotification(final T notification)

with

    public <T extends ApnsPushNotification> Future<PushNotificationResponse<T>> sendNotification(final T notification)

. What do you think of this? Doable?

**Comment by jchambers** [comment]
In short, I think this is possible, but will require significant internal refactoring.

**Comment by jchambers** [comment]
> From the perspective of polymorphism this means that an instance of the class can't be used with different implementations of `ApnsPushNotification`.

Also, that's not true. You can use multiple classes as long as they share a common base class.

For context, can you please elaborate on your use case?

**Comment by jchambers** [comment]
#349 has been merged.
