### ISSUE TITLE
Expose TopicUtil or use it internally

### ISSUE THREAD

**Issue by cen1** [relayrides/pushy#353]
Why is src/test/java/com/relayrides/pushy/apns/TopicUtil.java not publicly available for usage or used to simplify the library behind the scenes? It has a nice method to extract the topic aka. bundle identifier from the certificate which could reduce the SimpleApnsPushNotification constructor to two arguments. There is no need to specify the topic since that information is already available, especially in the most simple sending scenario. Obviously, 3 arg constructors with explicit topic can be left as is. Any specific reasons why this isn't used already?

**Comment by jchambers** [comment]
> Any specific reasons why this isn't used already?

Yes. It depends on [BouncyCastle](https://www.bouncycastle.org/), which is a bigger dependency than I think we should impose upon end users for this one feature. Additionally, certificates will be going away entirely soon and will be replaced by bare private keys, which generally don't have metadata (i.e. topics) attached. Even if there weren't a dependency issue, I think the upcoming protocol changes mean that we shouldn't decrease visibility of topics even if there were no dependency issues.

Please see #314 for details of the upcoming token-based authentication scheme and #348 and #323 for discussion about why we don't want to automate topic handling in the near term.

**Comment by cen1** [comment]
I just hacked together a function using TopicUtil as a sample and did not require BouncyCastle anywhere since the default topic can be parsed from certificate UID. At least for the regular case, BouncyCastle is not needed.

I guess it's fine if certs are being ditched in the future. Thank God for that at least.

**Comment by jchambers** [comment]
> the default topic can be parsed from certificate UID

True, but the secondary topics are stored in a certificate extension. To read those, we need to parse ASN.1 primitives, and that's where the BouncyCastle dependency comes in.

> I guess it's fine if certs are being ditched in the future. Thank God for that at least.

Well, don't let me get your hopes up too much—I think it's actually going to be a little more complicated in most cases. My understanding right now is that users will need to:

1. Give Pushy a private key for a given team ID.
2. Tell Pushy which topics are associated with that team ID.
3. Always specify a topic when sending notifications.

We'll see how things shake out, though.
