### ISSUE TITLE
DropwizardApnsClientMetricsListener Cunstroctor to provide external metricRegistery

### ISSUE THREAD

**Issue by saumitrabhave** [relayrides/pushy#358]
Hi:

I just observed this while testing out the master branch. It would be great to have a second constructor(or some other way) to provide the metricRegistry externally.

Most of the applications will have a single metricRegistry with different reporters attached to it, it will be useful to reuse the same instance inside the DropwizardApnsClientMetricsListener.

**Comment by jchambers** [comment]
Note that the `DropwizardApnsClientMetricsListener` is itself a `Metric`, which means you can do this:

```java
myMetricRegistry.register("com.example.myapp.pushNotifications", metricListener);
```

Passing a registry as a constructor argument seems like it'd only remove that one trivial step from callers' responsibility, and would do so at the cost of flexibility and increased complexity in the library itself. Thanks for the suggestion, but I think we're going to leave this one as it is.
