### ISSUE TITLE
Add fields for Safari push notifications

### ISSUE THREAD

**Issue by mmantel** [relayrides/pushy#373]
Sending a Safari push notification requires a "url-args" field in the "aps" object. It also allows an optional "action" field in the "alert" object. There is no apparent way to add either of these fields with ApnsPayloadBuilder.

[See documentation here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW12). Sample payload looks like:

```
{
    "aps": {
        "alert": {
            "title": "Flight A998 Now Boarding",
            "body": "Boarding has begun for Flight A998.",
            "action": "View"
        },
        "url-args": ["boarding", "A998"]
    }
}
```

**Comment by fjordansilva** [comment]
+1

Do you have antes example about how ti send notifications to Safari and the code needed in the client side?

**Comment by jchambers** [comment]
I've added these fields to the payload builder in #393. Please let me know if anything seems amiss.
