### ISSUE TITLE
Unregistered returned with a valid token

### ISSUE THREAD

**Issue by littlewitchanita** [relayrides/pushy#375]
I just found that some of my users stopped receiving push notification recently. Checked the log and found that Apple returned "Unregistered" with a timestamp.

I've verified the token using the old protocol (which I used "notnoop" java library) with the same cert and token, the device successfully received the push message.

The strange thing is not all my users failed, just some of them.
The only clue I got is those users which failed to receive the push message, are all using iOS 10.0.x.

Anyone have idea on what's going on? Is it pushy's issue or Apple's issue?

Thanks a lot!

**Comment by kkrgwbj** [comment]
Ios10 can receive.our project is used pushy,it's work very well.Would you sure the 'TOPIC' is right?And use pushy,you need your certificate is Apple based on http2 certificate.

**Comment by littlewitchanita** [comment]
most of the users can receive the push, only a few of them have this problem, so I don't think it's the problem with certificate or topic.

**Comment by kkrgwbj** [comment]
Okay,That I don't know what problem,You can see such as the author to reply you.

**Comment by jchambers** [comment]
This does sound like an upstream issue to me. By all appearances, we are (a) sending the notification to Apple's servers correctly and (b) receiving/processing their reply. Granted, the reply isn't what we'd expect, but that's beyond our control. I'd say it's muuuuuuuch more likely that there's some difference in the way Apple is implementing the two different APNs protocols than it is that the specific libraries are doing something differently.

My strong recommendation would be to [file a bug report with Apple](https://bugreport.apple.com). You might also mention it on the [push notification forums](https://forums.developer.apple.com/community/system-frameworks/push-notifications), though the latter doesn't seem to be the most effective route to getting problems addressed in an official capacity.

**Comment by littlewitchanita** [comment]
ok, I agree it should be upstream problem. Close this issue.

**Comment by naftuli** [comment]
did someone opened a but report with Apple? this happens to me too.
