### ISSUE TITLE
Prepare an example project [low]

### ISSUE THREAD

**Issue by petrdvorak** [relayrides/pushy#377]
While the library seems very nice, the examples are somehow limited. They are basically just code snippets. It would be nice to have some very simple demo app (maybe a Spring Boot web app - this would be awesome!) showcasing how the library should be used.

**Comment by jchambers** [comment]
Can you be more specific? What do you think we need to show that's not already covered by the examples?

**Comment by petrdvorak** [comment]
IMO it's about suggested usage and usage style. I was having slight doubts in following parts:

- What exactly should be in my pom.xml? Yes, it's covered in docs - it would be nice / faster to see an actual pom.xml file.
- How do I manage the lifecycle of the APNs client in the real world situation (for example, in a controller). Should it be in a separate _bean / _service that I autowire? Or should I create it ad hoc? ...
- How do I send notification batch in the _Controller and process the result with a future listener?
- Is this library even suitable for an "API application" (such as Spring Boot application)? Isn't it more suitable for the executable JAR that just sends a notification batch after being invoked by the "java -jar myjar.jar" spell? (for example - just having a listener in a Spring Boot controller just feels wrong, since the request / response cycle was already handled by the framework).
- How do I send multiple push notifications asynchronously, while returning the batch info (for example number of sent messages) synchronously?

Each of these items are covered in the docs to some extent and many of them are about "How do I do this in Java". It would be nice to see some compact but complete  example application to make that learning curve less steep.

Anyway, the priority is low - I will have my use-case ready before this would be ready. Just thought it could save people some time...

**Comment by petrdvorak** [comment]
Let's drop this issue - I found it's possible to work without the sample project if you deep dive into the project...

**Comment by badgersow** [comment]
@petrdvorak Did you come up with example yourself?
If yes, could you please post it here?

**Comment by bugix** [comment]
I created a simple demo app. https://github.com/bugix/pushy

**Comment by ChunBoL** [comment]
@bugix demo removed？

**Comment by petrdvorak** [comment]
Hello guys, we are using Pushy in our [PowerAuth](https://www.powerauth.com/) Push Server project, available here:

- https://github.com/lime-company/powerauth-push-server

If you have any questions regarding Pushy integration with Spring Boot, drop me a line on e-mail. Making latest Pushy work with Spring / Spring Boot seems quite easy - it used to be much harder couple versions ago...
