### ISSUE TITLE
Add support for "thread-id" in SimpleApnsPushNotification class

### ISSUE THREAD

**Issue by petrdvorak** [relayrides/pushy#382]
The SimpleApnsPushNotification class is missing the `thread-id` attribute, see:

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1

> Provide this key with a string value that represents the app-specific identifier for grouping notifications. The system groups notifications with the same thread identifier together in Notification Center and other system interfaces. For local notifications, this key corresponds to the threadIdentifier property of the UNNotificationContent object.

**Comment by petrdvorak** [comment]
Can be work-around with a "custom property".

**Comment by petrdvorak** [comment]
Hmmm... that's weird. You are right. But it somehow works - push messages with the same "thread-id" are replaced in notification center, namely when I include:

```java
payloadBuilder.addCustomProperty("thread-id", push.getMessage().getCollapseKey());
```

Notification is replaced by a newer one...

**Comment by jchambers** [comment]
APNs: Hmm… That's Weird™.

Well, good to know that there's an immediate workaround, but I wouldn't bank on it working forever. We'll get this in for real shortly. Thanks for calling it to our attention!

**Comment by jchambers** [comment]
@petrdvorak Took a shot at this in #394. Seem legit?

**Comment by jchambers** [comment]
Actually, @petrdvorak could you also verify that this… works? ;) I didn't observe any difference in behavior between:

1. Not including a thread ID of any kind
2. Including a thread ID directly in the `aps` section (#394)
3. Including a thread ID as a custom property

Is it possible the thread ID needs to be in some specific format? UUID? Or am I just looking for the wrong behavior?

**Comment by petrdvorak** [comment]
This should work now - I will be able to test it during the holidays, the end of the year is a bit crazy. I have recorded a rather dramatic and poorly edited video of push behavior without / with "thread-id" property. Notice that push without thread-id property go below each other, while push with that property are replaced (as long as the ID is the same for all payloads).

[apns-push-thredID-lowq.zip](https://github.com/relayrides/pushy/files/645380/apns-push-thredID-lowq.zip)

**Comment by jchambers** [comment]
Very, very strange. That's not at all what I'm seeing in testing; messages just keep stacking up for me, with or without a `thread-id`. To eliminate some possibilities, can you tell me what specific thread ID you're using for your demo? Also, what version of iOS are you using?

Thanks kindly!

**Comment by jchambers** [comment]
…also, did you have to modify the receiving app in any way to enable threading?

**Comment by jchambers** [comment]
For the curious, the exact payload I'm testing with is:

```json
{"aps":{"alert":"Thread!","sound":"default","thread-id":"thread-id"}}
```

**Comment by petrdvorak** [comment]
This is weird, the [Apple documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW3) is quite explicit about the `thread-id` attribute behavior...

My APNs payload looks like this (I still use the "custom property", as discussed earlier):

```json
{"aps":{"alert":{"body":"Your account balance is $25,450.45.","title":"Good morning!"},"sound":"default"},"thread-id":"balance"}
```

I then send the notification like this:

```java
final SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(
    token, // <== my push token
    iosTopic, // <== my app bundle ID
    payload, // payload above
    validUntil, // <== null
    DeliveryPriority.IMMEDIATE, // <== constant
    pushMessage.getMessage().getCollapseKey() // <== maybe the collapse key?
); 
final Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture
     = apnsClient.sendNotification(pushNotification);
```

I don't remember doing anything different in my iOS app. I have this in my Info.plist file:

```xml
<key>UIBackgroundModes</key>
<array>
    <string>fetch</string>
    <string>remote-notification</string>
</array>
```

This is my simplified AppDelegate class:

```swift
import UIKit
import UserNotifications

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate {

	var window: UIWindow?

	func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
		let userNotificationSettings = UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
		application.registerUserNotificationSettings(userNotificationSettings);
		application.registerForRemoteNotifications()
		return true
	}
	
	func applicationDidBecomeActive(_ application: UIApplication) {
		application.applicationIconBadgeNumber = 0
	}
	
	func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
		print("Error registering to push server")
	}
	
	func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
		var token = ""
		for i in 0..<deviceToken.count {
			token = token + String(format: "%02.2hhx", arguments: [deviceToken[i]])
		}
		print("Push Token: \(token) <= add this in database")
	}
	
	func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) {
		print("\(userInfo)");
		
		let notification = UILocalNotification()
		notification.alertTitle = userInfo["title"] as! String?
		notification.alertBody = userInfo["body"] as! String?
		notification.fireDate = Date()
		application.scheduleLocalNotification(notification)
	}
	
	func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
		print("\(userInfo)");
		
		let notification = UILocalNotification()
		notification.alertTitle = userInfo["title"] as! String?
		notification.alertBody = userInfo["body"] as! String?
		notification.fireDate = Date()
		application.scheduleLocalNotification(notification)
		completionHandler(.newData);
	}

}
```

**Comment by jchambers** [comment]
Ahhhh—I see. I strongly suspect this is related to the `collapse-id`. Will experiment a bit more and see what I can figure out. Many, many thanks for the additional details!

**Comment by jchambers** [comment]
Waaaaaaaaait a second. @petrdvorak I'm pretty sure the behavior shown in your video is *entirely* attributable to using a `collapse-id`. Messages are getting replaced, not grouped, which is what `collapse-id` promises.

I've asked contributors for other push notification libraries how this has worked out for them:

- https://github.com/node-apn/node-apn/issues/484
- https://github.com/sideshow/apns2/pull/41

I have a couple more ideas for things to try out later (what happens if we intersperse messages from app A and app B, for example) this evening, too.

**Comment by florianreinhart** [comment]
You are right. That behavior is attributed to collapse-id.

The use case for thread-id is to group several messages, e.g. in a chat conversation. That's also what [Apple's documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW3) says.

In your example `thread-id` is inside the `alert` dictionary. However, it must be inside the `aps` dictionary, e.g. `{"aps":{"alert":"Thread!","sound":"default"},"thread-id":"thread-id"}`

**Comment by petrdvorak** [comment]
Ok, sorry for the mass panic... I had a little retard moment there... but... what Apple docs says about `thread-id`:

> Provide this key with a string value that represents the app-specific identifier for grouping notifications. The **system groups notifications with the same thread identifier together in Notification Center and other system interfaces**. For local notifications, this key corresponds to the threadIdentifier property of the UNNotificationContent object.

Now, this is what they say about `apns-collapse-id`:

> ### Quality of Service, Store-and-Forward, and Coalesced Notifications
> 
> Apple Push Notification service includes a default Quality of Service (QoS) component that performs a store-and-forward function. If APNs attempts to deliver a notification and the destination device is offline, APNs stores the notification for a limited period of time and delivers it when the device becomes available again. This component stores only the most recent notification per device and per app. If a device is offline, sending a new notification causes the previous notification to be discarded. If a device remains offline for a long time, all stored notifications are discarded.
> 
> To allow the coalescing of similar notifications, you can include a collapse identifier with the notification request. Normally, when a device is online, each notification you send is delivered to the device. **However, when the apns-collapse-id key is present in your HTTP/2 request header, APNs coalesces requests whose value for that key is the same. For example, a news service that sends the same headline twice could use the same collapse identifier value for both notification requests. APNs would then coalesce the two requests into a single notification for delivery to the device.**

This seems to imply that `apns-collapse-id` is used by APNs internally in order not to send too many messages with the same or very similar content in a short period of time and instead, it would "coalesce the two requests into a single notification for delivery to the device".

I will fix my code, consider this fixed. Thank you for helping me with this, guys!

**Comment by petrdvorak** [comment]
@florianreinhart That `thread-id` should be in `aps` directory, not in the payload root (in your example). @jchambers has it right...

**Comment by florianreinhart** [comment]
@petrdvorak that's what meant, sorry about that.

**Comment by jchambers** [comment]
@florianreinhart Thanks for dropping in!

So my understanding from this conversation is that what we have in #394 (`thread-id` goes in the `aps` object) is correct, but I still don't see any practical effect in terms of grouping notifications when they arrive on an actual phone. @florianreinhart do you?

**Comment by jchambers** [comment]
Well, I still can't demonstrate that setting a thread ID actually *does* anything, but I'm very confident that we're setting the thread ID correctly. It may just be that I'm looking in the wrong places for the change in behavior. I'm going to go ahead and merge #394. We'll revise as new information becomes available.

**Comment by jchambers** [comment]
For what it's worth, it sounds like [other people on the APNs forums](https://forums.developer.apple.com/message/188955) are also struggling to figure out what effect `thread-id` really has. I've filed [rdar://29670386](https://openradar.appspot.com/radar?id=4938030620082176) to track the issue, too.

**Comment by sideshow** [comment]
I was able to confirm that setting a `thread-id` in the payload as you have done does come through into a Notification Content app extension. Thanks for pointing out our incorrect implementation in https://github.com/sideshow/apns2/pull/41 :)

**A better explanation from Apple:**

"The system calls this method to deliver notifications to your Notification Content app extension. Use this method to configure the contents of your view controller or to incorporate content from a new notification. This method may be called multiple times while your view controller is visible. Specifically, it is called again when a new notification arrives whose threadIdentifier value matches the thread identifier of the notification already being displayed. The method is called on the main thread of your extension".

https://developer.apple.com/reference/usernotificationsui/unnotificationcontentextension/1648525-didreceive

**Comment by jchambers** [comment]
:metal:

Thanks for the detailed explanation, and thanks for the indeed-much-better-explanation of what we're looking for. Hope I can return the favor some time!

In the meantime, I'll update our docs to make reference to the `didReceive` explanation, close the upstream bug report, and update the various forum threads.

Cheers!

**Comment by sideshow** [comment]
No probs, thanks for finding a bug in the apns2 implementation!
