### ISSUE TITLE
[Question] Confusing about how to "Using a native SSL provider"

### ISSUE THREAD

**Issue by kientux** [relayrides/pushy#388]
As in README.md, to use a native ssl provider, I just need to

 - Use pushy v0.8.1
 - Add netty-tcnative at least Fork22

```
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-boringssl-static</artifactId>
    <version>1.1.33.Fork23</version>
</dependency>
```

 - Add latest `alpn-api` as runtime dependency
```
<dependency>
    <groupId>org.eclipse.jetty.alpn</groupId>
    <artifactId>alpn-api</artifactId>
    <version>1.1.3.v20160715</version>
    <scope>runtime</scope>
</dependency>
```

But I still has this exception:
```
Caused by: java.lang.RuntimeException: ALPN unsupported. Is your classpatch configured correctly?...
```

If I add `alpn-boot` to boot classpath, then it runs just fine, but (of course), it uses JDK SSL instead of native SSL:

```
c.r.p.a.ApnsClientBuilder [ApnsClientBuilder.java : 377] Native SSL provider not available; will use JDK SSL provider.
```

So exactly what can I do to use native SSL? With pushy v0.8, I don't even need to add neither `alpn-api` as runtime dependency nor `alpn-boot` to boot classpath.

// I'm building the project in macOS 10.12.

**Comment by jchambers** [comment]
Adding `netty-tcnative-boringssl-static` as a dependency should Just Work™. Please see #379 for some sample code that can help us understand what's going wrong here.

One very likely problem, though: are you trying to run your application inside Tomcat?

**Comment by jchambers** [comment]
Closing due to lack of information. @kientux we'll happily re-open this if you can provide some more information!

**Comment by kientux** [comment]
Oh sorry, turn out it's just some messes about my dependencies that makes it failed to work. Just add `netty-tcnative-boringssl-static` is enough as you said!
