### ISSUE TITLE
Auto-collapsing alert dictionary into string

### ISSUE THREAD

**Issue by yoorick** [relayrides/pushy#390]
Long ago there was an advice in Apple's documentation:
> Don't specify a dictionary as the value of alert if the dictionary only has the body property

And Pushy's ApnsPayloadBuilder does exactly that -- it collapses `alert:{body:"text"}` into `alert:"text"`.
But now [the page containing the advice](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW10) is no longer available and [new version of documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW2) says the opposite:
> The **preferred value** for this key is a **dictionary**, the keys for which are listed in Table 9-2.

So I would like to have some kind of "switch" to enable/disable auto-collapsing of the `alert` dictionary into a string.

**Comment by jchambers** [comment]
> the new version of documentation says the opposite

Good catch. I hadn't noticed that.

> So I would like to have some kind of "switch" to enable/disable auto-collapsing of the alert dictionary into a string.

Why a switch? Why not just always use a dictionary?

**Comment by jchambers** [comment]
@yoorick Took a shot at this in #391. Please let me know if you have any objections.

**Comment by yoorick** [comment]
@jchambers Sorry for late answer, I've been on weekends.
> Why a switch? Why not just always use a dictionary?
A dictionary is a preferred way, but the docs still allow it to be a string.

Also, our iOS developers say that older versions of our mobile app, rely on the alert to be a string. These versions are not going to be updated, since they are for iOS 7 & 8. And it is still too early to put them out of service, since the number of active users.
There might be other users of your lib that are not prepared to fully switch to dictionary yet.

So my opinion is that a switch is good as "transitional" step before fully eliminate the alert as a string. (You could mark old behavior as deprecated and discourage its use).

**Comment by jchambers** [comment]
Ah—I forgot that clients need to work with the dictionary directly sometimes. I added a `setPreferStringRepresentationForAlerts` method to #391.

**Comment by yoorick** [comment]
Looks good to me.
Thank you!
