### ISSUE TITLE
Drop support for TLS-based client authentication

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#398]
We want v0.9 to be a transitional release that supports both "old-style" TLS-based client authentication and the newer token authentication system. After that, though, we can simplify the client (and also the docs, which will make life easier for end users) and add some new features if we drop support for TLS authentication.

**Comment by l3ender** [comment]
I'm curious about the move to drop TLS support. Is Apple also deprecating certificate based notifications?

**Comment by jchambers** [comment]
> Is Apple also deprecating certificate based notifications?

I'm not aware of any such plans.

Removing support for TLS-based authentication simplifies things internally quite a bit (net change is something like -1,000 lines in #400) and paves the way for meaningful connection pooling; since token-based authentication allows one client to work with many topics, we can move to a model where everybody—regardless of the scale of their operation—only needs a single `ApnsClient`, but can allocate more threads to a client for more throughput.

Incidentally, I *did* merge #400 earlier today, so I'll close this issue.
