### ISSUE TITLE
not find NoopMetricsListener

### ISSUE THREAD

**Issue by puyide** [relayrides/pushy#405]
Hi I  use Maven, add Pushy to project :

<dependency>
    <groupId>com.relayrides</groupId>
    <artifactId>pushy</artifactId>
    <version>0.9</version>
</dependency>

but  not find NoopMetricsListener class why?

**Comment by jchambers** [comment]
I don't know. This works fine for me, and seems to be fine for everybody else. The file is included in the Pushy jar file. It seems very unlikely to me that this is a bug in Pushy itself.

Can you provide more information about what you were doing (or trying to do) when this happened? What, exactly, is complaining about the missing class? Does it happen at compile time or runtime?

**Comment by jchambers** [comment]
Closing this issue due to lack of information or reports of similar problems elsewhere. @puyide if you find an opportunity to provide more information about how you were able to produce this problem, please post here and we'll revisit the issue.
