### ISSUE TITLE
Javadoc for buildWithDefaultMaximumLength - wrong default size

### ISSUE THREAD

**Issue by l3ender** [relayrides/pushy#406]
The javadoc for `buildWithDefaultMaximumLength()` mentions the default maximum as 2048 bytes when both the [Apple doc](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html) and the [constant itself](https://github.com/relayrides/pushy/blob/v0.9/pushy/src/main/java/com/relayrides/pushy/apns/util/ApnsPayloadBuilder.java#L95) specify **4096** bytes.

Minor? Yes...but it threw me a loop until I looked at the source :)

**Comment by jchambers** [comment]
Oops—good catch.

**Comment by jchambers** [comment]
Fixed in a8ac2f0.
