### ISSUE TITLE
Native SSL provider not available; will use JDK SSL provider

### ISSUE THREAD

**Issue by binauyang** [relayrides/pushy#415]
I am a rookie using pushy, and it works fine when I just write a java demo and package it to a jar, but when I package it to a war and use Tomcat to start it up, somethings wrong happens:

my pom.xml:
```
<dependency>
        <groupId>com.relayrides</groupId>
        <artifactId>pushy</artifactId>
        <version>0.8.2</version>
</dependency>
<dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-tcnative-boringssl-static</artifactId>
        <version>1.1.33.Fork24</version>
</dependency>
```

and I add some logs in my code:
```
System.out.println("OpenSSL available? " + OpenSsl.isAvailable());
System.out.println("ALPN supported?    " + OpenSsl.isAlpnSupported());

if (OpenSsl.unavailabilityCause() != null) {
    System.out.println("Reason for unavailability:");
    OpenSsl.unavailabilityCause().printStackTrace(System.out);
}
```

and it prints:
```
OpenSSL available? false
ALPN supported? false
Reason for unavailablity: no netty-tcnative in java.library.path
Native SSL provider not available; will use JDK SSL provider.
```

Could you please help me to solve this problem? Thanks a lot.

**Comment by jchambers** [comment]
Please see the ["Tomcat-specific issues" section of the "Using Pushy in an application container" wiki page](https://github.com/relayrides/pushy/wiki/Using-Pushy-in-an-application-container#tomcat-specific-issues). Tomcat's `tcnative` implementation currently conflicts with Netty's `netty-tcnative`, though we expect the situation to change in Netty 4.1.8.
