### ISSUE TITLE
Deploy 0.9.1 to maven repo

### ISSUE THREAD

**Issue by ostronom** [relayrides/pushy#416]
The latest version of pushy in maven is 0.9 (http://repo1.maven.org/maven2/com/relayrides/pushy/), but the doc says to use 0.9.1 :)

**Comment by jchambers** [comment]
Hm. Something screwy has happened here. We'll look into it.

**Comment by jchambers** [comment]
I believe the issue has been resolved and the 0.9.1 artifacts should be in the central repository within the hour.

**Comment by jchambers** [comment]
Looks like something is *still* screwy. Will get in touch with upstream support to see what's going on here.

**Comment by jchambers** [comment]
The upstream issue, for spectators: https://issues.sonatype.org/browse/MVNCENTRAL-1540

**Comment by jchambers** [comment]
…and we're good. The artifacts are now available in Maven Central.
