### ISSUE TITLE
MockApnsServer changes

### ISSUE THREAD

**Issue by ebabani** [relayrides/pushy#417]
Hi,

For our integration tests we've made some changes on the MockApnsServer to add the ability to see what pushes have been received, and record the topics/payloads of those pushes.

Do you have your own plans regarding something similar in the future, or would you be open to a PR?

**Comment by kdubb** [comment]
This would be great... we resorted to a Node server that mocked the APNS server that essentially does the exact same thing.  Reusing the `MockApnsServer` would be helpful.

**Comment by jchambers** [comment]
Can you elaborate a bit on the changes that you made? My inclination would be to add something like this:

```java
public interface MockApnsServerNotificationListener {
    void handleAcceptedNotification(ApnsPushNotification notification);
    void handleRejectedNotification(ApnsPushNotification notification, ErrorReason errorReason);
}
```

Seem legit? In any case, I'm kiiiiiinda taking a wrecking ball to `MockApnsServer` over in #404, so it might be a good idea to hold off on a pull request until that's a little less… wreck-y.

**Comment by ebabani** [comment]
That's exactly the same approach I took. Add a notification listener, and record accepted/rejected notifications. 

The ApnsPushNotification object contains the http2 headers and payload so that the listener implementations can check whatever they wants.

Thanks for the heads up on #404 , I'll hold off until that's in.

**Comment by jchambers** [comment]
I don't want to leave this hanging, but to be clear, #404 is temporarily on hold until we can get some clarification from Apple. Please see https://github.com/relayrides/pushy/issues/399#issuecomment-282306488 for additional discussion.

**Comment by jchambers** [comment]
@ebabani With apologies for the long delay, I think the state of the server in `master` is pretty stable for the moment. We'd be thrilled to receive a pull request at your convenience!

**Comment by jchambers** [comment]
For folks interested in this feature: do you mostly care that notifications made it to the server, or do you need something that runs notifications through the full validation gauntlet (verifying topics and auth tokens and such)?

One way I can think of to handle this is to have something like a `PushNotificationHandler` interface. Pushy could supply a `ValidatingPushNotificationHandler` that does all the checks we can derive from the APNs docs, and then end users could write something like a `JustTellMeIfAPushNotificationArrivedHandler` as needed. Things get a little more complicated if you folks need something that does all of the validation, but is easy to subclass. It's absolutely doable, but I'm just trying to strike the right balance of complexity and usefulness.

Thanks!

**Comment by jchambers** [comment]
I took a shot at this in #537. What do you folks think?

**Comment by jchambers** [comment]
#537 is merged, which I think resolves this issue. Please let us know if you have further feedback!
