### ISSUE TITLE
java.lang.NoSuchMethodError with ApnsClientBuilder.setClientCredentials on 0.9.1 built with Maven

### ISSUE THREAD

**Issue by Aquilosion** [relayrides/pushy#423]
Attempting to call `ApnsClientBuilder.setClientCredentials` results in a `NoSuchMethodError` when built using Maven.

Sample Maven dependency:

	<dependency>
		<groupId>com.relayrides</groupId>
		<artifactId>pushy</artifactId>
		<version>0.9.1</version>
	</dependency>

**Comment by jchambers** [comment]
As discussed on the mailing list, this happened because I goofed and released from the wrong branch :|

Will put out a new release as soon as possible, but that might be ~12 hours from now. I'm sincerely sorry for the trouble.

**Comment by Areii** [comment]
after 3 days.....

**Comment by rolanddb** [comment]
Running into this issue as well. A new release would be appreciated.

**Comment by marklocker** [comment]
Any news on the new release? I'm also waiting for it :)

**Comment by jchambers** [comment]
v0.9.2 has been released and is on its way to Maven Central.
