### ISSUE TITLE
com.relayrides.pushy.apns.ClientNotConnectedException in Jboss Fuse OSGI

### ISSUE THREAD

**Issue by rajibm2005** [relayrides/pushy#426]
Hi,

I'm trying to run the example code given in Pushy's homepage in Jboss Fuse 6.2.1 OSGI container and I'm getting this exception. 

I'm using a proxy to connect.  

It happens at:final Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = apnsClient.sendNotification(pushNotification);

Everything works fine outside OSGI. 

It seems in OSGI, we must use alpn-boot, otherwise io.netty.handler.sslJdkAlpnApplicationProtocolNegotiator fails to initialise. 

Correct version of alpn-boot is on boot class path. 

Does anybody know what might cause this ? 

Thanks
Rajib

**Comment by rajibm2005** [comment]
On further debugging, I found the issue is: 

IllegalStateException:Channel closed before HTTP/2 preface completed.

I'm using JWT and everything works fine outside OSGI container.

**Comment by jchambers** [comment]
@rajibm2005 I see you've already [posted about this on the mailing list](https://groups.google.com/d/msg/pushy-apns/4LV98ADy4RE/8F1gJdq7CQAJ), so let's move the conversation there.
