### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [relayrides/pushy#427]
I m not sure to understand correctly
I want use push http2 api in the browser (https://developer.mozilla.org/it/docs/Web/API/Push_API).
i wont use google service for it but i want implement my service in my java server.

does pushy permit it ?

**Comment by jchambers** [comment]
Pushy is a library for sending APNs push notifications. You appear to be looking for something to send browser "Push API" notifications. Regrettably, Pushy is completely unrelated to what you need.
