### ISSUE TITLE
NPE in ApnsPayloadBuilder.setLocalizedAlertMessage

### ISSUE THREAD

**Issue by Shohou** [relayrides/pushy#428]
Javadoc for ApnsPayloadBuilder.setLocalizedAlertMessage says:

> @param alertArguments arguments to populate placeholders in the localized alert string; may be {@code null}

But method will fail with NPE if null is passed as alertArgument in this row
`this.localizedAlertArguments = alertArguments.length > 0 ? alertArguments : null;`

Similar NPE will happen in other methods receiving vararg argument

**Comment by jchambers** [comment]
This has been fixed and will go out with v0.9.3. Thanks again!
