### ISSUE TITLE
Migrate to Netty 5

### ISSUE THREAD

**Issue by rajibm2005** [relayrides/pushy#431]
I was able to successfully run Pushy in OSGI container using Netty 4.1.9.Final-SNAPSHOT version. It does not work in earlier versions of Netty due a known Netty incompatibility with OSGI's class loading. 

But the issue is Netty 4.1.9.Final-SNAPSHOT is not released yet and there's no due date. 

Since Netty 5 has a different API, Pushy does not build with Netty 5. 

Is there any plan to migrate Pushy to Netty 5 ?

**Comment by sunng87** [comment]
IIRC, Netty 5 is dropped.

**Comment by jchambers** [comment]
> Netty 5 is dropped.

This is correct. I'm going to close this issue because there's nothing we can do on our end to change the situation. @rajibm2005 the best course of action for you, I think, is to continue to wait for Netty 4.1.9.
