### ISSUE TITLE
Internalize reconnection mechanics

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#455]
Right now, we ask users to deal with temporarily-dropped connections by waiting on a reconnection future. This drives complexity internally and also for callers. The Pushy world would probably be a better place if we could hide these details internally.

One weakness with this approach is that callers could attempt to send a notification that will never succeed if the client never reconnects. As discussed in #444, though, it might make sense to add a per-notification timeout.

Clearly, we have some details to iron out here, but I think leaving our reconnection laundry out in the open is unnecessary.

**Comment by zhouxiaohai** [comment]
A lot of push messages are lost every time you reconnect!
