### ISSUE TITLE
Add per-notification timeouts

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#466]
As a follow-up to #433, we should consider implementing per-notification timeouts.

**Comment by dfroberts2** [comment]
+1

**Comment by jchambers** [comment]
After lots of recent discussion, I'm pretty convinced this is something we should _not_ do. In basically all cases, it's a workaround for another bug elsewhere in Pushy. The right thing to do seems like it's pretty much always to just fix the bug rather than adding a workaround.

I'm going to close this for now, but welcome feedback and arguments that this provides non-workaround value.

Thanks!
