### ISSUE TITLE
 Broken network after the resumption of Apple APNs development documents do not receive the last message?

### ISSUE THREAD

**Issue by zhouxiaohai** [relayrides/pushy#471]
With Pushy's friends:
I now use two frames (http / apns4j) and (http2 / pushy). When the phone off the network, I use apns4j to send this phone to push, after a period of time I manually restore the phone to this network can accept the last push. But I use pushy to do the same operation and so my mobile phone recovery network is not received push, provided that I have been informed in the listener to push the APNs server success.
Do you have any friends who have met? Or my Pushy framework is useless where the lack of configuration?

**Comment by binauyang** [comment]
Have you set invalidationTime in ApnsNotification's construct method?

**Comment by zhouxiaohai** [comment]
@binauyang:
No settings, I'm the default operator！
pingyin:wo mei you she zhi,yong de shi mo ren cao zuo!zhei li zen me she zhi?

**Comment by zhouxiaohai** [comment]
@binauyang:
Thank you for your warning. It has been successful!
