### ISSUE TITLE
NPE on ApnsClient connect

### ISSUE THREAD

**Issue by maelaouane** [relayrides/pushy#474]
Hi Jon,

Firstof all, thank you for your efforts and support. 

I started using pushy 0.9.2 a couple of months ago with alpn-boot and netty 4.1.8 under jdk version 1.8.0_112. I managed to start my APNS service on a lab server but not on another one. I have this NPE when trying to connect to APNS server :  

```
Exception: java.lang.NullPointerException
 java.lang.NullPointerException
 	at com.relayrides.pushy.apns.ApnsClient.connect(ApnsClient.java:456)
 	at com.relayrides.pushy.apns.ApnsClient.connect(ApnsClient.java:418)
 	at com.centile.apns.server.APNSClientConnector.<init>(APNSClientConnector.java:57)
 	at com.centile.apns.server.APNSClientConnector.prepareClient(APNSClientConnector.java:95)
```

Which occurs in this lines of the ApnsClient class : 

```java
final ChannelFuture connectFuture = this.bootstrap.connect(host, port);
this.connectionReadyPromise = connectFuture.channel().newPromise();
```

I use token based authentication using a p8 file. 

Is it a bug ? Or a normal behaviour in case the connection cannot be established ? 

Note that toString of connectFuture returns : DefaultChannelPromise@1ba3ad0(failure: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel)
and the connectFuture.channel() is thus null

Thanks !

**Comment by jchambers** [comment]
Two things:

1. Please note that we effectively "revoked" v0.9.2 due to a release error. If you must use the 0.9 series, we strongly recommend 0.9.3; otherwise, we recommend using 0.10.
2. While it sounds like we can do better with some error handling in this specific case, the problem seems to be that you're missing dependencies (i.e. Netty). While certainly not desirable, that does *not* appear to be a bug with Pushy itself.

**Comment by maelaouane** [comment]
Hi Jon, 

Thank you for your help and your reply. I will proceed to the upgrade of Pushy to the latest version. 

For the Netty issue, we managed to solve the issue by excluding netty-codec-http2 and netty-handler-proxy from the maven dependency using pushy. These 4.1.6 libraries were conflicting with the netty-all 4.1.8.Final used in our project. 

Best,
Amine
