### ISSUE TITLE
Lost responses on reconnection

### ISSUE THREAD

**Issue by janzar** [relayrides/pushy#480]
Seems that there is another problem with lost responses. It happens in our production environment about once per week. Monitoring system shows that couple thousand notifications do not receive response in short time and we manually cancel them (Future<PushNotificationResponse>) after some large timeout (it would be nice to have such a feature in pushy itself so caller simply gets some timeout or cancellation exception). I have limited access to production servers so can’t tell much details but it looks like some connection issues. Have tried to reproduce it locally, and seems that have found one case. If run tcpkill net 17.188.0.0/16 to simulate problems with network, in log I see how connections are dropped and then reconnection process starts. When then cancel tcpkill, everything restores and normal delivery process continues, but responses to some connections are missed - GenericFutureListener::operationComplete. is not called. From debug it seems that ApnsClientHandler::close is not called and therefore responsePromises are lost on channel close. May be responsePromises cleanup could be moved to some other place, seems that ApnsClientHandler::channelInactive would be fine.

Thanks,
Z.

**Comment by janzar** [comment]
Does anybody investigated how often these reconnects happens. And how much time does it takes? And what is the reason for them? Looks like they happen more than once a week. We have seen it today and the day before yesterday. From logs seems that time taken by client.getReconnectionFuture().await() could be greater than minute. Reconnections happens because Apple periodically changes address of their push services?

Thanks,
Z.

**Comment by jchambers** [comment]
@janzar This was fixed in #481. I'd encourage you to move discussion about upstream server behavior to the mailing list.

**Comment by janzar** [comment]
Great, thanks. Could you please give url to the mailing list?

**Comment by jchambers** [comment]
The mailing list is at https://groups.google.com/d/forum/pushy-apns.
