### ISSUE TITLE
A certain period of time, network differential, Pushy constantly re connect APNs server, resulting in paralysis of the company network

### ISSUE THREAD

**Issue by zhouxiaohai** [relayrides/pushy#489]
![image](https://user-images.githubusercontent.com/17846308/27668428-9f74f71e-5cb3-11e7-8e2a-b33908d42465.png)

Recently, frequently encountered bad network situation, Pushy constantly reconnection APNs server, a few seconds to produce more than 10000 connections. Has caused the company network are dragged down paralysis?

**Comment by jchambers** [comment]
This sounds like it's related to other connection difficulties that have been reported recently, but we'll need some more information to be able to debug this effectively. Most importantly, how many `ApnsClient`s do you have running at the same time? Just one?

**Comment by zhouxiaohai** [comment]
Two ApnsClient!

**Comment by zhouxiaohai** [comment]
I have not been found in the weak network is how to issue so many connections, my project is based on a single enterprise deployment so use a certificate, so I worry about the APN server to block my certificate? I am worried about every day now!

**Comment by zhouxiaohai** [comment]
Guess the conclusion: When the ApnsClient build is completed after we stored in a memory Map, some time ApnsClient itself cut off so Map can not find the ApnsClient object. And ApncClient will automatically re-connect this time there is a free state of the ApnsClient?

**Comment by jchambers** [comment]
> I worry about the APN server to block my certificate?

I have never heard of that actually happening.

> And ApncClient will automatically re-connect this time there is a free state of the ApnsClient?

I'm not completely certain I understand your hypothesis, but I do expect this problem to be solved in #492.
