### ISSUE TITLE
Mock APNS Server as a separate maven artifact

### ISSUE THREAD

**Issue by saumitrabhave** [relayrides/pushy#494]
Guys, great job writing this awesome library...

Not sure if this has been discussed previously, but it would be really great if the MockAPNS server can be released as a separate maven artifact, 
1. It might reduce some classes from the runtime.
2. It will be helpful for people using some other ways/technologies to send APNS pushes, but still want to use pushy's MockServer in their integration tests.
Thanks

**Comment by jchambers** [comment]
Even though I didn't explicitly call it out, this will definitely happen as part of #459. Thanks for the suggestion!

**Comment by jchambers** [comment]
I think we're going to have to defer on this for now; the main motivation for moving the mock server into its own module is developer convenience, but it turns out that's also where most of the costs lie. Let's keep looking for opportunities to make this happen, though.
