### ISSUE TITLE
ApnsClientHandler.onStreamClosed bug

### ISSUE THREAD

**Issue by Tielancy** [relayrides/pushy#496]
In version 0.10.1, class ApnsClientHandler has implemented the interface Http2Connection.Listener. As a listener, does ApnsClientHandler has been added into Http2Connection  through addListener method？if not, some methods will never be executed(such as: ApnsClientHandler.onStreamClosed).
And I have met this problem: when disconnect ApnsClient, the callback added by me not be executed because of ApnsClientHandler.onStreamClosed method not be executed.
so, if codes write like follow,this problem  disappears:
```
        @Override
        public ApnsClientHandler build(final Http2ConnectionDecoder decoder, final Http2ConnectionEncoder encoder, final Http2Settings initialSettings) {
            Objects.requireNonNull(this.authority(), "Authority must be set before building an ApnsClientHandler.");

            final ApnsClientHandler handler = new ApnsClientHandler(decoder, encoder, initialSettings, this.authority(), this.idlePingIntervalMillis());
            this.frameListener(handler);
            //this line added by me.
            decoder.connection().addListener(handler);
            return handler;
        }
```

**Comment by jchambers** [comment]
Ugh… I think I know what happened here. I had added some hacky bonus logic (like messing with token timestamps) to test this against the production APNs environment; I must have reverted the `addListener` call when I took that out. I'm afraid it'll be a few days before I can put out a new release, but the fix should be trivial.

Thanks for catching this!

**Comment by justinpermar** [comment]
@jchambers , is the change to fix this the one-liner shown above? If so, is there any reason for me not to check out the 0.10.1 release, apply this patch, and re-build a version for my own use?

**Comment by jchambers** [comment]
@justinpermar Pushy v0.10.2 has been released; there should be no need to build your own.
