### ISSUE TITLE
Didn't receive response for some notifications

### ISSUE THREAD

**Issue by chaharvi** [relayrides/pushy#506]
Hi,

We see one issue where we are not getting response (Accepted or Rejected) for some of the notifications.
We sent 6 notifications but received response for 2 notifications only. Payload content is same in these notifications but we were sending it to different devices.
We enabled pushy logs and we see 'ExpiredProviderToken' error in pushy logs. Pushy generates new authentication tokens whenever the previous token expires, but we didn't receive response for some notifications and notifications not sent to device also.

Please help to resolve this issue and confirm how we can handle this.

We are using pushy-0.9.2.

Thanks,
Vikas

**Comment by jchambers** [comment]
This appears to be a result of #496. We expect to have a fix out shortly. I'll close this issue as a duplicate in the meantime.

**Comment by chaharvi** [comment]
#496 raised against 0.10.1 while we are using pushy 0.9.2. 
Do we still think its duplicate?

Is there any workaround which can be implemented in our code?

**Comment by jchambers** [comment]
> Do we still think its duplicate?

Yes.

> Is there any workaround which can be implemented in our code?

You can fall back to certificate-based authentication, which is not affected by this problem. Again, we expect a fix to be out shortly.

**Comment by chaharvi** [comment]
Thanks Jon for confirmation.
Do we have plan to release 0.9 version with this fix?

**Comment by jchambers** [comment]
> Do we have plan to release 0.9 version with this fix?

No. It will go into 10.2.
