### ISSUE TITLE
MDM push notifications

### ISSUE THREAD

**Issue by ricardopt** [relayrides/pushy#509]
Hi,

I'm trying to implement MDM functionalities in an app. But for some reason, I'm receiving `DeviceTokenNotForTopic`.

The topic is something like `com.apple.mgmt.External.{uuid}` and is correct and also the token. Let's go to the code.

```
try {
            Future<Void> connectFuture = apnsClient.connect(ApnsClient.PRODUCTION_APNS_HOST);
            connectFuture.await();
            String token = decodeTokenFromBase64(mdm.getToken());
            SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(token, configurationFacade.getString(Constants.MDM_TOPIC), createPayload(mdm.getPushMagic()));
            Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = apnsClient.sendNotification(pushNotification);
            PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse = sendNotificationFuture.get();
            if (pushNotificationResponse.isAccepted()) {
                LOGGER.info("environment:{}|deviceId:{}|MDM Push notification accepted by APNs gateway.", ApnsClient.PRODUCTION_APNS_HOST, device.getId());
            } else {
                LOGGER.info("environment:{}|deviceId:{}|MDM Notification rejected by the APNs gateway: {}", ApnsClient.PRODUCTION_APNS_HOST, device.getId(), pushNotificationResponse.getRejectionReason());
                if (pushNotificationResponse.getTokenInvalidationTimestamp() != null) {
                    LOGGER.info("environment:{}|deviceId:{}|The mdm token is invalid as of: {}", ApnsClient.PRODUCTION_APNS_HOST, device.getId(), pushNotificationResponse.getTokenInvalidationTimestamp());
                }
            }
            LOGGER.debug("userId:{}|deviceId:{}|wake up mdm notification sent", user.getId(), device.getId());
        } catch (InterruptedException | ExecutionException ex) {
            LOGGER.warn("environment:{}|deviceId:{}|sending mdm push notification failed. ", configurationFacade.getString(Constants.MDM_HOST), device.getId(), ex.getMessage());
        }
```
**Create Payload**

```
private String createPayload(String pushMagic) {
        ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
        payloadBuilder.addCustomProperty("mdm", pushMagic);
        return payloadBuilder.buildWithDefaultMaximumLength();
    }
```

**Decode Token**
```
private String decodeTokenFromBase64(String tokenFromPayload) {
        byte[] bytes = Base64.decodeBase64(tokenFromPayload.getBytes());
        return Hex.encodeHexString(bytes);
    }
```

**Push Notification sent:**
SimpleApnsPushNotification 

```
[token=xxcc33xxxxxfe46bxxxxx225c70c8xxxxxfc42065c1cxxxxx18cfc32d8xxxxx, payload={"aps":{},"mdm":"XXXXFDB1-XXXX-42F8-XXXX-3078E66EXXXX"}, invalidationTime=null, priority=IMMEDIATE, topic=com.apple.mgmt.External.7cfxxxxe-661e-xxxx-b5xx-xxxx80ddxxxx, apns-collapse-id=null]
```

**Error**
environment:api.push.apple.com|deviceId:41|MDM Notification rejected by the APNs gateway: DeviceTokenNotForTopic

Can someone explain me what I'm doing wrong? Pushy supports MDM?

NOTE: Before using pushy I used the notnoop and it worked perfectly, I'm planning on switching to pushy but this issue is blocking me.

**EDIT:** After some reading in the [MDM documentation](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/MobileDeviceManagementProtocolRef/3-MDM_Protocol/MDM_Protocol.html#//apple_ref/doc/uid/TP40017387-CH3-SW2) I found this: 

> In place of PushMagicValue above, substitute the actual PushMagic string that the device sends to the MDM server in the TokenUpdate message. That should be the whole message. There should not be an aps key. (The aps key is used only for third-party app push notifications.)
I printed the push notification and the aps went to the APNs with empty value "aps":{} 
The problem can arise from this? How can I remove the aps?

**EDIT2:** I've made some changes in the Pushy client to not includethe aps on the payload and didn't work either. The payload now follows this structure `{"mdm": "UDID"}`
I've made a Clone and created a branch, if you need I can make a pull request for you to test. I must warn you that the code was a quick fix and not the final version I would like to see to solve this case.

Thanks in advance,

**Comment by ricardopt** [comment]
I've solved the issue. Will do a pull request...

**Comment by jchambers** [comment]
> I want to make a pull request with the fix, but I don't have permissions can someone handle that?

For posterity, this was answered [on the mailing list](https://groups.google.com/d/msg/pushy-apns/4JEP3Bg-8Zs/szufE-9xAQAJ).
