### ISSUE TITLE
Documentation Clarification: Multithreaded use of ApnsClients

### ISSUE THREAD

**Issue by mohamedhafez** [relayrides/pushy#520]
So as of version 0.11, after an `ApnsClient` is created, can it be shared amongst several threads, each of which is calling `sendNotification` simultaneously? 

If so, then if an `ApnsClient` is built with a large enough connection pool, then there is no longer any need to have more than one ApnsClient for each app you are trying to send push notifications to, is that correct?

I'd be happy to send in a pull request to update the docs to reflect these points, just wanted to make sure I'm correct first:)

**Comment by jchambers** [comment]
> after an `ApnsClient` is created, can it be shared amongst several threads, each of which is calling `sendNotification` simultaneously?

Correct.

> if an ApnsClient is built with a large enough connection pool, then there is no longer any need to have more than one ApnsClient for each app you are trying to send push notifications to, is that correct?

Mostly correct! I'd hesitate to frame pool size as a limiting factor; you could use a client with a singleton pool with a bazillion threads and it would be slow (or at least not faster overall), but the fundamental guarantees would not change. But, yeah, big picture: you should only ever need one client per certificate/signing key at this point, and putting more connections in the pool will—to a point—help with overall throughput in high-concurrency use cases.

Also on my to-do list: write a wiki page explaining the tradeoffs around pool size, event loop group size, available cores, etc..

> I'd be happy to send in a pull request to update the docs to reflect these points, just wanted to make sure I'm correct first:)

Thank you on all counts! Looking forward to it!

**Comment by mohamedhafez** [comment]
Awesome, I created a pull request to add the info from your answer to the README. Looking forward to the wiki article, that'll be really helpful. Is there a quick rule of thumb for how many threads the eventloopgroup should have based on the available cores / number of connections for the best throughput?

**Comment by jchambers** [comment]
Well, one connection will never use more than one thread in the event loop group, so it never makes sense to have an event loop group with more threads than you'll ever have connections. In other words, if you have a single `ApnsClient` with two concurrent connections and an `EventLoopGroup` with 8 threads, 6 of those threads will be sitting idle all the time.

As for how many threads, I'd say a very rough ballpark is one or two per core (again, assuming you have at least that many connections). Beyond that, it's really a matter of whether you're running out of CPU time or network throughput first.
