### ISSUE TITLE
Cannot send VoIP pn

### ISSUE THREAD

**Issue by alqa-dash** [relayrides/pushy#522]
Hi! 
I've been trying to send VoIP push notification using team id/key id but just got "Notification rejected by the APNs gateway: TopicDisallowed" in reply. Unfortunately I could not find any mention upon how to correctly compose payload (voip) for silent push notification. Help me please with my problem. 

PS I'm able to send voip pn with houston (ruby command line tool) using pem but I do need to send pn through java backend.

**Comment by alqa-dash** [comment]
upd. just found the proper way - sorry for disturbance

**Comment by jchambers** [comment]
For the benefit of others who may run into this problem, what was wrong? What did you do to fix it?

**Comment by alqa-dash** [comment]
Sure. It was not clear for me how to prepare voip payload for silent push notification. I've never dealt before with apn services and yesterday I discover that to be able to successfully deliver voip pn one have to add "voip" suffix to bundle name in the SimpleApnsPushNotification's topic parameter. 
E.g. if bundle name is "com.apple.facetime" so the final topic should be "com.apple.facetime.voip". Of course contentAvailable must be set to true.

PS Thanks for your great product!

**Comment by casevictor** [comment]
Hey @alqa-dash what did use as `.setClientCredentials()` the VOIP Service Cerificate or the APNS Push Service, and for the `SimpleApnsPushNotification` deviceToken the value from `PKPushCredentials` or the simple device token? 

[]`s

**Comment by alqa-dash** [comment]
Hi, sorry for latence. I didn't set setClientCredentials - it is unnecessary. For VoIP push notification I first register only VoIP pn and use exactly this token.

**Comment by casevictor** [comment]
@alqa-dash thanks wow.. then you do not import the VoIP certificate on the library? 😮  
Could you share a snippet of your code please?

**Comment by alqa-dash** [comment]
Sure. Actually it was pretty straightforward. My code snippet below.

try {
            final ApnsClient apnsClient = new ApnsClientBuilder()
                    .setSigningKey(ApnsSigningKey.loadFromPkcs8File(new File(p8File),
                            // team id. Constant for one p8 file
                            "XXXXXXXXX",
                            // key id. Constant for one p8 file
                            "YYYYYYYYY"))
                    // push notification server. Different for development and production
                    // Development server: api.development.push.apple.com
                    // Production server: api.push.apple.com
                    .setApnsServer("api.development.push.apple.com")
                    .build();

            final SimpleApnsPushNotification pushNotification;

            {
                final ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
                payloadBuilder.setContentAvailable(true);
                payloadBuilder.addCustomProperty("content-available", 1);

                final String payload = payloadBuilder.buildWithDefaultMaximumLength();

                // renewable token from each mobile device. Must be uploaded from mobile device and renewed if needed/
                final String token = TokenUtil.sanitizeTokenString("voiptoken");

                // mobile application bundle name. Equal for every ios client. May be changed.
                pushNotification = new SimpleApnsPushNotification(token, "bundle-name.voip", payload);


                final Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture =
                        apnsClient.sendNotification(pushNotification);

                final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse =
                        sendNotificationFuture.get();

                if (pushNotificationResponse.isAccepted()) {
                    System.out.println("Push notification accepted by APNs gateway.");
                } else {
                    System.out.println("Notification rejected by the APNs gateway: " +
                            pushNotificationResponse.getRejectionReason());

                    if (pushNotificationResponse.getTokenInvalidationTimestamp() != null) {
                        System.out.println("\t…and the token is invalid as of " +
                                pushNotificationResponse.getTokenInvalidationTimestamp());
                    }
                }

                final Future<Void> closeFuture = apnsClient.close();
                closeFuture.await();
            }

        } catch (IOException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (InvalidKeyException e) {
            e.printStackTrace();
        } catch (final ExecutionException e) {
            System.err.println("Failed to send push notification.");
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();

**Comment by casevictor** [comment]
Thanks again :)
Uhmmm ok, then the Auth Key (p8) is also valid for VOIP Pushes..
Apple needs to document this kind of stuff 🤔 

Another question, I really need to duplicate the `content-available`?
```
payloadBuilder.setContentAvailable(true);
payloadBuilder.addCustomProperty("content-available", 1);
```

**Comment by alqa-dash** [comment]
How to use p8 certificate is well described here: https://www.codementor.io/ramachandrangunasekeran/send-push-notifications-to-ios-devices-via-p8-file-xcode-8-and-swift-3-8wpot2yn9

According to content, I think second line is extra and I occasionally left it in code trying to send voip pn.

**Comment by baonq-me** [comment]
Thank you for pointing out this @alqa-dash
