### ISSUE TITLE
PushNotificationFuture not available on last maven repository

### ISSUE THREAD

**Issue by fjginermontagud** [relayrides/pushy#543]
On Pushy documentation you write about how to use PushNotificationFuture to handle events and wait to APNS server feedback, but in last version of Pushy (0.11.3) it's not available, but present on master branch. It's possible to have a new version including this functionality?

**Comment by jchambers** [comment]
I've set the default branch to the 0.11.3 release to avoid confusion until we release 0.12. We do not intend to alter the release schedule for 0.12. For a list of the remaining pull requests and issues for 0.12, please see the [v0.12 milestone](https://github.com/relayrides/pushy/milestone/26).

**Comment by fjginermontagud** [comment]
Ok! Thanks for the information. By the way, great job.
