### ISSUE TITLE
Pushy home page showing incorrect version info

### ISSUE THREAD

**Issue by lagrangian-mech** [relayrides/pushy#547]
I finally got around to realizing I wasn't clear enough/thorough enough in #532 . The problem isn't just the README.md file, but the fact that the version of the README.md that displays on the home page is wrong. You did fix the README.md file in that commit, but the home page is still showing the wrong thing.

Right now if you go to https://github.com/relayrides/pushy the home page text (incorrectly!) says that you should put 0.11.1 when declaring a dependency and that Pushy's dependencies are netty 4.1.14.Final and netty-tcnative 2.0.5.Final.

**Comment by jchambers** [comment]
I regret that it's taken so long to get to this, but it's now resolved (and Pushy 0.12 is making its way to Maven Central!). Thanks for the report!
