### ISSUE TITLE
Native ALPN support in Java9

### ISSUE THREAD

**Issue by humbled** [relayrides/pushy#550]
[JDK9](https://docs.oracle.com/javase/9/whatsnew/toc.htm#JSNEW-GUID-C23AFD78-C777-460B-8ACE-58BE5EA681F6) with [JEPS-244](http://openjdk.java.net/jeps/244) appears to have native ALPN support. We're looking to use pushy for a project and like to know if any external libraries are needed for ALPNs support now, or is JDK9 sufficient?

**Comment by jchambers** [comment]
I haven't tried it myself, but my understanding is that it should just work. To try it, you'd need to exclude `netty-tcnative` as a dependency and make sure you don't have `alpn-agent` as a `javaagent` or `alpn-boot` on your boot classpath.

Please let us know how it goes.
