### ISSUE TITLE
support  apns-id 

### ISSUE THREAD

**Issue by hzshlomi** [relayrides/pushy#559]
Hi,
First, thanks so much for the work you did.
To the issue: pls either allow adding the "apns-id" header sending, receiving or both.
There are (many?) cases where you get 200 OK and still the application does not show a push notification and this identifier could be used to further investigate what happened to the poor transaction.

According to "https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html" you could either send a UUID or get one in the response. if i had to choose only one i would take the APNS generated one but doing both may be the best.

This is rather small so I did take the lazy path asking you but if busy / too much trouble, I could do.

Shlomi

**Comment by jchambers** [comment]
This has come up before; we certainly acknowledge that there are cases where the APNs ID _could_ be helpful in theory. That said, I haven't yet been convinced by a _practical_ use case. I'm very open to being convinced, to be clear!

With that in mind my question to you: if you had a case where a notification was accepted by the APNs server but not ultimately delivered, what would you actually do with the APNs ID in that case? Is there something specific to do with it beyond filing a bug report with Apple?

**Comment by hzshlomi** [comment]
Hey,

First, if i'm not mistaken, you did ask them once (https://forums.developer.apple.com/thread/35582) about it and they did not answer (I did though).

Second - to answer the question - Not a whole lot but this is exactly the (valid IMHO) use case: being able to file an issue and then take it to Apple to bring the answers. You will never get answers without filing something to follow up on. So we have to have that ID to be able to even communicate a problem.

Third - think back on the fact they did not answer. If they had to answer what happened to every UUID successfully sent (200 OK) but never actually getting to the device that would cost them. So we just have to take care of our business and see from there.. I think..

Shlomi 




So it looks like they won't go the mile unless we try harder.

**Comment by jchambers** [comment]
I've opened #577 for discussion.

**Comment by hzshlomi** [comment]
Hi, replied at #577, all for it.
