### ISSUE TITLE
Restore no-op name resolver when using proxies

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#560]
I think I accidentally clobbered the no-op name resolver that we need for proxies when moving to the pooled channel model. To fix the issue, we just need to choose an address resolver for the channel factory's `Bootstrap` depending on whether or not we have a proxy handler factory.

**Comment by jchambers** [comment]
Fixed in 5d5c1c3.

**Comment by petrdvorak** [comment]
Wel... I know it is already closed, but this one really did surprise us with one of our customers. :D

**Comment by jchambers** [comment]
I offer my sincere apologies for the error. Can you confirm that this did, indeed, fixe the problem?

**Comment by petrdvorak** [comment]
@jchambers Yes, everything seems to work after we updated dependency to 0.12.0.
