### ISSUE TITLE
connection was not restored after goaway/shutdown

### ISSUE THREAD

**Issue by hzshlomi** [relayrides/pushy#567]
Just caught a case with v0.11.3 where c.t.p.a.ApnsClientHandler log says:
---
Received GOAWAY from APNs server: {"reason":"Shutdown"}
---
And the server failed each and every following request.

Looks like APNs server upgrade got the best of us.

Restarting process bailed me out.

**Comment by jchambers** [comment]
Huh. That seems like an upstream bug (if the server is shutting down, why wouldn't it close the connection?), but I guess we can special-case `Shutdown` and close the connection on our own if we see it.

**Comment by jchambers** [comment]
Reading this again, I believe this was a symptom of the problem fixed in #571. I think this should now be fixed in `master`, and we'll put out a new release with the fix shortly.
