### ISSUE TITLE
Plans for SDK9 support

### ISSUE THREAD

**Issue by Vicinitor** [relayrides/pushy#572]
Are there any near time plans for implementing Java 9 with Pushy eliminating the need for ALPN/Jetty?

**Comment by jchambers** [comment]
I haven't tested it myself, but I believe it should Just Work™. If you've tried it and learned that it doesn't work, please post a comment here and we'll reopen the issue to investigate. Otherwise, I don't believe there's anything we need to do.

**Comment by Vicinitor** [comment]
If I understand things correctly, Pushy is implemented using Netty and there is no Netty support for Java 9.
Hopefully I have misunderstood something,

**Comment by Vicinitor** [comment]
Hi again. I am getting confused after testing different solutions and mixing Netty and Jetty....
I'll investigate further why my tests dont run.

**Comment by Vicinitor** [comment]
Works! Sorry 'bout the confusion.

**Comment by jchambers** [comment]
Ah—glad to hear it! Are there any pitfalls or tricks we should know about/add to the wiki?

**Comment by Vicinitor** [comment]
Worked without any complications.
(Still haven't figured out why badge don't get updated, but I'm having the same problem with other sw as well so it might be somewhere else)

**Comment by flozano** [comment]
does it work with JDK9's own ALPN ?

**Comment by Vicinitor** [comment]
I just played with it a bit. Cannot upgrade the server to 9 yet, so dont really know.
