### ISSUE TITLE
Messages hangs after connection failure

### ISSUE THREAD

**Issue by anwerup** [relayrides/pushy#583]
When ApnsChannelFactory.create fails, for instance during a network outage, the caller only gets feedback on the listener of the first message and some random (assume it's timing base) number of subsequent messages. Most of the messages seem to be queued up an only processed at some later point when ApnsChannelFactory.create succeeds. Closing the ApnsClient seem to trigger failure callbacks on all of the outstanding messages.

I would expect to get a failure callback on the listeners of all messages sent during a network outage in a timely manner. The fact that they get queued up and don't seem to be processed until connections are reestablished creates three potential issues. 

- The queue size can get very large triggering OOM problems
- If reestablishing connection takes a long time messages can be out of date when they are delivered and make no sense to clients
- The lack of timely feedback on the failure by calling the listener makes it hard to catch and log failures in an appropriate manner

Is the behavior described in the first paragraph intended behavior or is this a bug?

Below is a partial test showing how to recreate the issue.

```java
@Test
public void sendMessagesSimple() throws InterruptedException, ExecutionException {

    SimpleApnsPushNotification pushNotification = createNotification(pushAddress, payload);

    for (int i = 0; i < 4; i++) {
        PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                pushNotificationFuture = apnsClient.sendNotification(pushNotification);

        pushNotificationFuture.addListener(
                (PushNotificationResponseListener<SimpleApnsPushNotification>) future -> {
                    System.out.println("Callback " + future);
                });
        Thread.sleep(1);
    }

    Thread.sleep(30000);
    System.out.println("\nWaited 30 sec. Shutting down\n");
    apnsClient.close();
}
```

This creates the following output when setting the APNS server name to an invalid server.

```
653  [main] INFO  com.turo.pushy.apns.SslUtil - Native SSL provider is available and supports ALPN; will use native provider. 
Callback handleConnectionCreationFailed
Callback handleWriteFailure
Callback PushNotificationPromise@7aa13b53(failure: io.netty.channel.ConnectTimeoutException: connection timed out: test.encap.no/85.221.67.15:9080)

Waited 30 sec. Shutting down

31051 [main] INFO  com.turo.pushy.apns.ApnsClient - Shutting down. 
Callback handleWriteFailure
Callback PushNotificationPromise@12a6f922(failure: java.lang.IllegalStateException: Channel pool has closed and no more channels may be acquired.)
Callback handleWriteFailure
Callback PushNotificationPromise@61ae3386(failure: java.lang.IllegalStateException: Channel pool has closed and no more channels may be acquired.)
Callback handleWriteFailure
Callback PushNotificationPromise@dbea44f(failure: java.lang.IllegalStateException: Channel pool has closed and no more channels may be acquired.)
```

**Comment by anwerup** [comment]
Created a test and a fix for the problem, see https://github.com/relayrides/pushy/pull/584

**Comment by jchambers** [comment]
Thanks for the report and for the tests. I'll review as soon as I can.

**Comment by dfroberts2** [comment]
+1

**Comment by jchambers** [comment]
Now that I've (finally) dug into this a bit more, I don't think this is a bug at all and is, indeed, the intended behavior. What you're actually seeing is exponential back-off behavior; if the pool fails to open a connection, it will wait for an exponentially-increasing period (up to a [maximum of 60 seconds](https://github.com/relayrides/pushy/blob/master/pushy/src/main/java/com/turo/pushy/apns/ApnsChannelFactory.java#L65)) before making another attempt at connecting. This is intended to avoid a number of adverse effects including burning CPU time and bombarding Apple's servers with bogus connections (this is mostly a problem when a client's TLS certificate has expired).

I don't think we actually want to change the behavior here, but there may be an opportunity to improve the documentation. My recommendation to you would be to use a [`Semaphore`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Semaphore.html) to control how many notifications you have "in flight" at a time (see the ["Flow control" section of the "Best practices" page on the wiki](https://github.com/relayrides/pushy/wiki/Best-practices#flow-control)).

I recognize that there's room to complain about this behavior (shouldn't Pushy do this automatically?), but I believe this is the best option. The two other approaches we've considered/used in the past are:

1. Don't do exponential back-off on connections at all. This caused (as mentioned earlier) unreasonable CPU load and bazillions of requests to Apple's servers whenever a client's TLS certificates expired. Exponential back-off is widely viewed as a best-practice.
2. Impose a limit on the number of outstanding notifications in Pushy itself. Our choices here are to either block on calls to `sendNotification`, which would violate the principles of asynchronous operation on which Pushy is built, or to fail notifications when the limit has been reached (which just caused a failure volcano for many users, and the only recourse was to just try again).

In all, I think this approach strikes the right balance between avoiding heinous problems and leaving reasonable solutions in users' control when there's no right-for-everybody solution we can bake into Pushy itself.

Please let me know if you disagree; I'll keep this issue open for a few days to collect feedback, but am now convinced it is not a bug.

Thanks!

**Comment by anwerup** [comment]
I'm sorry but what I'm seeing does not seem to be just back-off behavior. Given your description, I would expect to eventually get a notified that connection failed but with given the test below, I will never get notified of the second push failing. The test fails on the last assertion.

```    
    @Test
    public void testConsistentConnectionFailuresSlow() throws IOException, InterruptedException {
        final TestMetricsListener metricsListener = new TestMetricsListener();
        final ApnsClient client = this.buildInvalidAddressTlsAuthenticationClient(metricsListener);

        final SimpleApnsPushNotification pushNotification =
                new SimpleApnsPushNotification(DEVICE_TOKEN, TOPIC, PAYLOAD);

        final Future<PushNotificationResponse<SimpleApnsPushNotification>> firstFuture =
                client.sendNotification(pushNotification);

        final Future<PushNotificationResponse<SimpleApnsPushNotification>> secondFuture =
                client.sendNotification(pushNotification);

        long timeout = 61_000;
        assertTrue("Message processing should not take more then  " + timeout + " sec", firstFuture.await(timeout));
        assertTrue("Message processing should not take more then  " + timeout + " sec", secondFuture.await(timeout));
    }
```
How do you explain this?

**Comment by jchambers** [comment]
Interesting. I used a very slightly modified version of your test, and it passed. Your test does, indeed, fail. Let me dig more.

**Comment by jchambers** [comment]
I've investigated further and have, indeed, found a bug. I apologize for the incorrect diagnosis earlier. I think the core idea of the fix you proposed in #584 makes sense, but I don't think we want to make `ApnsClient` responsible for prodding `ApnsChannelPool` if it gets stuck; `ApnsChannelPool` should be self-sufficient and shouldn't get stuck in the first place.

I opened #589 to address the issue; please let me know what you think!

Again, I offer my apologies for the delay in getting this resolved.

**Comment by jchambers** [comment]
Actually, I'm pretty confident that #589 is the right approach, so I'm going to merge this and get a fresh release out while I have the opportunity. Thanks for the report, tests, and patience!

**Comment by anwerup** [comment]
Thanks for the fix. Moved to v0.12.1 and can no longer recreate the problem

**Comment by jchambers** [comment]
Glad to hear it! Thanks for following up, and thanks again for the report/debugging/patience/pull request ;)
