### ISSUE TITLE
Use Joda-Time or another framework for Date handlings

### ISSUE THREAD

**Issue by klopfdreh** [relayrides/pushy#590]
Hello,

first of all thanks a lot for the great framework!

I just wanted to ask if it is possible to not use java.util.Date, but Joda-Time or another framework to calc time within the classes like:
```java
com.turo.pushy.apns.ApnsPushNotification
```

this would make it possible to do some time calculations directly within the constructor:

```java
new SimpleApnsPushNotification(deviceToken, 
topic, 
apnsPayloadBuilder.buildWithDefaultMaximumLength(),
new DateTime().plusDays(1));
```

What do you think of that?

Let me know if I should create a PR.

**Comment by panchenko** [comment]
@klopfdreh You can do 
`new DateTime().plusDays(1).toDate()` if using joda-time or e.g.
`Date.from(Instant.now().plus(1, ChronoUnit.DAYS))` if using java 8.

Nowadays most of the systems are running on java 8 (since java 7 is EOL ~3 years ago), so -1 for the joda-time dependency.

**Comment by klopfdreh** [comment]
Good point - just wanted the API to guide the user a bit more on how to set the expiry to +2 days. Joda is no option because of what you said.

**Comment by jchambers** [comment]
> just wanted the API to guide the user a bit more on how to set the expiry to +2 days.

Forgive me for splitting hairs on what might just be a word choice thing, but do you mean the API itself (i.e. the `ApnsPushNotification` interface) or the documentation?

**Comment by panchenko** [comment]
I think it's neither API not documentation, but really the `java.util.Date` class, which has some well known issues:
- name is "date", but it's really a timestamp
- mutable
- deals with timezone a bit
- inconvenient for some operations, etc.

@jchambers when you can increase the java version required by the library, it would be nice to replace it with `java.time.Instant`

**Comment by jchambers** [comment]
> when you can increase the java version required by the library, it would be nice to replace it with `java.time.Instant`

Sure; agreed on all points.

We intend to support Java 7 for as long as is practical. While there are certainly things that would be nice to adopt from Java 8 and newer, there's nothing we _need_ from newer versions right now. I don't think this is enough to push us over the line right now (and I understand you're not suggesting that we drop Java 7 support just for this—just want to be clear about the wider philosophy).

**Comment by klopfdreh** [comment]
I mean the API itself. @panchenko explained it very well and I also understand to not drop the support for Java 7 to only have those benefits. Anyway this would be very good if you are decide to go over the line moving to Java 8.

/close

**Comment by jchambers** [comment]
Understood. Thank you for the suggestion!
