### ISSUE TITLE
Micrometer support

### ISSUE THREAD

**Issue by buyukim** [relayrides/pushy#595]
Spring Boot 2 has swapped out Dropwizard Metrics for Micrometer (and its implementations).  Are there any plans to move to this API?

**Comment by jchambers** [comment]
> Are there any plans to move to this API?

It's not on the roadmap, but contributions are welcome!

**Comment by jchambers** [comment]
…to clarify, what we'd want to do here is introduce a new stand-alone listener analogous to the existing [Dropwizard Metrics listener](https://github.com/relayrides/pushy/tree/master/dropwizard-metrics-listener). We would _not_ want to replace Pushy's own [`ApnsClientMetricsListener`](http://relayrides.github.io/pushy/apidocs/0.12/com/turo/pushy/apns/ApnsClientMetricsListener.html).

**Comment by jchambers** [comment]
I took a shot at this in #597. I'm very open to feedback.
