### ISSUE TITLE
Error compiling in Xcode

### ISSUE THREAD

**Issue by EnricoGiordano1992** [relayrides/pushy#601]
Hi, when I compile this library for iOS in Xcode 9.3, I get this error:

PushySDK/PushySDK-Swift.h' file not found

in PushyNotificationPlugin.m at line 9.

What does it mean? How can I resolve this problem?

Thanks

**Comment by jchambers** [comment]
I think you have the wrong project. It sounds like you're looking for https://github.com/pushy-me/pushy-sdk-ios.
