### ISSUE TITLE
Guide for porting from notnoop/java-apns

### ISSUE THREAD

**Issue by jiangbodev** [relayrides/pushy#622]
By searching github with `APN` in `java` category, the project `notnoop/java-apns` listed the first, and `relayrides/pushy` the second.

I have a project which used  `notnoop/java-apns`, consider it has no code update 4 years, I want to port to use `relayrides/pushy`, I'd like to know is there any guide for this porting?

Thanks.

**Comment by jchambers** [comment]
We haven't written a migration guide yet, but would be very interested in your feedback and experience as you make the move, and we can plan to use this issue as a gathering place for questions.

Do you already have specific questions? Are there any areas you're especially concerned about? What would be most helpful to you in a migration guide?

**Comment by jchambers** [comment]
I took a shot at a migration guide at https://github.com/relayrides/pushy/wiki/Migrating-from-java-apns. I'm going to close this issue for now, but please do let us know if there are other topics you think we should address or questions we should answer.

**Comment by AloulouAchraf** [comment]
When i use notnoop/java-apns i can specify sslContext  from ApnsServiceBuilder class. So how can i provide it in relayrides/pushy ?

**Comment by jchambers** [comment]
@AloulouAchraf Could you please move your question to the [mailing list](https://groups.google.com/d/forum/pushy-apns)? This issue has been closed for nearly two years.

**Comment by AloulouAchraf** [comment]
Ok i will move the question to the mailing list.

Le ven. 13 mars 2020 à 21:46, Jon Chambers <notifications@github.com> a
écrit :
