### ISSUE TITLE
What is "topic"? OR rejectionReason='DeviceTokenNotForTopic'

### ISSUE THREAD

**Issue by Tsyklop** [relayrides/pushy#623]
I need send web push notification to Safari browser. I get from it a token.

I use this code:

```
final ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
            payloadBuilder.setAlertBody(body);
            payloadBuilder.setAlertTitle(title);
            payloadBuilder.setLaunchImageFileName(icon);

            SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(TokenUtil.sanitizeTokenString(to), "com.chat2help", payloadBuilder.buildWithDefaultMaximumLength());

            PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                    sendNotificationFuture = apnsClient.sendNotification(pushNotification);

            sendNotificationFuture.addListener(new PushNotificationResponseListener<SimpleApnsPushNotification>() {
                @Override
                public void operationComplete(final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> future) throws Exception {
                    if (future.isSuccess()) {
                        LOGGER.info(sendNotificationFuture.getNow());
                    } else {
                        LOGGER.error("FUTURE ERROR", future.cause());
                    }
                }
            });
```
And i get error:

`SimplePushNotificationResponse{pushNotification=SimpleApnsPushNotification{token='366D8AAB4DAF2C2CD8929EAC549C38BC03CC6540BF188D49B07DD03D9C474871', payload='{"aps":{"alert":{"launch-image":"","body":"Новое сообщение","title":"Новое сообщение"}}}', invalidationTime=Fri Jun 22 10:20:06 CEST 2018, priority=IMMEDIATE, topic='com.mysite', collapseId='null', apnsId=null}, success=false, apnsId=8dfba6ba-aacd-870a-8924-336be5de3335, rejectionReason='DeviceTokenNotForTopic', tokenExpirationTimestamp=null}`

But i don't understand what is `topic`? I do not need a topic. I send a message by token.

**Comment by panchenko** [comment]
* topic should be "Website Push ID" , which identifies your certificate
* DeviceTokenNotForTopic is a mismatch of "website push id" between client (while obtaining a token) and server (while sending a notification)

**Comment by Tsyklop** [comment]
@panchenko Thanks)
