### ISSUE TITLE
Better log errors that should be reported by `tryFailure` but aren't

### ISSUE THREAD

**Issue by mattnathan** [relayrides/pushy#631]
Explicitly I seem to be on a network where the connection-close timeout beats the dns resolution timeout but both happen.

This causes the generic `java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.` to beat the much more specific `java.net.UnknownHostException: failed to resolve 'api.development.push.apple.com' after 4 queries` in `com.turo.pushy.apns.ApnsChannelFactory#create`. I had to debug the code with a breakpoint there to find the cause of the issue.

Would it be possible to change anywhere that `promise.tryFailure(ex)` is called it can be changed to
```java
if (!promise.tryFailure(ex)) {
  logSwallowedError(ex);
}
```

**Comment by mattnathan** [comment]
Yeah, I noticed #625 was fixed in `0.13.3`. I'm using that version though, I guess there are a few edge cases where closing the stream doesn't interrupt the connection future (at least in a timely manner) causing the close to complete before the connection completes.

After some more digging last night this happens for me when Netty decides to try use using my  laptops 4g network interface, even though that interface is not connected, instead of my wifi NIC. This caused it to try and do a dns lookup using the settings there causing the above `UnknownHostException`

**Comment by jchambers** [comment]
> I guess there are a few edge cases where closing the stream doesn't interrupt the connection future

Actually, come to think of it, I'm pretty sure that channel closure happens OUTSIDE of the channel's event loop group. This has caused all kinds of weird issues in the past, and I forgot about it until just now.
