### ISSUE TITLE
Channel pools not guaranteed to ever create more than one channel

### ISSUE THREAD

**Issue by lianyuzhe** [relayrides/pushy#639]
```
        if (!this.isClosed) {
            final Channel channelFromIdlePool = ApnsChannelPool.this.idleChannels.poll();

            if (channelFromIdlePool != null) {
                if (channelFromIdlePool.isActive()) {
                    acquirePromise.trySuccess(channelFromIdlePool);
                } else {
                    // The channel from the idle pool isn't usable; discard it and create a new one instead
                    this.discardChannel(channelFromIdlePool);
                    this.acquireWithinEventExecutor(acquirePromise);
                }
            } else {
             // We don't have any connections ready to go; create a new one if possible.
            }
        }
```
I don't think it is a good idea. When I use it to push, I find some time channel.writeAndFlush use little time, so ApnsClient use only one channel to push. But the time of  apple server response is at 200 pieces per second and I have to set the semaphore to prevent the OOM. Therefore, ApnsClient just sends 200 pieces per second. So In my opinion, we should create max number of  channels in the initialization of ApnsChannelPool.

**Comment by jchambers** [comment]
I wouldn't call this a bug, per se, but think it's an interesting idea all the same. We'll look into it.

**Comment by jchambers** [comment]
Actually, I take it back. I think this _is_ a bug. There's no fundamental guarantee that we'll ever create the number of connections callers are expecting, and are relying on one thread probably being faster than another, which is bogus design.
