### ISSUE TITLE
Is this library suitable for sending notifications to Safari?

### ISSUE THREAD

**Issue by T3rm1** [relayrides/pushy#640]
I digged a lot through the code and documentation but I wasn't able to find out if I can send notifications to Safari with this library.
The only official documentation [here](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html) does not mention a Topic. However the code seems to require a topic.

That's why I suspect sending notifications to Safari can't work. Is this right?

Also, the above linked docs give an example what should be sent to the APN:

    {
    "aps": {
      "alert": {
        "title": "Flight A998 Now Boarding",
        "body": "Boarding has begun for Flight A998.",
        "action": "View"
        },
    "url-args": ["boarding", "A998"]
      }
    }

When looking at `SimpleApnsPushNotification` the fields do not look similar at all.

**Comment by panchenko** [comment]
Yes, you can send push notifications to Safari. The page you mentioned says (under "Pushing Notifications").

> You send push notifications to clients in the same way that iOS and OS X apps push notifications to APNs

Topic would be your _Website Push ID_, and you can find the payload field names in the [ApnsPayloadBuilder ](https://github.com/relayrides/pushy/blob/master/pushy/src/main/java/com/turo/pushy/apns/util/ApnsPayloadBuilder.java#L77) class.

**Comment by jchambers** [comment]
Thanks, @panchenko.

@T3rm1 We generally ask people to move questions about using Pushy (as opposed to bug reports or feature requests) to the [mailing list](https://groups.google.com/forum/#!forum/pushy-apns). I'm going to close this issue for now (@panchenko's answer is correct!), but please feel free to follow up on the mailing list if you have additional questions.

Cheers!
