### ISSUE TITLE
Why not user EpollEventLoopGroup instead of NioEventLoopGroup? 

### ISSUE THREAD

**Issue by frankneu** [relayrides/pushy#647]

**Comment by frankneu** [comment]
NioEventLoopGroup is based on select function in linux system, is there other consideration about this? Generally, epoll's performance is better than select/poll.

PS: forgive my pool English, I come from China.

**Comment by jchambers** [comment]
As you say, epoll is a Linux-specific thing (and has additional dependencies), so we can't make it the default event loop group for all of Pushy.

That said, if you pass an `EpollEventLoopGroup` to [`ApnsClientBuilder#setEventLoopGroup(EventLoopGroup)`](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/ApnsClientBuilder.html#setEventLoopGroup-io.netty.channel.EventLoopGroup-), then Pushy will, indeed, use epoll. Please note that if you pass in your own event loop group, you'll need to shut it down yourself after closing all of the `ApnsClient` instances that are using the event loop group.
