### ISSUE TITLE
FIND_ASCII_SPACE  Error in response

### ISSUE THREAD

**Issue by ganchix** [relayrides/pushy#649]
Hi,

When I send a push notification something strange happens, I received this error:

```
 StackTrace: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: FIND_ASCII_SPACE
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)

```

But the push notification has been sent, and the device received it.

I'm using last Pushy version with Java 8 and Jetty agent 2.0.9.

**Comment by jchambers** [comment]
Very strange indeed.

Please note that the latest version(s) of Pushy _no longer require_ the Jetty ALPN agent. As a debugging step, could you please try removing it and seeing if the problem goes away?

To be clear, I can't imagine how the agent could be causing this problem, but it seems like a worthwhile possibility to eliminate.

**Comment by ganchix** [comment]
Yes! I deleted it and started to work!
Thank you!
