### ISSUE TITLE
10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR 	

### ISSUE THREAD

**Issue by Iris-zhang-072611** [relayrides/pushy#653]
```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
	at com.jxd.test.Test.main(Test.java:40)
```

**Comment by ylgrgyq** [comment]
Please provide more details. Like:
1. Does this happen with every notification? If not, how often does it happen? 
1. Which version of `pushy`, `netty`, `openssl` are you using?
1. Can you provide a way to reproduce this problem?

**Comment by jchambers** [comment]
@Iris-zhang-072611 I'm afraid there isn't enough information here for us to go on. With what we have, though, that sounds more like a problem with your certificate than a problem with Pushy, though.

I'm going to close this issue for now. If you have the opportunity to provide more information, we'll happily revisit the issue.
