### ISSUE TITLE
Support iOS Voip Push ？？

### ISSUE THREAD

**Issue by zhoubo2015** [relayrides/pushy#676]
Support？？
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/OptimizeVoIP.html

**Comment by jchambers** [comment]
I'm sorry—I'm not quite sure what you're asking for. Can you be more specific? Pushy already supports VOIP push notifications (which are exactly the same as normal push notifications—just sent to another topic). Is there something you need that we don't already offer?

**Comment by jchambers** [comment]
Because I _think_ we already support the feature being requested here (@zhoubo2015 please let me know if I'm wrong!), I'm going to close this issue for now.

**Comment by HELLOYUANJIE** [comment]
How to push VoIP push?
