### ISSUE TITLE
RejectionReason's getReasonText method should be public for comparison reasons

### ISSUE THREAD

**Issue by guykatz** [relayrides/pushy#680]
hi;
currently there is no way (that I can tell) to compare rejection reason returning from the notification response and the rejection reason enum due to getReasonText having package visibility instead of public.
for example, the following code will not compile:

```java
// this will not compile as getReasonText is not public to classes outside the pushy package
if(RejectionReason.BAD_DEVICE_TOKEN.getReasonText().equals(pushNotificationResponse.getRejectionReason())
```

this makes it hard to code cleanly. I believe older versions had this ability (0.3 did).
please consider. thanks

**Comment by jchambers** [comment]
Believe it or not, this is actually a deliberate design decision. Please see the discussion in #650 for the rationale. We're always open to new arguments, of course, but I'm going to close this for now.
