### ISSUE TITLE
One JWT token for multiple provider instances

### ISSUE THREAD

**Issue by dmolchun** [relayrides/pushy#682]
Hi,

We're building push delivery service with pushy. Our architecture have multiple instances of microservice which performs delivery using pushy, which all use JWT authentication flow. As it is designed now, pushy completely takes care of JWT token under the hood (AFAIK in TokenAuthenticationApnsClientHandler) and we can not influence this implementation.
I’m afraid that we can face APNs error if each instance will generate a new JWT token, as it described in apple developer documentation: “Similarly, APNs reports an error if you recreate your tokens more than once every 20 minutes” (https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns)
In my case, we want to share JWT token between multiple application instances. From pushy side, this means I need a way to supply pre-defined JWT token and be able to handle it's expiration accordingly. Is where a way how can we do it? Or maybe you can guide me, what to change in pushy to achieve that?

**Comment by jchambers** [comment]
Hello!

This comes up periodically, but I assure you that the intention is to avoid recreating tokens more than once every 20 minutes _on the same connection_. Lots of Pushy users have multiple application instances and have no problems with token rotation. There was an extended [discussion about this on the mailing list](https://groups.google.com/d/msg/pushy-apns/XKnlg8iFvoU/sxD_cblNCQAJ) a little while back, but the punchline is that everything is fine and you don't need to do anything fancy if you're using multiple application nodes.
