### ISSUE TITLE
oom  cased by io.netty.buffer.PoolThreadCache

### ISSUE THREAD

**Issue by tylzvs007** [relayrides/pushy#683]
A problem appeared when I used pushy with the follow version:
<dependency>
            <groupId>com.relayrides</groupId>
            <artifactId>pushy</artifactId>
            <version>0.7.2</version>
</dependency>

OOM happened when some expired p12 files are used to build connection.
![1550902659062-image](https://user-images.githubusercontent.com/9005095/53337037-2948c780-393b-11e9-8ec7-1029c57e50ca.png)

This is my  code:
connectFuture = apnsClient.connect(ApnsClient.DEVELOPMENT_APNS_HOST, ApnsClient.DEFAULT_APNS_PORT); 
connectFuture.get(TIMEOUT_CONNECT, TimeUnit.MILLISECONDS);  //exception happends

But I  am not sure how to resolve it? And I wanna know what the case of it? 
Can you help me to resolve it, thank u very much!

**Comment by jchambers** [comment]
Hi!

While it's possible this problem is still a going concern, you're using version 0.7.3, which is two and a half years old. The current version is 0.13.7. Could you please update to the latest version and see if you're still having this problem?

Thanks!

**Comment by tylzvs007** [comment]
Thank you very much. I will try it.
