### ISSUE TITLE
lost some message

### ISSUE THREAD

**Issue by browanchenjing** [relayrides/pushy#684]
When send 10 messages at the same time,receiver only get 7 or 8 messages

**Comment by jchambers** [comment]
Can you please provide more details? Are you sending ten messages to the same device? How quickly are you sending them? Does the server accept all ten messages?

**Comment by jchambers** [comment]
Closing due to lack of information. @browanchenjing if you have an opportunity to explain the problem in more detail, please do so here and we'll happily reassess.
