### ISSUE TITLE
APNS Critical Alerts Critical flag should be integer 1, not boolean true

### ISSUE THREAD

**Issue by imprivata** [relayrides/pushy#686]
our app was recently approved for APNS Critical Alerts.  In updating my Unit Tests on the server side, I noticed that when I do a 'getPayload' for the JSON created by Pushy the "critical" is a Boolean 'true'.  

performed Critical Alert logic ZZZZ: pushyObject: {"data":{"key1":"value1","key2":"value2"},"aps":{"sound":{"name":"red-alert","critical":true,"volume":1.0},"category":"a category","content-available":1}}

Per Table 3, the critical alert flag should be an integer '1': 

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2990112

**Comment by jchambers** [comment]
This is fixed in #688. Thanks for the report!
