### ISSUE TITLE
UDP Ports leak on calling close on ApnsClient - 0.13.5 

### ISSUE THREAD

**Issue by eugeneseppel** [relayrides/pushy#698]
I've experienced this bug in prod after updating to new Pushy and could easily reproduce situation:

```
    @Test
    public void test1() throws Exception {
        final SimpleApnsPushNotification pushNotification
                = new SimpleApnsPushNotification("apns:xxxxxxxxxxxxxxxxxxxxxxxx",
                DEFAULT_TOPIC, "{}");

        NioEventLoopGroup group = new NioEventLoopGroup(1);
        while (true) {
            final ApnsClient client = new ApnsClientBuilder()
                    .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
                    .setSigningKey(signingKey)
                    .setEventLoopGroup(group)
                    .build();

            client.sendNotification(pushNotification).await();
            client.close().await();

            Thread.sleep(1000);
        }
    }
```

this
$ while true; do netstat -lpn --udp|grep java; sleep 1; done
shows port leak on every iteration
Please see https://github.com/relayrides/pushy/issues/675 for more details or reopen it

**Comment by jchambers** [comment]
I do understand that you're frustrated that I have not yet reopened #675. I promise I will investigate as soon as time allows. In the meantime, while I do not mean to be rude, I'll point out that this is the second time you have opened a duplicate ticket for this issue. This does not help me—or anybody—resolve the issue more quickly, and I respectfully ask that you stop.

**Comment by eugeneseppel** [comment]
I'm sorry if my behaviour looks officious, I asked to reopen the first ticket a month ago, because I provided code that reproduces the issue. However I haven't received any feedback and became afraid this issue could be forgotten as there are no open tickets for it. First time I reopened the ticket with different code, but that was considered as invalid. Thank you!
