### ISSUE TITLE
Update `netty-tcnative-boringssl-static` version

### ISSUE THREAD

**Issue by petrdvorak** [relayrides/pushy#699]

**Comment by jchambers** [comment]
Can you please provide more information/context? Is there something important in the latest version that we should pick up as soon as possible?

**Comment by petrdvorak** [comment]
@jchambers I am sorry for the brief issue - I opened it for myself, I am preparing a PR for this, I don't see a major reason for the update...

Latest Spring Boot 2.1.5 contains a compile-time dependency on [netty-tcnative-boringssl-static-2.0.25.Final](http://central.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.5.RELEASE/spring-boot-dependencies-2.1.5.RELEASE.pom), so this is mostly to be in sync.

**Comment by petrdvorak** [comment]
One quick comment - the initiator for this report was that our Spring Boot app had an issue with missing `SSLPrivateKeyMethod` class (added in `2.0.20+` version of `netty-tcnative-boringssl-static`).
