### ISSUE TITLE
Support for apns-push-type

### ISSUE THREAD

**Issue by ntfromtn** [relayrides/pushy#701]
Via https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc:

> `apns-push-type `
> (**Required when delivering notifications to devices running iOS 13 and later, or watchOS 6 and later.** Ignored on earlier system versions.) The type of the notification. The value of this header is `alert` or `background`. Specify `alert` when the delivery of your notification displays an alert, plays a sound, or badges your app's icon. Specify `background` for silent notifications that do not interact with the user.
>
> The value of this header must accurately reflect the contents of your notification's payload. If there is a mismatch, or if the header is missing on required systems, APNs may delay the delivery of the notification or drop it altogether.
>
> For information about configuring notification alerts, see [Generating a Remote Notification](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification?language=objc). For more information about sending background notifications, see [Pushing Background Updates to Your App](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc).

Thanks,
Nick

**Comment by jchambers** [comment]
Thanks for calling this to our attention. Is there a specific WWDC session where this was announced, or a summary of changes to the docs?

**Comment by ntfromtn** [comment]
Not that I'm aware of.  I noticed this after testing against iOS 13 beta.

**Comment by jchambers** [comment]
Ha—okay. Thanks. Sounds like it's time for the post-WWDC "figure out what changed" festivities!

**Comment by jchambers** [comment]
I took a shot at this in #702. Feedback is welcome!

**Comment by icodebuster** [comment]
@jchambers Any expected timeline for v0.13.9 to be released.
Thank you.
