### ISSUE TITLE
are apns device token same for all apps on a device ?

### ISSUE THREAD

**Issue by anuraggupta** [relayrides/pushy#703]
Looking at the apple documentation 
https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns
```
The device token for one app cannot be used for another app, even when both apps are installed on the same device. Both apps must request their own unique device token and forward it to your provider server. 
```
As per above note the device token should be unique for each app on the same device. But in my practical usage even on my macbook pro (macos Mojave 10.14.5) apps are generating the same device token. 

I'm posting it here just to see if other's are also seeing this issue.

**Comment by jchambers** [comment]
Hello!

I think this is a great question, and would love to learn more about it! That said, I don't know that this is the right venue. We'll have to close this ticket at some point, at which point the discussion will be much harder for future readers to find. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) for exactly that reason.

Let's definitely keep this discussion going, but just move it to a slightly different venue. Thank you!

**Comment by jchambers** [comment]
Also, I noticed that somebody (I'm guessing you) opened a very similar thread on the Apple Developer Forums: https://forums.developer.apple.com/thread/117831

**Comment by anuraggupta** [comment]
> Also, I noticed that somebody (I'm guessing you) opened a very similar thread on the Apple Developer Forums: https://forums.developer.apple.com/thread/117831

That's me

**Comment by jchambers** [comment]
Thanks for moving things to the mailing list! For future readers, the discussion now lives at https://groups.google.com/d/msg/pushy-apns/NwZewuyHzI8/SMDP03oPAQAJ.
