### ISSUE TITLE
The response time of APNs become longer and longer 

### ISSUE THREAD

**Issue by t1mek1ller** [relayrides/pushy#704]
We use pushy(0.13.8) to call APNs. In our business scene,  we need push about ten million notifications in a period of time. The QPS reach our expectations at the beginning of these calls, but APNs's response time become longer and longer as time goes by.  To conclude, APNs response time is unstable.

It is uncertain  whether APNs limits the number of push notifications for one app.   But check the [https://developer.apple.com/library/archive/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG44](url) says 

> There are no caps or batch size limits for using APNs

So, why this happens, anyone has the same problem as I encountered ?

**Comment by jchambers** [comment]
I think we'll need some more information to assess this problem.

Can you say more about how much the response time changes? What kinds of response times do you see at the beginning of the batch? At the end? Do you see proportional increases in CPU/memory consumption?

And if you send a second batch with the same client, does it start fast and end slow, or does it start at a slow speed?

Actually, that's another important question: how many clients are you using, and how many connections does each have?

**Comment by t1mek1ller** [comment]
Thanks for your reply. More information is as follows:

1. Machine and basic config
cpu:4core
mem:8g
connections:8
threads:4

2. CPU and Throughput
Throughput(k/m)    282  391 313 233 226
cpu(%)    33.5 65.1 59.1 50.1 45.5          

3. every client has the same behavior described above

4. we use the Semaphore to limit the number of calls every seconds(6500 calls/s). And we log the time-consuming for each call in the operationComplete method.  we found the response time can change from 160ms to 800ms or even worse.

**Comment by jchambers** [comment]
So to explore your situation a bit more, are you trying to send the entire batch of notifications through a single client, or are there multiple clients in play?

So if you send a big batch and, by the end, notifications are taking 800ms, what happens if you let the client "rest" for a while, then try sending notifications again? Does it pick back up at 800ms, or does it go back down to 160ms?

**Comment by t1mek1ller** [comment]
Only one apnsClient for app.

**Comment by jchambers** [comment]
> t1mek1ller closed this 4 hours ago

Wait—so what was up? How did you resolve this?

**Comment by t1mek1ller** [comment]
Sorry for not reply in time. After check the count of response for one second, we found it was stable for just one ApnsClient(one app). So I think many requests were waiting in the memory queue and hit the limit for in-flight notifications after a period of time.
