### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [relayrides/pushy#708]
Hi
The following lines have cryptographic API misuses.

- File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 146: API name => Signature:
- File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 150: API name => Signature:
- File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 242: API name => Signature:
- File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 246: API name => Signature:
- File name => pushy/src/main/java/com/turo/pushy/apns/P12Util.java: Line number => 59: API name => KeyStore:Operation on object of type java.security.KeyStore object not completed. Expected call to getKey
- File name => pushy/src/main/java/com/turo/pushy/apns/auth/ApnsVerificationKey.java: Line number => 70: API name => Signature:Operation on object of type java.security.Signature object not completed. Expected call to update, verify, <java.security.Signature: void initVerify(java.security.cert.Certificate)>, <java.security.Signature: void initVerify(java.security.PublicKey)>
- File name => pushy/src/main/java/com/turo/pushy/apns/auth/ApnsSigningKey.java: Line number => 63: API name => Signature:Operation on object of type java.security.Signature object not completed. Expected call to <java.security.Signature: void initSign(java.security.PrivateKey)>, update, <java.security.Signature: void initSign(java.security.PrivateKey,java.security.SecureRandom)>
- File name => benchmark/src/main/java/com/turo/pushy/apns/ApnsClientBenchmark.java: Line number => 83: API name => KeyPairGenerator:First parameter (with value "EC") should be any of {RSA, DSA, Diffie-Hellman}
- File name => benchmark/src/main/java/com/turo/pushy/apns/ApnsClientBenchmark.java: Line number => 86: API name => KeyPairGenerator:

**Comment by jchambers** [comment]
Can you please be more specific? Why are these misuses? What should happen instead?

**Comment by jchambers** [comment]
To work through the list of complaints:

> File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 146: API name => Signature:
> File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 150: API name => Signature:
> File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 242: API name => Signature:
> File name => pushy/src/main/java/com/turo/pushy/apns/auth/AuthenticationToken.java: Line number => 246: API name => Signature:
> File name => benchmark/src/main/java/com/turo/pushy/apns/ApnsClientBenchmark.java: Line number => 86: API name => KeyPairGenerator:

None of these "issues" actually specify a problem.

> File name => pushy/src/main/java/com/turo/pushy/apns/P12Util.java: Line number => 59: API name => KeyStore:Operation on object of type java.security.KeyStore object not completed. Expected call to getKey

We load things from the `KeyStore` via `getEntry` instead. There's no requirement that we use `getKey`. This code is clearly working as intended, and "expected call to `getKey`" is, at best, a heuristic that will often be incorrect.

> File name => pushy/src/main/java/com/turo/pushy/apns/auth/ApnsVerificationKey.java: Line number => 70: API name => Signature:Operation on object of type java.security.Signature object not completed. Expected call to update, verify, <java.security.Signature: void initVerify(java.security.cert.Certificate)>, <java.security.Signature: void initVerify(java.security.PublicKey)>
> File name => pushy/src/main/java/com/turo/pushy/apns/auth/ApnsSigningKey.java: Line number => 63: API name => Signature:Operation on object of type java.security.Signature object not completed. Expected call to <java.security.Signature: void initSign(java.security.PrivateKey)>, update, <java.security.Signature: void initSign(java.security.PrivateKey,java.security.SecureRandom)>

In both of these cases, we're creating a `Signature` instance to validate the given algorithm name and `Key`. This is explained in comments and is working as intended.

> File name => benchmark/src/main/java/com/turo/pushy/apns/ApnsClientBenchmark.java: Line number => 83: API name => KeyPairGenerator:First parameter (with value "EC") should be any of {RSA, DSA, Diffie-Hellman}

This is—to be blunt—false. Although the [`KeyPairGenerator` docs](https://docs.oracle.com/javase/7/docs/api/java/security/KeyPairGenerator.html) do call out RSA, DSA, and Diffie-Hellman as algorithms that _must_ be supported by the JDK, other algorithms are certainly allowed (and even widespread).

Beyond that, the APNs protocol demands that we use EC keys in this context.

----

On the whole, it appears you ran a linter against about a thousand projects and dumped the results into issues in each project. While I believe your heart is in the right place, I'd like to offer the (I hope) constructive criticism that it's usually much more helpful to slow down and really understand each of these warnings before filing a report.

In our case, none of the things you've reported appear to actually be problems. It's certainly possible that you'll find a real security issue in another project, but if that's the case, I'd also encourage you to slow down and check the project's policy for disclosing security issues; many have specific expectations for [responsible disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure).

Thank you for your effort, but please give careful thought to your approach going forward.
