### ISSUE TITLE
Where did you find it?The APNs server allows for (at the time of this writing) 1,500 notifications in flight at any time. 

### ISSUE THREAD

**Issue by wuchunzhi235** [relayrides/pushy#709]
I see it in your instructions:You may notice that this leaves us with lots of notifications "in flight" at the same time. The APNs server allows for (at the time of this writing) 1,500 notifications in flight at any time. 

Where did you find "1,500 notifications in flight at any time"? Please give me an official link to Apple.

**Comment by jchambers** [comment]
To the best of my knowledge, that figure is _not_ present in any official documentation.

That figure comes instead from watching the "max concurrent streams" property in the initial [`SETTINGS`](https://httpwg.org/specs/rfc7540.html#SETTINGS) frame we get when connecting to the APNs server. You can check for yourself by [adding a frame logger](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/ApnsClientBuilder.html#setFrameLogger(io.netty.handler.codec.http2.Http2FrameLogger)) to your client.
