### ISSUE TITLE
Support for target-content-id key in aps dictionary.

### ISSUE THREAD

**Issue by Nuthan04** [relayrides/pushy#716]
Hi,

Are there any plans to support "target-content-id" key in aps dictionary.
This key is introduced in iOS 13.
This was announced in this [session.](https://developer.apple.com/videos/play/wwdc2019/259) [seek to 05:05 in video]
Documentation for this can be found [here.](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943363)

**Comment by jchambers** [comment]
I guess we must have missed `target-content-id` among the other announcements. We'll get it in.

**Comment by Nuthan04** [comment]
@jchambers Hope this will be available in the next milestone.
