### ISSUE TITLE
iOS 13 apns-push-type should be "voip" for voip push 

### ISSUE THREAD

**Issue by pankajsinghal** [relayrides/pushy#719]
On iOS 13, VoIP pushes are getting rejected by APNs servers with the reason `InvalidPushType`.  AS mentioned [here](https://forums.developer.apple.com/thread/121083), we require to send `"apns-push-type" : "voip"` for VoIP pushes. But, it's not documented in the [official docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns#2947610).

I've tested it locally by sending a push to my device on iOS 13 and it is indeed true. Would need to add that in `PushType` enum as without that, I'm unable to use this lib.

**Comment by pankajsinghal** [comment]
I've created a PR for the same - https://github.com/relayrides/pushy/pull/720

**Comment by jchambers** [comment]
Huh… it's certainly frustrating that this isn't documented. Let me ask around briefly and see what I can learn.

Thanks for reporting the issue, and thanks for the pull request.

**Comment by bdabrowski32** [comment]
Confirmed in testing as well that `apns-push-type` should be set to voip for VoIP pushes.

**Comment by jchambers** [comment]
> Let me ask around briefly and see what I can learn.

As mentioned in #720, I've learned that there are actually several new values for the `apns-push-type` header, and they should all be documented in the next couple of days. Let's this situation a couple more days to develop so we can get everything at the same time.

**Comment by jchambers** [comment]
Looks like [the docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns) have been updated. I'll augment #720 tomorrow.

**Comment by jchambers** [comment]
I've opened #723 to cover the remaining `apns-push-type` values.

**Comment by stonyz** [comment]
any workaround we have now before 0.13.10 release?
