### ISSUE TITLE
VOIP push phone lock screen for more than 3 minutes without receiving voip push

### ISSUE THREAD

**Issue by HELLOYUANJIE** [relayrides/pushy#728]
VOIP push phone lock screen for more than 3 minutes without receiving voip push,But the response message accepted is true,I don't know if this is a bug,The push code is as follows.

--- 
String payload = new ApnsPayloadBuilder()
                        .setAlertTitle(getTitle())
                        .setAlertBody(getBody())
                        .setContentAvailable(true)
                        .setBadgeNumber(getBadge())
                        .setSound(getSound())
                        .buildWithDefaultMaximumLength();

                SimpleApnsPushNotification notification = new SimpleApnsPushNotification(
                        TokenUtil.sanitizeTokenString(getPushToken()),
                        getSurroundings(),
                        payload,
                        DateUtil.offsetSecond(DateUtil.date(), 60),
                        DeliveryPriority.IMMEDIATE,
                        isVoipPush ? PushType.VOIP : PushType.ALERT,
                        getApnsCollapseId()
                );

                //推送
                PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> pushNotificationFuture = apnsClient.sendNotification(notification);

**Comment by jchambers** [comment]
Hello, and thanks for the report. It sounds like you're describing behavior on the receiving device (but please let me know if I'm misunderstanding). How the receiving device handles the push notification is beyond our control, and I don't think there's any corrective action we can take within Pushy. I'll close this issue for now, but please let me know if I'm misunderstanding the problem and I'll happily revisit the issue.
