### ISSUE TITLE
When using http proxy pushy api is unable to dns lookup & resolve ip address changes when Loadbalancer used for proxies changes ip, forcing restarts.

### ISSUE THREAD

**Issue by KumarVJ12** [relayrides/pushy#731]
unable to resolve ip address changes when Loadbalancer for proxy servers changes ip, forcing restarts.
`ApnsChannelFactory` class uses  `NoopAddressResolverGroup`  if http/https proxy is used .
any specific reason for using `NoopAddressResolverGroup` when using proxy ?
can we provide customization for this or is there any way to add a different resolver.

**Comment by jchambers** [comment]
With apologies for the delay, I'm not entirely sure if I understand the problem.

> unable to resolve ip address changes when Loadbalancer for proxy servers changes ip, forcing restarts.

What, exactly, is changing IP addresses? Do you mean when Apple rotates the IP addresses for their APNs servers?

> any specific reason for using NoopAddressResolverGroup when using proxy?

Yes; generally, when somebody is behind a proxy, the expectation is that the proxy will handle name resolution. If we used a name resolver that actually tried to make DNS queries, those queries might get blocked by whatever firewall is in play.

> can we provide customization for this or is there any way to add a different resolver.

There isn't right now, but we could add it if there's demonstrated need. I don't understand the use case well enough to make a decision about whether that's the right way forward, though. Can you please provide more details about the problem?

**Comment by jchambers** [comment]
@KumarVJ12 I'm afraid I can't act on this without more information. I'll close this issue for now, but will happily revisit it if you can provide more information in the future.

Thanks!
