### ISSUE TITLE
The official document is [api.sandbox.push.apple.com]

### ISSUE THREAD

**Issue by tenlee2012** [relayrides/pushy#734]
The official document is api.sandbox.push.apple.com,
but the code is different
https://github.com/relayrides/pushy/blob/1254c1a2091a44fe3f89c034fc98af268c5841f8/pushy/src/main/java/com/turo/pushy/apns/ApnsClientBuilder.java#L102

**Comment by jchambers** [comment]
Thanks for the heads-up. I wonder when this changed.
