### ISSUE TITLE
how to set apns-expiration header 0 value

### ISSUE THREAD

**Issue by chaekyung** [relayrides/pushy#739]
Thanks for the comfortable library, I have a question.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/
in this link, apple mentioned about 'apns-expiration' header that "If the value is nonzero, APNs stores the notification and tries to deliver it at least once, repeating the attempt as needed until the specified date. If the value is 0, APNs attempts to deliver the notification only once and doesn’t store it."

So, I want to set this header value 0 for immediate purpose, But the constructor of SimpleApnsPushNotification has invalidation time parameter of Date type.

If I set the invalidation time new Date(0), pushy set 'apns-expiration' header value EPOCH? or value 0?

I already read #566 and #593 
But I can't understand the exact way to set 'apns-expiration' header value 0.

Please let me know how to set apns-expiration header value 0.

Thanks

**Comment by jchambers** [comment]
Please see the documentation for [`ApnsPushNotification#getExpiration()`](https://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/ApnsPushNotification.html#getExpiration()). It reads, in part:

> If `null`, the push notification service will not attempt to store the notification at all. Note that APNs will only store one notification per device token for re-delivery at a time.

So, yes, just setting the expiration to `null` will do what you want.

**Comment by chaekyung** [comment]
Thanks a lot.

I will set the value null.
