### ISSUE TITLE
Netty SecureRandom issue

### ISSUE THREAD

**Issue by patrixgdd** [relayrides/pushy#74]
Hi,

It is netty 4.0.18, and pushy is 0.3 with jdk 1.7.0.55 x64 on centos 6.

The tomcat 7.0.53 catalina.out turns out:

Apr 23, 2014 2:19:01 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?

By checking this:
http://netty.io/5.0/xref/io/netty/util/internal/ThreadLocalRandom.html

I think it is thread related issue.

Any helps?

**Comment by whybe** [comment]
I'm using netty-4.0.25-final, but it appeared the WARNNIG unfortunately.
I don't know what is the name of machine running app, but the result of its `uname -a` is `HP-UX nateifsd B.11.11 U 9000/800 3537491374 unlimited-user license`.
And java version is 
```
java version "1.6.0.13"
Java(TM) SE Runtime Environment (build 1.6.0.13-jinteg_01_dec_2011_03_39-b00)
Java HotSpot(TM) Server VM (build 20.3-b02-jre1.6.0.13-rc1b1 PA2.0 (aCC_AP), mixed mode)
```

How can I avoid this warning?

**Comment by neil-mao** [comment]
I saw the issue again.

2015-09-15 21:03:28,470 WARN [io.netty.util.internal.ThreadLocalRandom] 136 - Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?

The application is running under ARM cpu.

agent@agentpi:~/agent$ uname -a
Linux agentpi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux

java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)

Netty version:
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:35:31 +0200

netty-transport-rxtx.version=4.0.20.Final
netty-transport-rxtx.buildDate=2014-06-12 16\:35\:31 +0200
netty-transport-rxtx.commitDate=2014-06-12 16\:14\:48 +0200
netty-transport-rxtx.shortCommitHash=1709113
netty-transport-rxtx.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-transport-rxtx.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:28:52 +0200

netty-common.version=4.0.20.Final
netty-common.buildDate=2014-06-12 16\:28\:52 +0200
netty-common.commitDate=2014-06-12 16\:14\:48 +0200
netty-common.shortCommitHash=1709113
netty-common.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-common.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:30:14 +0200

netty-buffer.version=4.0.20.Final
netty-buffer.buildDate=2014-06-12 16\:30\:14 +0200
netty-buffer.commitDate=2014-06-12 16\:14\:48 +0200
netty-buffer.shortCommitHash=1709113
netty-buffer.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-buffer.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:31:11 +0200

netty-transport.version=4.0.20.Final
netty-transport.buildDate=2014-06-12 16\:31\:11 +0200
netty-transport.commitDate=2014-06-12 16\:14\:48 +0200
netty-transport.shortCommitHash=1709113
netty-transport.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-transport.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:35:03 +0200

netty-codec-socks.version=4.0.20.Final
netty-codec-socks.buildDate=2014-06-12 16\:35\:03 +0200
netty-codec-socks.commitDate=2014-06-12 16\:14\:48 +0200
netty-codec-socks.shortCommitHash=1709113
netty-codec-socks.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-codec-socks.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:33:27 +0200

netty-handler.version=4.0.20.Final
netty-handler.buildDate=2014-06-12 16\:33\:27 +0200
netty-handler.commitDate=2014-06-12 16\:14\:48 +0200
netty-handler.shortCommitHash=1709113
netty-handler.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-handler.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:32:48 +0200

netty-codec.version=4.0.20.Final
netty-codec.buildDate=2014-06-12 16\:32\:48 +0200
netty-codec.commitDate=2014-06-12 16\:14\:48 +0200
netty-codec.shortCommitHash=1709113
netty-codec.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-codec.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:33:59 +0200

netty-codec-http.version=4.0.20.Final
netty-codec-http.buildDate=2014-06-12 16\:33\:59 +0200
netty-codec-http.commitDate=2014-06-12 16\:14\:48 +0200
netty-codec-http.shortCommitHash=1709113
netty-codec-http.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-codec-http.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:36:13 +0200

netty-transport-udt.version=4.0.20.Final
netty-transport-udt.buildDate=2014-06-12 16\:36\:13 +0200
netty-transport-udt.commitDate=2014-06-12 16\:14\:48 +0200
netty-transport-udt.shortCommitHash=1709113
netty-transport-udt.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-transport-udt.repoStatus=clean
#Generated by netty-parent/pom.xml
#Thu, 12 Jun 2014 16:35:49 +0200

netty-transport-sctp.version=4.0.20.Final
netty-transport-sctp.buildDate=2014-06-12 16\:35\:49 +0200
netty-transport-sctp.commitDate=2014-06-12 16\:14\:48 +0200
netty-transport-sctp.shortCommitHash=1709113
netty-transport-sctp.longCommitHash=1709113a1f27be021e890d07c4d94576e2e7710c
netty-transport-sctp.repoStatus=clean

**Comment by skinnermk** [comment]
Firewall blocking the ports causes the issue in redhat. Cleared up by adding ports to the intended interface in firewalld.
firewall-cmd --zone=public --add-port=52489/tcp


Just thought I'd respond with how I fixed it on my system.

**Comment by neil-mao** [comment]
http://stackoverflow.com/questions/28173570/conditions-for-lack-of-entophy-in-threadlocalrandom

cat /proc/sys/kernel/random/entropy_avail
391

Normally,It is large number,when the issue happens, it is small,just 29 .

**Comment by neil-mao** [comment]
http://askubuntu.com/questions/99144/how-can-i-permantly-increase-the-entropy-avail-level

sudo apt-get install haveged -y

It works for me now. really great.
