### ISSUE TITLE
APNs supports notifications without a topic, but Pushy does not

### ISSUE THREAD

**Issue by tca-ms** [relayrides/pushy#740]
Hi,

When using certificate-based authentication, the APNs API allows clients to omit the `apns-topic` header, and will use the bundle ID associated with the certificate as the default topic - see Listing 2 at the bottom of [this page](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns).

However, Pushy does not allow the construction of notifications without specifying a topic. Passing a `null` value for the topic to the constructor of `SimpleApnsPushNotification` gives the following exception:
```
Exception in thread "main" java.lang.NullPointerException: Destination topic must not be null.
        at java.util.Objects.requireNonNull(Objects.java:228)
        at com.turo.pushy.apns.util.SimpleApnsPushNotification.<init>(SimpleApnsPushNotification.java:195)
        at com.turo.pushy.apns.util.SimpleApnsPushNotification.<init>(SimpleApnsPushNotification.java:73)
        at ApnsTest.main(ApnsTest.java:46)
```
and the javadoc on the `ApnsPushNotification` interface states that the `getTopic()` method must not return null.

Would you be willing to remove the `requireNonNull` restriction to support notifications without a topic? I'd be happy to submit a PR for this.

Thanks,
Tom

**Comment by jchambers** [comment]
> Would you be willing to remove the `requireNonNull` restriction to support notifications without a topic?

I certainly understand your point, but this is a deliberate design decision and I don't think we're really open to changing it. In the immediate term, always having a topic avoids some branches internally and makes expectations of callers more consistent. In the future, always having a topic will allow us to do multi-credential clients (we'll need the topic to figure out which credentials to use if multiple certificates are in play).

I appreciate the willingness to contribute, but let's leave this one as-is.

Thanks!
