### ISSUE TITLE
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by thedp** [relayrides/pushy#97]
I'm trying to send push notifications to iOS devices.
I've created a developer certificate for the APNS and bonded it with the application identifier.

I then proceeded to use Pushy to establish a connection to the APNS server, using the examples provided:

``` java
final PushManagerFactory<SimpleApnsPushNotification> pushManagerFactory =
        new PushManagerFactory<SimpleApnsPushNotification>(
                ApnsEnvironment.getSandboxEnvironment(),
                PushManagerFactory.createDefaultSSLContext( DEV_CERT_P12__PATH, DEV_CERT_P12__PASSWORD )
                );

final PushManager<SimpleApnsPushNotification> pushManager = pushManagerFactory.buildPushManager();

pushManager.registerFailedConnectionListener(new MyFailedConnectionListener());

pushManager.start();
```

``` java
public static class MyFailedConnectionListener implements FailedConnectionListener<SimpleApnsPushNotification> {

    public void handleFailedConnection(
            final PushManager<? extends SimpleApnsPushNotification> pushManager,
            final Throwable cause) {

        System.out.println("ERROR  -  "+ cause.toString());

        if (cause instanceof SSLHandshakeException) {

            // This is probably a permanent failure, and we should shut down
            // the PushManager.
        }
    }
}
```

I get this error: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown.

I tried to ask on stackoverflow, by so far no luck: http://stackoverflow.com/questions/24101643/apple-apns-and-entrust-secure-ca-root-certificate
Could it be an issue with Pushy ?

**Comment by srinisubramanian** [comment]
We faced the same issue today.  On a linux server running pushy the p12 file from the Mac works perfectly.  The same on a Windows server running pushy was failing.  Exported and reconverted the certificate and the Windows server pushy started working.  I also noticed that the size of the certificate reduced from 7KB or thereabouts to 3KB after the command line export/convert.  Maybe this is some hint?

**Comment by Tolsi** [comment]
+1 I have the same trouble now

**Comment by jchambers** [comment]
My best guess is that this is being caused by a bug in Keychain Access; we've documented the problem and a workaround on [the wiki](https://github.com/relayrides/pushy/wiki/Certificates). We've also filed a bug report with Apple.

It's worth noting that this problem will basically go away when the APNs servers move to a token-based authentication scheme and we no longer need to present client certificates when connecting; please see #314 for additional details and discussion.

**Comment by Tolsi** [comment]
Thanks, it works, but I think that too little attention is given to it in the readme. It took about an hour to find this solution, I think, not me alone.
