### ISSUE TITLE
configure pushy to use a proxy

### ISSUE THREAD

**Issue by jcesarmobile** [relayrides/pushy#99]
It might be useful for other people (it's useful for me) to add a way to configure a proxy when sending push notifications 

Right now I'm using javapns and they provide a way to configure the proxy, but I can't figure out how to do it with pushy or even if it's possible.

**Comment by herio** [comment]
Is there any estimate of when you can prioritize this issue? For security reasons, we need some feature to enable the proxies configuration.

**Comment by jchambers** [comment]
> Is there any estimate of when you can prioritize this issue?

No; certainly not until Netty 4.1 is released, though. Even then, it's unlikely that this will rise to the top of our own priority list, and we'll likely look for a contributor to provide a pull request rather than implementing it ourselves.

**Comment by jwest-apigee** [comment]
How's it looking for this to be added?  It has been a while since the last update.

**Comment by jchambers** [comment]
@jwest-apigee Maybe never, but in a good way! Is this still a thing that will be helpful after APNs makes the transition to HTTP/2?

**Comment by jchambers** [comment]
I lied! I misunderstood the need here, and I recognize that this is a thing people will need even though we've shipped HTTP/2 support. Please take a look at #215 and let me know if it will meet your needs.

Thanks!

**Comment by jchambers** [comment]
Folks, if anybody has the opportunity, could you please give the changes in #215 a try and let us know if they do what you need? I'm confident in the architecture, but we're not well-positioned to do real-world testing.

@jwest-apigee To answer your question from earlier, I think this is ready to go just as soon as we get confirmation that it's working for people in the real world.

Thanks, everybody!

**Comment by jwest-apigee** [comment]
Rock on, I will try to test it soon.  Thanks!!

**Comment by jwest-apigee** [comment]
We are tracking it under https://issues.apache.org/jira/browse/USERGRID-1240.

**Comment by jchambers** [comment]
I'm reasonably confident that this is good from "lab" testing, so I went ahead and merged it. Please let me know if it seems like that's a bad call.
